/* scexplain.c -- see scexplain.h. Function-for-function from
 * ssb-decomp-re/src/sc/sccommon/scexplain.c, REGION_US arms; the line
 * numbers in each function's own comment are the decomp's. The three
 * DIVERGES (the Hyrule ground/collision/wallpaper fallback, the
 * compiled-in KeyEvent/ExplainPhase data, and the missing control-stick
 * diagram) are explained once, in scexplain.h's own header comment --
 * not repeated at every site they touch.
 */
#include "scexplain.h"
#include "overlay.h"

#include "ftcommon.h"
#include "gmcamera.h"
#include "lbcommon.h" /* lbCommonSpriteFillRect */
#include "lbpartex.h" /* lbpTexFreeAll */
#include "gmcommon.h"
#include "ifcommon.h"
#include "input.h"
#include "scmanager.h"
#include "sprite.h"
#include "lbpdraw.h"
#include "efmanager.h"
#include "fighter.h"
#include "objmodel.h"
#include "itemmodel.h"
#include "wpattrs.h"
#include "assetroot.h"
#include "stage.h"
#include "taskman.h"

#include <ef/efdisplay.h>
#include <ef/efparticle.h>
#include <ef/effect.h>
#include <ft/fighter.h>
#include <ft/ftdef.h>
#include <ft/ftparam.h>
#include <ft/ftpublic.h>
#include <gm/gmrumble.h>
#include <gm/gmsound.h>
#include <gr/ground.h>
#include <sys/utils.h>    /* syUtilsSetRandomSeedPtr */
#include <if/ifcommon.h>
#include <if/interface.h>
#include <it/item.h>
#include <mp/map.h>
#include <sys/controller.h>
#include <sys/rdp.h> /* syRdpSetViewport */
#include <wp/wpmanager.h> /* wpManagerAllocWeapons */
#include <lb/lbdef.h>
#include <lb/lbfade.h>

/* n_env.c:5128, the FGM voice-cue wrapper every scene entry calls --
 * declared in src/dc/ftcommon.h (already included above), defined in
 * src/dc/fgm.c. scexplain.c's own call (scExplainFuncStart below) passes
 * nSYAudioVoiceAnnounceHowToPlay, not an FGM id -- func_800269C0_275C0
 * takes either (src/dc/itkamex.c's own nSYAudioVoiceMBallKamexAppear
 * call is the same shape). */

/* The game reaches a sprite as a file's base plus the offset its link
 * label took; the port's file is a bank and the label's value is the
 * offset (src/dc/mncongra.c and src/dc/mnoption.c do the same). Only
 * scExplainGraphicsFileHead uses this now -- the KeyEvent/ExplainPhase
 * half of file 252 is compiled in below instead of reloc-loaded (see
 * scexplain.h). */
#undef lbRelocGetFileData
#define lbRelocGetFileData(type, file, offset) \
    ((type)sprite_bank_get((SpriteBank *)(file), (u32)(offset)))

/* ---- the pools --------------------------------------------------------
 *
 * scexplain.c:55-97 dSCExplainTaskmanSetup carries zero for every pool
 * count, the same placeholder scvsbattle.c:24-64/scautodemo.c:56-73
 * document. This scene is the same battle spine with two fighters
 * instead of four and no countdown/timer/entry sequence, but adds its
 * own decorative interface GObjs (the window/text/[cut control-stick]
 * cameras, six phase-indicator SObjs, the textbox SObj) that scvsbattle.c
 * and scautodemo.c do not carry -- so this reuses scautodemo.c's own
 * figures rather than scaling scvsbattle.c's down, the safe upper bound
 * either way. */
#define SCEXPLAIN_GOBJS       48
#define SCEXPLAIN_GOBJPROCS   48
#define SCEXPLAIN_XOBJS      288
#define SCEXPLAIN_AOBJS      576
#define SCEXPLAIN_MOBJS       32
#define SCEXPLAIN_DOBJS       96
#define SCEXPLAIN_SOBJS       96
#define SCEXPLAIN_COBJS        6

// // // // // // // // // // // //
//                               //
//       INITIALIZED DATA        //
//                               //
// // // // // // // // // // // //

/* scexplain.c:16 dSCExplainInterfacePositions, verbatim: the four
 * player-tag/damage-digit column x-positions (only the first two are
 * ever read -- pl_count is always 2). */
s32 dSCExplainInterfacePositions[4] = { 55, 125, 195, 265 };

/* scexplain.c:43 dSCExplainFadeColor, verbatim: opaque black, the same
 * "from the colour to the scene" alpha-0 convention scautodemo.c's own
 * dSCAutoDemoFadeColor uses. */
SYColorRGBA dSCExplainFadeColor = { 0x00, 0x00, 0x00, 0x00 };

/* scexplain.c:45-49 dSCExplainRandomSeed1/2, verbatim: the two random
 * streams the demo runs on, one for the update and one for the draw,
 * both seeded at 1 so every showing plays the same. syUtils's generator
 * writes through the pointer, so unlike the rest of the overlay's .data
 * these ARE written; scExplainOverlayLoad puts them back. */
s32 dSCExplainRandomSeed1 = 0x00000001;
s32 dSCExplainRandomSeed2 = 0x00000001;

/* scexplain.c:55-97 dSCExplainTaskmanSetup, DIVERGES the same shape
 * src/dc/scautodemo.c's own dSCAutoDemoTaskmanSetup documents: the DL
 * buffers/graphics arena/RDP output are zeroed (no RSP/RDP here),
 * func_lights is NULL (scExplainFuncLights is not ported -- dropped
 * reflection lighting), arena_start is NULL, the matrix function list
 * is NULL (the matrix kinds are a switch in objdisplay.c). */
SYTaskmanSetup dSCExplainTaskmanSetup =
{
    {
        0,                              /* flags */
        scExplainFuncUpdate,            /* update function */
        scExplainFuncDraw,              /* frame draw function */
        NULL,                           /* allocatable memory pool start */
        0,                              /* allocatable memory pool size */
        1,                              /* ??? */
        2,                              /* number of contexts? */
        0, 0, 0, 0,                     /* the four DL buffer sizes */
        0,                              /* graphics heap size */
        2,                              /* ??? */
        0,                              /* RDP output buffer size */
        NULL,                           /* pre-render function */
        syControllerFuncRead,           /* controller I/O function */
    },

    0,                                  /* number of GObjThreads */
    sizeof(u64) * 192,                  /* thread stack size */
    0,                                  /* number of thread stacks */
    0,                                  /* ??? */
    SCEXPLAIN_GOBJPROCS,
    SCEXPLAIN_GOBJS,   sizeof(GObj),
    SCEXPLAIN_XOBJS,
    NULL,                               /* matrix function list */
    NULL,                               /* DObjVec eject function */
    SCEXPLAIN_AOBJS,
    SCEXPLAIN_MOBJS,
    SCEXPLAIN_DOBJS,   sizeof(DObj),
    SCEXPLAIN_SOBJS,   sizeof(SObj),
    SCEXPLAIN_COBJS,   sizeof(CObj),

    scExplainFuncStart                  /* task start function */
};

/* relocData/252_SCExplainMain.c:71-1249 dSCExplainMain_0_KeyEvent,
 * REGION_US arm, verbatim (every #if defined(REGION_JP) block dropped,
 * the region-stripping convention every REGION_US-only port file
 * follows) -- Mario's canned How to Play input script,
 * ftKeyProcessKeyEvents' (src/dc/ftcommon.c) first real exercise: 1258
 * halfwords of real stick/button taps, not a synthetic
 * host-test-only script. See scexplain.h's header note on why this is
 * compiled in rather than reloc-loaded. */
const FTKeyEvent dSCExplainKeyEvent0[1258] = {
	FTKEY_EVENT_STICK(0, 0, 0),
	FTKEY_EVENT_STICK(2, 0, 130),
	FTKEY_EVENT_STICK(-32, 0, 1),
	FTKEY_EVENT_STICK(-36, -1, 1),
	FTKEY_EVENT_STICK(-47, -1, 1),
	FTKEY_EVENT_STICK(-67, -1, 1),
	FTKEY_EVENT_STICK(-75, -1, 120),
	FTKEY_EVENT_STICK(75, -7, 1),
	FTKEY_EVENT_STICK(76, -2, 21),
	FTKEY_EVENT_STICK(74, -2, 19),
	FTKEY_EVENT_STICK(0, -1, 129),
	FTKEY_EVENT_STICK(0, 82, 1),
	FTKEY_EVENT_STICK(0, 81, 1),
	FTKEY_EVENT_STICK(-1, 81, 1),
	FTKEY_EVENT_STICK(-1, 82, 4),
	FTKEY_EVENT_STICK(1, 55, 1),
	FTKEY_EVENT_STICK(0, -1, 98),
	FTKEY_EVENT_STICK(-68, 66, 4),
	FTKEY_EVENT_STICK(73, -7, 10),
	FTKEY_EVENT_STICK(3, 2, 35),
	FTKEY_EVENT_STICK(0, 1, 2),
	FTKEY_EVENT_STICK(61, 70, 3),
	FTKEY_EVENT_STICK(0, -1, 2),
	FTKEY_EVENT_STICK(-18, -5, 1),
	FTKEY_EVENT_STICK(-24, -9, 1),
	FTKEY_EVENT_STICK(-1, -2, 2),
	FTKEY_EVENT_STICK(0, -2, 3),
	FTKEY_EVENT_STICK(-74, -2, 2),
	FTKEY_EVENT_STICK(-74, -3, 1),
	FTKEY_EVENT_STICK(-74, -2, 5),
	FTKEY_EVENT_STICK(-74, -3, 4),
	FTKEY_EVENT_STICK(50, -2, 1),
	FTKEY_EVENT_STICK(67, -2, 1),
	FTKEY_EVENT_STICK(71, -2, 3),
	FTKEY_EVENT_STICK(0, 1, 100),
	FTKEY_EVENT_BUTTON(A_BUTTON, 2),
	FTKEY_EVENT_BUTTON(0, 8),
	FTKEY_EVENT_BUTTON(A_BUTTON, 6),
	FTKEY_EVENT_BUTTON(0, 2),
	FTKEY_EVENT_BUTTON(A_BUTTON, 4),
	FTKEY_EVENT_BUTTON(0, 2),
	FTKEY_EVENT_BUTTON(A_BUTTON, 4),
	FTKEY_EVENT_BUTTON(0, 30),
	FTKEY_EVENT_BUTTON(A_BUTTON, 2),
	FTKEY_EVENT_BUTTON(0, 8),
	FTKEY_EVENT_BUTTON(A_BUTTON, 6),
	FTKEY_EVENT_BUTTON(0, 8),
	FTKEY_EVENT_BUTTON(A_BUTTON, 2),
	FTKEY_EVENT_BUTTON(0, 5),
	FTKEY_EVENT_STICK(0, 0, 1),
	FTKEY_EVENT_STICK(0, 1, 19),
	FTKEY_EVENT_STICK(-1, 37, 5),
	FTKEY_EVENT_STICK(-1, 36, 7),
	FTKEY_EVENT_STICK(-1, 39, 11),
	FTKEY_EVENT_STICK(0, 1, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 2),
	FTKEY_EVENT_BUTTON(0, 18),
	FTKEY_EVENT_STICK(0, 4, 1),
	FTKEY_EVENT_STICK(0, 10, 1),
	FTKEY_EVENT_STICK(0, 11, 2),
	FTKEY_EVENT_STICK(0, 13, 1),
	FTKEY_EVENT_STICK(1, 27, 2),
	FTKEY_EVENT_STICK(1, 30, 1),
	FTKEY_EVENT_STICK(1, 32, 1),
	FTKEY_EVENT_STICK(1, 37, 25),
	FTKEY_EVENT_BUTTON(A_BUTTON, 2),
	FTKEY_EVENT_BUTTON(0, 5),
	FTKEY_EVENT_STICK(0, -1, 30),
	FTKEY_EVENT_STICK(0, 1, 1),
	FTKEY_EVENT_STICK(3, 0, 7),
	FTKEY_EVENT_STICK(10, 0, 4),
	FTKEY_EVENT_STICK(15, 0, 1),
	FTKEY_EVENT_BUTTON(A_BUTTON, 2),
	FTKEY_EVENT_STICK(1, 0, 0),
	FTKEY_EVENT_BUTTON(0, 2),
	FTKEY_EVENT_STICK(25, 0, 1),
	FTKEY_EVENT_STICK(26, 0, 4),
	FTKEY_EVENT_STICK(9, 0, 1),
	FTKEY_EVENT_STICK(7, 0, 1),
	FTKEY_EVENT_STICK(9, 0, 1),
	FTKEY_EVENT_STICK(11, 0, 3),
	FTKEY_EVENT_STICK(17, 0, 7),
	FTKEY_EVENT_STICK(25, 0, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_BUTTON(0, 5),
	FTKEY_EVENT_STICK(0, 0, 8),
	FTKEY_EVENT_STICK(0, -1, 3),
	FTKEY_EVENT_STICK(0, -2, 1),
	FTKEY_EVENT_STICK(2, -1, 2),
	FTKEY_EVENT_STICK(2, -2, 1),
	FTKEY_EVENT_STICK(0, -2, 1),
	FTKEY_EVENT_STICK(0, -1, 10),
	FTKEY_EVENT_STICK(1, -6, 1),
	FTKEY_EVENT_STICK(24, -75, 2),
	FTKEY_EVENT_STICK(26, -75, 1),
	FTKEY_EVENT_STICK(24, -75, 17),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_STICK(25, -75, 1),
	FTKEY_EVENT_STICK(26, -76, 2),
	FTKEY_EVENT_BUTTON(0, 2),
	FTKEY_EVENT_STICK(3, -1, 49),
	FTKEY_EVENT_STICK(3, 4, 3),
	FTKEY_EVENT_STICK(3, 2, 5),
	FTKEY_EVENT_STICK(3, 3, 6),
	FTKEY_EVENT_STICK(2, 79, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 2),
	FTKEY_EVENT_STICK(2, -2, 0),
	FTKEY_EVENT_BUTTON(0, 74),
	FTKEY_EVENT_STICK(5, -2, 1),
	FTKEY_EVENT_STICK(2, -I_CONTROLLER_RANGE_MAX, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_STICK(0, -2, 0),
	FTKEY_EVENT_BUTTON(0, 1),
	FTKEY_EVENT_STICK(1, -2, 35),
	FTKEY_EVENT_STICK(0, -1, 3),
	FTKEY_EVENT_STICK(1, -1, 3),
	FTKEY_EVENT_STICK(68, 17, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 2),
	FTKEY_EVENT_STICK(68, 18, 1),
	FTKEY_EVENT_STICK(0, 1, 0),
	FTKEY_EVENT_BUTTON(Z_TRIG, 1),
	FTKEY_EVENT_STICK(2, -1, 0),
	FTKEY_EVENT_BUTTON(0, 30),
	FTKEY_EVENT_STICK(0, 0, 1),
	FTKEY_EVENT_STICK(-76, -1, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_STICK(1, -1, 0),
	FTKEY_EVENT_BUTTON(0, 10),
	FTKEY_EVENT_STICK(5, -79, 10),
	FTKEY_EVENT_STICK(5, -I_CONTROLLER_RANGE_MAX, 5),
	FTKEY_EVENT_STICK(7, -78, 1),
	FTKEY_EVENT_STICK(17, -14, 1),
	FTKEY_EVENT_STICK(1, -1, 19),
	FTKEY_EVENT_STICK(-75, -1, 3),
	FTKEY_EVENT_STICK(-75, -3, 8),
	FTKEY_EVENT_STICK(-76, -6, 3),
	FTKEY_EVENT_STICK(3, 1, 1),
	FTKEY_EVENT_STICK(-74, -11, 26),
	FTKEY_EVENT_STICK(0, 0, 1),
	FTKEY_EVENT_STICK(2, 1, 1),
	FTKEY_EVENT_STICK(3, 0, 1),
	FTKEY_EVENT_STICK(0, -1, 117),
	FTKEY_EVENT_STICK(21, -1, 1),
	FTKEY_EVENT_STICK(37, 1, 1),
	FTKEY_EVENT_STICK(38, 1, 1),
	FTKEY_EVENT_STICK(0, -1, 2),
	FTKEY_EVENT_STICK(0, -2, 1),
	FTKEY_EVENT_STICK(1, -1, 1),
	FTKEY_EVENT_STICK(0, -1, 2),
	FTKEY_EVENT_STICK(0, 4, 1),
	FTKEY_EVENT_STICK(0, 13, 2),
	FTKEY_EVENT_STICK(0, 25, 1),
	FTKEY_EVENT_STICK(0, 31, 1),
	FTKEY_EVENT_STICK(0, 38, 1),
	FTKEY_EVENT_STICK(0, 40, 1),
	FTKEY_EVENT_STICK(0, 47, 1),
	FTKEY_EVENT_STICK(0, 50, 1),
	FTKEY_EVENT_STICK(0, 34, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 2),
	FTKEY_EVENT_BUTTON(0, 8),
	FTKEY_EVENT_STICK(1, 1, 1),
	FTKEY_EVENT_STICK(3, 1, 5),
	FTKEY_EVENT_STICK(0, 1, 4),
	FTKEY_EVENT_STICK(1, 1, 2),
	FTKEY_EVENT_STICK(0, 1, 2),
	FTKEY_EVENT_STICK(1, 1, 2),
	FTKEY_EVENT_STICK(2, 1, 1),
	FTKEY_EVENT_STICK(1, 1, 13),
	FTKEY_EVENT_STICK(2, 1, 2),
	FTKEY_EVENT_STICK(1, 1, 25),
	FTKEY_EVENT_STICK(3, 1, 41),
	FTKEY_EVENT_STICK(3, 46, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_STICK(2, 0, 0),
	FTKEY_EVENT_BUTTON(0, 2),
	FTKEY_EVENT_STICK(3, 1, 2),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(0, 1, 7),
	FTKEY_EVENT_STICK(1, 1, 24),
	FTKEY_EVENT_STICK(2, 1, 2),
	FTKEY_EVENT_STICK(1, 1, 14),
	FTKEY_EVENT_STICK(3, 1, 1),
	FTKEY_EVENT_STICK(5, 1, 1),
	FTKEY_EVENT_STICK(12, 1, 10),
	FTKEY_EVENT_STICK(1, 1, 18),
	FTKEY_EVENT_STICK(0, 2, 1),
	FTKEY_EVENT_STICK(1, 18, 1),
	FTKEY_EVENT_STICK(0, 22, 2),
	FTKEY_EVENT_STICK(0, 25, 12),
	FTKEY_EVENT_BUTTON(A_BUTTON, 3),
	FTKEY_EVENT_STICK(0, 23, 0),
	FTKEY_EVENT_BUTTON(0, 3),
	FTKEY_EVENT_STICK(0, 21, 1),
	FTKEY_EVENT_STICK(0, 2, 2),
	FTKEY_EVENT_STICK(1, -1, 29),
	FTKEY_EVENT_STICK(18, 3, 1),
	FTKEY_EVENT_STICK(34, 3, 11),
	FTKEY_EVENT_STICK(35, 3, 27),
	FTKEY_EVENT_STICK(3, 1, 15),
	FTKEY_EVENT_STICK(3, 4, 7),
	FTKEY_EVENT_STICK(3, 12, 1),
	FTKEY_EVENT_STICK(3, 20, 1),
	FTKEY_EVENT_STICK(3, 31, 7),
	FTKEY_EVENT_BUTTON(A_BUTTON, 2),
	FTKEY_EVENT_BUTTON(0, 4),
	FTKEY_EVENT_STICK(0, -2, 38),
	FTKEY_EVENT_STICK(0, -1, 3),
	FTKEY_EVENT_STICK(2, -1, 1),
	FTKEY_EVENT_STICK(31, 0, 1),
	FTKEY_EVENT_STICK(41, 1, 1),
	FTKEY_EVENT_STICK(46, 1, 32),
	FTKEY_EVENT_STICK(3, 1, 2),
	FTKEY_EVENT_STICK(0, 77, 2),
	FTKEY_EVENT_STICK(2, -1, 1),
	FTKEY_EVENT_STICK(2, 0, 9),
	FTKEY_EVENT_STICK(3, 0, 2),
	FTKEY_EVENT_STICK(70, 4, 2),
	FTKEY_EVENT_STICK(3, 2, 2),
	FTKEY_EVENT_STICK(68, 10, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_BUTTON(0, 3),
	FTKEY_EVENT_STICK(68, 9, 1),
	FTKEY_EVENT_STICK(3, 1, 7),
	FTKEY_EVENT_STICK(-35, -15, 1),
	FTKEY_EVENT_STICK(-70, -33, 1),
	FTKEY_EVENT_STICK(-73, -28, 1),
	FTKEY_EVENT_STICK(-73, -25, 1),
	FTKEY_EVENT_STICK(-69, -41, 1),
	FTKEY_EVENT_STICK(-69, -39, 1),
	FTKEY_EVENT_STICK(-69, -38, 1),
	FTKEY_EVENT_STICK(-63, -30, 1),
	FTKEY_EVENT_STICK(0, 0, 12),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-10, -1, 13),
	FTKEY_EVENT_STICK(-28, -9, 1),
	FTKEY_EVENT_STICK(-55, -13, 1),
	FTKEY_EVENT_STICK(-73, -18, 16),
	FTKEY_EVENT_STICK(3, 1, 29),
	FTKEY_EVENT_BUTTON(A_BUTTON, 2),
	FTKEY_EVENT_BUTTON(0, 5),
	FTKEY_EVENT_STICK(0, 1, 1),
	FTKEY_EVENT_STICK(1, -1, 1),
	FTKEY_EVENT_STICK(0, 4, 1),
	FTKEY_EVENT_STICK(2, 1, 10),
	FTKEY_EVENT_BUTTON(Z_TRIG, 1),
	FTKEY_EVENT_STICK(11, 1, 1),
	FTKEY_EVENT_STICK(70, 0, 1),
	FTKEY_EVENT_STICK(0, 1, 0),
	FTKEY_EVENT_BUTTON(0, 1),
	FTKEY_EVENT_STICK(0, 0, 38),
	FTKEY_EVENT_STICK(0, 1, 2),
	FTKEY_EVENT_STICK(-45, -3, 1),
	FTKEY_EVENT_STICK(-41, -4, 2),
	FTKEY_EVENT_STICK(-46, -6, 1),
	FTKEY_EVENT_STICK(-52, -6, 15),
	FTKEY_EVENT_STICK(3, -2, 4),
	FTKEY_EVENT_STICK(2, -2, 2),
	FTKEY_EVENT_STICK(3, -2, 1),
	FTKEY_EVENT_STICK(0, -2, 1),
	FTKEY_EVENT_STICK(-18, -3, 16),
	FTKEY_EVENT_STICK(-17, -1, 1),
	FTKEY_EVENT_STICK(-20, -1, 8),
	FTKEY_EVENT_STICK(-8, -1, 1),
	FTKEY_EVENT_STICK(-12, -1, 7),
	FTKEY_EVENT_STICK(2, -1, 35),
	FTKEY_EVENT_STICK(5, -1, 1),
	FTKEY_EVENT_STICK(10, -1, 3),
	FTKEY_EVENT_STICK(3, -1, 13),
	FTKEY_EVENT_STICK(2, 1, 4),
	FTKEY_EVENT_STICK(69, -5, 1),
	FTKEY_EVENT_STICK(70, -4, 3),
	FTKEY_EVENT_STICK(3, 1, 1),
	FTKEY_EVENT_STICK(2, 1, 1),
	FTKEY_EVENT_STICK(-44, 1, 1),
	FTKEY_EVENT_STICK(2, 1, 1),
	FTKEY_EVENT_STICK(3, 1, 4),
	FTKEY_EVENT_STICK(1, 1, 3),
	FTKEY_EVENT_STICK(3, 1, 6),
	FTKEY_EVENT_STICK(1, -1, 1),
	FTKEY_EVENT_STICK(3, 1, 1),
	FTKEY_EVENT_STICK(2, 1, 58),
	FTKEY_EVENT_STICK(0, -1, 3),
	FTKEY_EVENT_STICK(3, -1, 1),
	FTKEY_EVENT_STICK(2, -1, 1),
	FTKEY_EVENT_STICK(1, -1, 5),
	FTKEY_EVENT_STICK(2, -1, 1),
	FTKEY_EVENT_STICK(1, -1, 5),
	FTKEY_EVENT_BUTTON(Z_TRIG, 2),
	FTKEY_EVENT_STICK(3, 0, 0),
	FTKEY_EVENT_BUTTON(0, 12),
	FTKEY_EVENT_STICK(2, -1, 1),
	FTKEY_EVENT_STICK(3, -1, 1),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(2, -1, 1),
	FTKEY_EVENT_STICK(3, -1, 1),
	FTKEY_EVENT_STICK(2, -1, 13),
	FTKEY_EVENT_STICK(1, -1, 19),
	FTKEY_EVENT_STICK(3, -2, 25),
	FTKEY_EVENT_STICK(4, -2, 5),
	FTKEY_EVENT_STICK(4, -3, 5),
	FTKEY_EVENT_STICK(7, -78, 2),
	FTKEY_EVENT_STICK(2, 0, 1),
	FTKEY_EVENT_STICK(1, -1, 2),
	FTKEY_EVENT_STICK(1, -I_CONTROLLER_RANGE_MAX, 1),
	FTKEY_EVENT_STICK(1, -1, 2),
	FTKEY_EVENT_STICK(52, -1, 1),
	FTKEY_EVENT_STICK(70, -1, 7),
	FTKEY_EVENT_STICK(1, -2, 1),
	FTKEY_EVENT_STICK(-1, -2, 1),
	FTKEY_EVENT_STICK(-67, -2, 1),
	FTKEY_EVENT_STICK(-74, -2, 3),
	FTKEY_EVENT_STICK(2, -2, 1),
	FTKEY_EVENT_STICK(-4, -2, 1),
	FTKEY_EVENT_STICK(-61, -2, 1),
	FTKEY_EVENT_STICK(-75, -2, 10),
	FTKEY_EVENT_STICK(2, 1, 4),
	FTKEY_EVENT_STICK(-3, 81, 1),
	FTKEY_EVENT_STICK(-4, 81, 1),
	FTKEY_EVENT_STICK(-3, 79, 1),
	FTKEY_EVENT_STICK(0, 1, 5),
	FTKEY_EVENT_STICK(1, 1, 2),
	FTKEY_EVENT_STICK(0, 1, 14),
	FTKEY_EVENT_STICK(1, 1, 1),
	FTKEY_EVENT_STICK(0, 1, 21),
	FTKEY_EVENT_STICK(2, 2, 5),
	FTKEY_EVENT_STICK(2, 77, 0),
	FTKEY_EVENT_BUTTON(B_BUTTON, 2),
	FTKEY_EVENT_STICK(1, 77, 0),
	FTKEY_EVENT_BUTTON(0, 1),
	FTKEY_EVENT_STICK(-16, 74, 1),
	FTKEY_EVENT_STICK(-39, 53, 1),
	FTKEY_EVENT_STICK(-50, 32, 1),
	FTKEY_EVENT_STICK(0, 1, 8),
	FTKEY_EVENT_STICK(0, -1, 2),
	FTKEY_EVENT_STICK(0, 0, 7),
	FTKEY_EVENT_STICK(1, 0, 1),
	FTKEY_EVENT_STICK(1, 1, 1),
	FTKEY_EVENT_STICK(1, 0, 1),
	FTKEY_EVENT_STICK(2, 0, 1),
	FTKEY_EVENT_STICK(1, 0, 1),
	FTKEY_EVENT_STICK(2, 0, 1),
	FTKEY_EVENT_STICK(1, 0, 12),
	FTKEY_EVENT_STICK(3, 1, 1),
	FTKEY_EVENT_STICK(3, 0, 1),
	FTKEY_EVENT_STICK(0, 0, 13),
	FTKEY_EVENT_STICK(2, 79, 1),
	FTKEY_EVENT_STICK(0, 79, 1),
	FTKEY_EVENT_STICK(1, 79, 3),
	FTKEY_EVENT_STICK(1, 1, 1),
	FTKEY_EVENT_STICK(2, 1, 3),
	FTKEY_EVENT_STICK(1, 1, 1),
	FTKEY_EVENT_STICK(2, 1, 1),
	FTKEY_EVENT_STICK(3, 1, 3),
	FTKEY_EVENT_STICK(1, 1, 1),
	FTKEY_EVENT_STICK(3, 1, 3),
	FTKEY_EVENT_STICK(1, 1, 2),
	FTKEY_EVENT_STICK(2, 1, 1),
	FTKEY_EVENT_STICK(0, 1, 1),
	FTKEY_EVENT_STICK(1, 1, 1),
	FTKEY_EVENT_STICK(3, 1, 1),
	FTKEY_EVENT_STICK(2, 1, 2),
	FTKEY_EVENT_STICK(0, 0, 5),
	FTKEY_EVENT_STICK(1, 0, 1),
	FTKEY_EVENT_STICK(0, 0, 1),
	FTKEY_EVENT_STICK(2, 0, 1),
	FTKEY_EVENT_STICK(3, 0, 1),
	FTKEY_EVENT_STICK(2, 0, 1),
	FTKEY_EVENT_STICK(2, -1, 1),
	FTKEY_EVENT_STICK(1, -1, 6),
	FTKEY_EVENT_STICK(1, 0, 1),
	FTKEY_EVENT_STICK(1, -1, 1),
	FTKEY_EVENT_STICK(2, 0, 12),
	FTKEY_EVENT_BUTTON(B_BUTTON, 1),
	FTKEY_EVENT_BUTTON(0, 18),
	FTKEY_EVENT_STICK(1, 0, 42),
	FTKEY_EVENT_STICK(3, 21, 1),
	FTKEY_EVENT_STICK(3, 0, 1),
	FTKEY_EVENT_STICK(1, 78, 0),
	FTKEY_EVENT_BUTTON(B_BUTTON, 2),
	FTKEY_EVENT_STICK(2, -1, 0),
	FTKEY_EVENT_BUTTON(0, 1),
	FTKEY_EVENT_STICK(3, 1, 2),
	FTKEY_EVENT_STICK(2, 1, 30),
	FTKEY_EVENT_STICK(3, 1, 8),
	FTKEY_EVENT_STICK(2, 1, 7),
	FTKEY_EVENT_STICK(3, 1, 11),
	FTKEY_EVENT_STICK(2, -82, 3),
	FTKEY_EVENT_STICK(18, -78, 1),
	FTKEY_EVENT_STICK(60, -68, 1),
	FTKEY_EVENT_STICK(20, -73, 1),
	FTKEY_EVENT_STICK(1, 1, 2),
	FTKEY_EVENT_STICK(1, 0, 1),
	FTKEY_EVENT_STICK(0, 0, 1),
	FTKEY_EVENT_STICK(2, 0, 14),
	FTKEY_EVENT_STICK(2, -1, 5),
	FTKEY_EVENT_STICK(2, -2, 1),
	FTKEY_EVENT_STICK(2, -78, 1),
	FTKEY_EVENT_STICK(2, -I_CONTROLLER_RANGE_MAX, 9),
	FTKEY_EVENT_BUTTON(B_BUTTON, 1),
	FTKEY_EVENT_BUTTON(0, 1),
	FTKEY_EVENT_STICK(2, -2, 1),
	FTKEY_EVENT_STICK(2, 0, 1),
	FTKEY_EVENT_STICK(0, -2, 1),
	FTKEY_EVENT_STICK(0, -1, 3),
	FTKEY_EVENT_STICK(0, -2, 1),
	FTKEY_EVENT_STICK(1, -2, 7),
	FTKEY_EVENT_STICK(1, -1, 7),
	FTKEY_EVENT_STICK(1, 1, 61),
	FTKEY_EVENT_STICK(3, 1, 31),
	FTKEY_EVENT_STICK(2, 1, 1),
	FTKEY_EVENT_STICK(3, 1, 4),
	FTKEY_EVENT_STICK(0, -1, 2),
	FTKEY_EVENT_STICK(2, 1, 1),
	FTKEY_EVENT_STICK(3, 1, 1),
	FTKEY_EVENT_STICK(2, 1, 3),
	FTKEY_EVENT_STICK(1, 1, 1),
	FTKEY_EVENT_STICK(0, 1, 1),
	FTKEY_EVENT_STICK(-1, 1, 5),
	FTKEY_EVENT_STICK(-2, 1, 2),
	FTKEY_EVENT_STICK(-1, 1, 7),
	FTKEY_EVENT_STICK(-2, 1, 1),
	FTKEY_EVENT_STICK(-4, 1, 1),
	FTKEY_EVENT_STICK(-12, 1, 1),
	FTKEY_EVENT_STICK(-18, 1, 1),
	FTKEY_EVENT_STICK(-18, 0, 4),
	FTKEY_EVENT_STICK(-15, 0, 1),
	FTKEY_EVENT_STICK(0, 0, 1),
	FTKEY_EVENT_STICK(2, 0, 1),
	FTKEY_EVENT_STICK(32, 0, 3),
	FTKEY_EVENT_STICK(10, 0, 1),
	FTKEY_EVENT_STICK(3, 0, 23),
	FTKEY_EVENT_BUTTON(Z_TRIG, 174),
	FTKEY_EVENT_STICK(1, 0, 1),
	FTKEY_EVENT_STICK(3, -1, 4),
	FTKEY_EVENT_STICK(1, -1, 4),
	FTKEY_EVENT_STICK(69, -13, 9),
	FTKEY_EVENT_STICK(3, -1, 0),
	FTKEY_EVENT_BUTTON(0, 35),
	FTKEY_EVENT_STICK(1, -1, 0),
	FTKEY_EVENT_BUTTON(Z_TRIG, 1),
	FTKEY_EVENT_STICK(-76, 1, 8),
	FTKEY_EVENT_STICK(-76, 2, 1),
	FTKEY_EVENT_STICK(-25, 3, 1),
	FTKEY_EVENT_STICK(0, 0, 0),
	FTKEY_EVENT_BUTTON(0, 20),
	FTKEY_EVENT_STICK(3, 0, 2),
	FTKEY_EVENT_STICK(2, -1, 7),
	FTKEY_EVENT_STICK(3, 0, 2),
	FTKEY_EVENT_STICK(3, -1, 0),
	FTKEY_EVENT_BUTTON(Z_TRIG, 1),
	FTKEY_EVENT_STICK(74, 2, 1),
	FTKEY_EVENT_STICK(70, 1, 1),
	FTKEY_EVENT_STICK(2, -2, 0),
	FTKEY_EVENT_BUTTON(0, 12),
	FTKEY_EVENT_STICK(0, -2, 17),
	FTKEY_EVENT_STICK(2, -2, 2),
	FTKEY_EVENT_STICK(0, -2, 3),
	FTKEY_EVENT_STICK(-1, -2, 1),
	FTKEY_EVENT_STICK(-48, -3, 3),
	FTKEY_EVENT_STICK(-53, -3, 7),
	FTKEY_EVENT_STICK(2, -1, 2),
	FTKEY_EVENT_STICK(-75, -9, 0),
	FTKEY_EVENT_BUTTON(Z_TRIG, 1),
	FTKEY_EVENT_STICK(2, 0, 1),
	FTKEY_EVENT_STICK(-75, -7, 9),
	FTKEY_EVENT_STICK(2, -1, 0),
	FTKEY_EVENT_BUTTON(0, 5),
	FTKEY_EVENT_STICK(0, -1, 6),
	FTKEY_EVENT_STICK(2, -1, 1),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(1, -2, 1),
	FTKEY_EVENT_STICK(2, -2, 9),
	FTKEY_EVENT_STICK(2, -1, 1),
	FTKEY_EVENT_STICK(3, 1, 3),
	FTKEY_EVENT_STICK(2, 1, 0),
	FTKEY_EVENT_BUTTON(Z_TRIG, 1),
	FTKEY_EVENT_BUTTON(A_BUTTON | Z_TRIG, 1),
	FTKEY_EVENT_BUTTON(0, 6),
	FTKEY_EVENT_BUTTON(Z_TRIG, 2),
	FTKEY_EVENT_BUTTON(0, 10),
	FTKEY_EVENT_BUTTON(A_BUTTON | Z_TRIG, 4),
	FTKEY_EVENT_BUTTON(0, 2),
	FTKEY_EVENT_STICK(0, 1, 18),
	FTKEY_EVENT_STICK(0, 0, 56),
	FTKEY_EVENT_STICK(0, -1, 2),
	FTKEY_EVENT_STICK(1, -1, 7),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(1, -1, 2),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(2, -1, 2),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(2, -1, 3),
	FTKEY_EVENT_STICK(1, -1, 1),
	FTKEY_EVENT_STICK(2, -1, 1),
	FTKEY_EVENT_STICK(0, -1, 64),
	FTKEY_EVENT_STICK(2, -1, 2),
	FTKEY_EVENT_STICK(2, 0, 26),
	FTKEY_EVENT_STICK(-66, 56, 4),
	FTKEY_EVENT_STICK(-69, 37, 1),
	FTKEY_EVENT_STICK(-47, -7, 1),
	FTKEY_EVENT_STICK(3, -2, 25),
	FTKEY_EVENT_STICK(-44, 40, 1),
	FTKEY_EVENT_STICK(-64, 65, 2),
	FTKEY_EVENT_STICK(48, 0, 1),
	FTKEY_EVENT_STICK(0, 0, 1),
	FTKEY_EVENT_STICK(1, 0, 3),
	FTKEY_EVENT_STICK(2, 0, 1),
	FTKEY_EVENT_STICK(3, 0, 1),
	FTKEY_EVENT_STICK(2, 0, 3),
	FTKEY_EVENT_STICK(3, 0, 1),
	FTKEY_EVENT_STICK(0, 0, 1),
	FTKEY_EVENT_STICK(3, 0, 1),
	FTKEY_EVENT_STICK(2, 0, 1),
	FTKEY_EVENT_STICK(1, 0, 1),
	FTKEY_EVENT_STICK(3, 0, 1),
	FTKEY_EVENT_STICK(3, -81, 2),
	FTKEY_EVENT_STICK(3, -77, 1),
	FTKEY_EVENT_STICK(7, -14, 1),
	FTKEY_EVENT_STICK(8, -8, 1),
	FTKEY_EVENT_STICK(3, -2, 2),
	FTKEY_EVENT_STICK(6, -82, 1),
	FTKEY_EVENT_STICK(6, -79, 1),
	FTKEY_EVENT_STICK(2, -I_CONTROLLER_RANGE_MAX, 1),
	FTKEY_EVENT_STICK(2, -76, 1),
	FTKEY_EVENT_STICK(2, 1, 2),
	FTKEY_EVENT_STICK(0, 0, 1),
	FTKEY_EVENT_STICK(69, -7, 2),
	FTKEY_EVENT_STICK(1, -79, 1),
	FTKEY_EVENT_STICK(1, 1, 7),
	FTKEY_EVENT_BUTTON(B_BUTTON, 2),
	FTKEY_EVENT_BUTTON(0, 53),
	FTKEY_EVENT_BUTTON(A_BUTTON, 3),
	FTKEY_EVENT_BUTTON(0, 21),
	FTKEY_EVENT_STICK(59, 66, 5),
	FTKEY_EVENT_STICK(61, 61, 1),
	FTKEY_EVENT_STICK(62, 42, 1),
	FTKEY_EVENT_STICK(64, 27, 1),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(4, -1, 1),
	FTKEY_EVENT_STICK(3, -1, 20),
	FTKEY_EVENT_STICK(37, 0, 1),
	FTKEY_EVENT_STICK(70, 0, 6),
	FTKEY_EVENT_STICK(1, -1, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 13),
	FTKEY_EVENT_STICK(-75, -4, 13),
	FTKEY_EVENT_STICK(42, -1, 1),
	FTKEY_EVENT_STICK(16, -1, 1),
	FTKEY_EVENT_STICK(34, -1, 1),
	FTKEY_EVENT_STICK(33, -1, 1),
	FTKEY_EVENT_STICK(4, -1, 1),
	FTKEY_EVENT_STICK(22, -1, 1),
	FTKEY_EVENT_STICK(29, -1, 5),
	FTKEY_EVENT_STICK(1, -1, 9),
	FTKEY_EVENT_STICK(0, -1, 65),
	FTKEY_EVENT_BUTTON(0, 17),
	FTKEY_EVENT_STICK(1, -1, 13),
	FTKEY_EVENT_STICK(2, -1, 7),
	FTKEY_EVENT_STICK(3, -2, 1),
	FTKEY_EVENT_STICK(3, -1, 40),
	FTKEY_EVENT_STICK(71, -4, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON | Z_TRIG, 3),
	FTKEY_EVENT_STICK(3, -1, 0),
	FTKEY_EVENT_BUTTON(0, 27),
	FTKEY_EVENT_STICK(2, 1, 49),
	FTKEY_EVENT_STICK(27, 1, 1),
	FTKEY_EVENT_STICK(33, 1, 1),
	FTKEY_EVENT_STICK(41, 1, 1),
	FTKEY_EVENT_STICK(48, 1, 10),
	FTKEY_EVENT_STICK(68, 1, 3),
	FTKEY_EVENT_STICK(1, 1, 5),
	FTKEY_EVENT_BUTTON(A_BUTTON, 2),
	FTKEY_EVENT_BUTTON(0, 5),
	FTKEY_EVENT_STICK(0, 1, 1),
	FTKEY_EVENT_STICK(1, 1, 1),
	FTKEY_EVENT_STICK(2, 1, 29),
	FTKEY_EVENT_STICK(1, 1, 3),
	FTKEY_EVENT_STICK(72, -10, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON | Z_TRIG, 1),
	FTKEY_EVENT_STICK(3, -1, 0),
	FTKEY_EVENT_BUTTON(0, 36),
	FTKEY_EVENT_STICK(75, -5, 5),
	FTKEY_EVENT_STICK(74, -5, 3),
	FTKEY_EVENT_STICK(72, -5, 1),
	FTKEY_EVENT_STICK(72, -4, 4),
	FTKEY_EVENT_STICK(71, -3, 1),
	FTKEY_EVENT_STICK(1, 0, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 2),
	FTKEY_EVENT_STICK(3, 0, 0),
	FTKEY_EVENT_BUTTON(0, 1),
	FTKEY_EVENT_STICK(1, 0, 1),
	FTKEY_EVENT_STICK(0, -2, 1),
	FTKEY_EVENT_STICK(2, -1, 1),
	FTKEY_EVENT_STICK(0, 1, 20),
	FTKEY_EVENT_STICK(1, 1, 8),
	FTKEY_EVENT_STICK(0, 1, 7),
	FTKEY_EVENT_STICK(-63, 63, 7),
	FTKEY_EVENT_STICK(-64, 63, 3),
	FTKEY_EVENT_STICK(-65, 63, 1),
	FTKEY_EVENT_STICK(0, -1, 18),
	FTKEY_EVENT_STICK(1, -1, 1),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(1, -1, 1),
	FTKEY_EVENT_STICK(1, 1, 1),
	FTKEY_EVENT_STICK(1, 2, 4),
	FTKEY_EVENT_STICK(3, 1, 3),
	FTKEY_EVENT_BUTTON(B_BUTTON, 2),
	FTKEY_EVENT_BUTTON(0, 1),
	FTKEY_EVENT_STICK(1, 1, 1),
	FTKEY_EVENT_STICK(0, 1, 2),
	FTKEY_EVENT_STICK(3, -2, 1),
	FTKEY_EVENT_STICK(1, 2, 1),
	FTKEY_EVENT_STICK(3, 1, 24),
	FTKEY_EVENT_STICK(2, 0, 5),
	FTKEY_EVENT_STICK(0, 0, 19),
	FTKEY_EVENT_STICK(71, -14, 6),
	FTKEY_EVENT_STICK(70, -14, 1),
	FTKEY_EVENT_STICK(0, 0, 17),
	FTKEY_EVENT_STICK(1, 0, 1),
	FTKEY_EVENT_STICK(30, 0, 1),
	FTKEY_EVENT_STICK(31, 0, 5),
	FTKEY_EVENT_STICK(2, 78, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_STICK(0, 0, 0),
	FTKEY_EVENT_BUTTON(0, 63),
	FTKEY_EVENT_BUTTON(L_TRIG, 5),
	FTKEY_EVENT_BUTTON(0, 4),
	FTKEY_EVENT_BUTTON(L_TRIG, 2),
	FTKEY_EVENT_BUTTON(0, 173),
	FTKEY_EVENT_END(),
};

/* relocData/252_SCExplainMain.c:1251-2443 dSCExplainMain_1_KeyEvent,
 * REGION_US arm, verbatim, same shape as dSCExplainKeyEvent0 above --
 * Luigi's canned script (1300 halfwords). Player slots 2/3
 * (dSCExplainMain_2_KeyEvent/_3_KeyEvent, both a bare FTKEY_EVENT_END())
 * are not carried: scExplainFuncStart's own player loop below only
 * calls ftParamSetKey for a slot whose pkind is not nFTPlayerKindNot,
 * and scExplainSetBattleState sets only players 0 and 1 -- slots 2/3
 * are never read. */
const FTKeyEvent dSCExplainKeyEvent1[1300] = {
	FTKEY_EVENT_STICK(0, 0, 0),
	FTKEY_EVENT_STICK(-1, 0, 130),
	FTKEY_EVENT_STICK(-38, -1, 1),
	FTKEY_EVENT_STICK(-60, -3, 1),
	FTKEY_EVENT_STICK(-3, 0, 3),
	FTKEY_EVENT_STICK(-50, 2, 1),
	FTKEY_EVENT_STICK(-51, 1, 1),
	FTKEY_EVENT_STICK(-39, 1, 1),
	FTKEY_EVENT_STICK(-2, 0, 14),
	FTKEY_EVENT_STICK(-36, 0, 4),
	FTKEY_EVENT_STICK(-41, 0, 1),
	FTKEY_EVENT_STICK(-52, 0, 1),
	FTKEY_EVENT_STICK(-53, 0, 2),
	FTKEY_EVENT_STICK(-73, 0, 1),
	FTKEY_EVENT_STICK(-75, 0, 93),
	FTKEY_EVENT_STICK(77, -1, 1),
	FTKEY_EVENT_STICK(77, 0, 40),
	FTKEY_EVENT_STICK(0, 0, 17),
	FTKEY_EVENT_STICK(-1, 0, 19),
	FTKEY_EVENT_STICK(-8, -2, 1),
	FTKEY_EVENT_STICK(-18, -3, 1),
	FTKEY_EVENT_STICK(-22, -2, 1),
	FTKEY_EVENT_STICK(-23, -2, 1),
	FTKEY_EVENT_STICK(-24, -2, 2),
	FTKEY_EVENT_STICK(-5, -2, 1),
	FTKEY_EVENT_STICK(-2, 0, 65),
	FTKEY_EVENT_STICK(2, -81, 1),
	FTKEY_EVENT_STICK(0, 0, 20),
	FTKEY_EVENT_STICK(0, 79, 2),
	FTKEY_EVENT_STICK(4, 78, 4),
	FTKEY_EVENT_STICK(3, 78, 1),
	FTKEY_EVENT_STICK(2, 69, 1),
	FTKEY_EVENT_STICK(-1, 0, 53),
	FTKEY_EVENT_STICK(2, -I_CONTROLLER_RANGE_MAX, 1),
	FTKEY_EVENT_STICK(0, -2, 44),
	FTKEY_EVENT_STICK(63, 63, 4),
	FTKEY_EVENT_STICK(-I_CONTROLLER_RANGE_MAX, -2, 5),
	FTKEY_EVENT_STICK(-81, -2, 5),
	FTKEY_EVENT_STICK(-1, -1, 10),
	FTKEY_EVENT_STICK(-2, -1, 3),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(-2, -1, 21),
	FTKEY_EVENT_STICK(-1, -2, 2),
	FTKEY_EVENT_STICK(-66, 69, 2),
	FTKEY_EVENT_STICK(-65, 68, 1),
	FTKEY_EVENT_STICK(-2, 0, 9),
	FTKEY_EVENT_STICK(75, 1, 12),
	FTKEY_EVENT_STICK(-2, -1, 1),
	FTKEY_EVENT_STICK(-2, -2, 4),
	FTKEY_EVENT_STICK(-2, -1, 4),
	FTKEY_EVENT_STICK(-1, 0, 26),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(-1, 0, 1),
	FTKEY_EVENT_STICK(-1, -12, 1),
	FTKEY_EVENT_STICK(-24, -81, 2),
	FTKEY_EVENT_STICK(0, -27, 1),
	FTKEY_EVENT_STICK(0, -2, 64),
	FTKEY_EVENT_STICK(-1, -2, 3),
	FTKEY_EVENT_STICK(-2, -2, 3),
	FTKEY_EVENT_STICK(-1, -2, 3),
	FTKEY_EVENT_STICK(-2, -2, 1),
	FTKEY_EVENT_STICK(-1, -2, 1),
	FTKEY_EVENT_STICK(-2, -2, 5),
	FTKEY_EVENT_STICK(-81, -7, 1),
	FTKEY_EVENT_STICK(-79, -6, 1),
	FTKEY_EVENT_STICK(-2, 0, 10),
	FTKEY_EVENT_STICK(-77, 13, 1),
	FTKEY_EVENT_STICK(-77, 9, 1),
	FTKEY_EVENT_STICK(-2, 0, 7),
	FTKEY_EVENT_BUTTON(A_BUTTON, 3),
	FTKEY_EVENT_BUTTON(0, 6),
	FTKEY_EVENT_STICK(-4, -1, 1),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(0, -2, 2),
	FTKEY_EVENT_STICK(-72, 17, 2),
	FTKEY_EVENT_STICK(0, -2, 5),
	FTKEY_EVENT_STICK(40, 0, 1),
	FTKEY_EVENT_STICK(1, 0, 1),
	FTKEY_EVENT_STICK(0, 0, 20),
	FTKEY_EVENT_STICK(0, -1, 3),
	FTKEY_EVENT_STICK(0, 0, 5),
	FTKEY_EVENT_STICK(-74, 22, 1),
	FTKEY_EVENT_STICK(-1, -1, 26),
	FTKEY_EVENT_STICK(-19, -1, 1),
	FTKEY_EVENT_STICK(-26, -1, 1),
	FTKEY_EVENT_STICK(-35, -1, 1),
	FTKEY_EVENT_STICK(-39, -2, 3),
	FTKEY_EVENT_STICK(-40, -2, 2),
	FTKEY_EVENT_STICK(-41, -2, 4),
	FTKEY_EVENT_STICK(-2, 0, 18),
	FTKEY_EVENT_STICK(-37, -3, 6),
	FTKEY_EVENT_STICK(0, 0, 3),
	FTKEY_EVENT_STICK(-46, -5, 1),
	FTKEY_EVENT_STICK(-51, -5, 1),
	FTKEY_EVENT_STICK(-52, -5, 1),
	FTKEY_EVENT_STICK(-53, -5, 4),
	FTKEY_EVENT_STICK(-54, -5, 1),
	FTKEY_EVENT_STICK(-55, -5, 4),
	FTKEY_EVENT_STICK(-2, -1, 22),
	FTKEY_EVENT_STICK(-1, -1, 77),
	FTKEY_EVENT_STICK(-76, -5, 1),
	FTKEY_EVENT_STICK(-1, -2, 11),
	FTKEY_EVENT_STICK(-1, 0, 1),
	FTKEY_EVENT_STICK(-1, -2, 9),
	FTKEY_EVENT_STICK(-I_CONTROLLER_RANGE_MAX, -4, 2),
	FTKEY_EVENT_STICK(-79, -4, 3),
	FTKEY_EVENT_STICK(-79, -3, 1),
	FTKEY_EVENT_STICK(-79, -4, 6),
	FTKEY_EVENT_STICK(-79, 4, 1),
	FTKEY_EVENT_STICK(-79, 2, 1),
	FTKEY_EVENT_STICK(-79, 5, 8),
	FTKEY_EVENT_STICK(-79, 4, 5),
	FTKEY_EVENT_STICK(-79, 5, 4),
	FTKEY_EVENT_STICK(-29, 7, 1),
	FTKEY_EVENT_STICK(-72, 18, 1),
	FTKEY_EVENT_STICK(-72, 19, 7),
	FTKEY_EVENT_STICK(-72, 22, 1),
	FTKEY_EVENT_STICK(-72, 23, 3),
	FTKEY_EVENT_STICK(-71, 23, 1),
	FTKEY_EVENT_STICK(-71, 22, 1),
	FTKEY_EVENT_STICK(-72, 22, 4),
	FTKEY_EVENT_STICK(-71, 22, 2),
	FTKEY_EVENT_STICK(-72, 22, 1),
	FTKEY_EVENT_STICK(-71, 22, 1),
	FTKEY_EVENT_STICK(-72, 22, 7),
	FTKEY_EVENT_STICK(-71, 22, 1),
	FTKEY_EVENT_STICK(-72, 22, 2),
	FTKEY_EVENT_STICK(-34, 12, 1),
	FTKEY_EVENT_STICK(-2, 0, 31),
	FTKEY_EVENT_STICK(-11, 0, 1),
	FTKEY_EVENT_STICK(-18, 0, 4),
	FTKEY_EVENT_STICK(-39, 0, 1),
	FTKEY_EVENT_STICK(-78, 3, 2),
	FTKEY_EVENT_STICK(1, 0, 58),
	FTKEY_EVENT_STICK(-3, -86, 1),
	FTKEY_EVENT_STICK(-2, -1, 1),
	FTKEY_EVENT_STICK(-2, -2, 13),
	FTKEY_EVENT_STICK(-9, -85, 2),
	FTKEY_EVENT_STICK(1, -2, 1),
	FTKEY_EVENT_STICK(-35, -I_CONTROLLER_RANGE_MAX, 1),
	FTKEY_EVENT_STICK(-34, -I_CONTROLLER_RANGE_MAX, 1),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-11, -84, 1),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(-2, -74, 1),
	FTKEY_EVENT_STICK(-19, -37, 1),
	FTKEY_EVENT_STICK(-40, -73, 1),
	FTKEY_EVENT_STICK(-41, -61, 1),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(-2, -2, 1),
	FTKEY_EVENT_STICK(-2, -86, 1),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(-1, -43, 1),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(-1, -84, 1),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-1, -85, 1),
	FTKEY_EVENT_STICK(-1, 0, 1),
	FTKEY_EVENT_STICK(-77, 0, 1),
	FTKEY_EVENT_STICK(-78, 0, 1),
	FTKEY_EVENT_STICK(-78, 3, 2),
	FTKEY_EVENT_STICK(-78, 4, 1),
	FTKEY_EVENT_STICK(-2, -85, 1),
	FTKEY_EVENT_STICK(0, -2, 1),
	FTKEY_EVENT_STICK(-4, -84, 1),
	FTKEY_EVENT_STICK(0, -2, 5),
	FTKEY_EVENT_STICK(-1, -2, 6),
	FTKEY_EVENT_STICK(-2, -2, 20),
	FTKEY_EVENT_STICK(-74, 10, 1),
	FTKEY_EVENT_STICK(-75, 10, 3),
	FTKEY_EVENT_STICK(-76, 10, 1),
	FTKEY_EVENT_STICK(-77, 10, 4),
	FTKEY_EVENT_STICK(-75, 10, 1),
	FTKEY_EVENT_STICK(-1, -1, 49),
	FTKEY_EVENT_STICK(26, 5, 1),
	FTKEY_EVENT_STICK(76, 7, 1),
	FTKEY_EVENT_STICK(76, 17, 1),
	FTKEY_EVENT_STICK(76, 16, 4),
	FTKEY_EVENT_STICK(76, 15, 2),
	FTKEY_EVENT_STICK(76, 14, 2),
	FTKEY_EVENT_STICK(76, 15, 30),
	FTKEY_EVENT_STICK(75, 15, 1),
	FTKEY_EVENT_STICK(74, 15, 4),
	FTKEY_EVENT_STICK(73, 14, 2),
	FTKEY_EVENT_STICK(73, 13, 4),
	FTKEY_EVENT_STICK(74, 13, 12),
	FTKEY_EVENT_STICK(65, 63, 2),
	FTKEY_EVENT_STICK(65, 45, 1),
	FTKEY_EVENT_STICK(74, 4, 1),
	FTKEY_EVENT_STICK(74, 3, 2),
	FTKEY_EVENT_STICK(75, 3, 5),
	FTKEY_EVENT_STICK(74, 2, 1),
	FTKEY_EVENT_STICK(69, -56, 1),
	FTKEY_EVENT_STICK(68, -66, 1),
	FTKEY_EVENT_STICK(68, -55, 1),
	FTKEY_EVENT_STICK(75, -3, 4),
	FTKEY_EVENT_STICK(68, -62, 1),
	FTKEY_EVENT_STICK(68, -69, 1),
	FTKEY_EVENT_STICK(67, -52, 1),
	FTKEY_EVENT_STICK(72, -17, 1),
	FTKEY_EVENT_STICK(73, -14, 1),
	FTKEY_EVENT_STICK(73, -13, 2),
	FTKEY_EVENT_STICK(77, -6, 23),
	FTKEY_EVENT_STICK(77, -8, 1),
	FTKEY_EVENT_STICK(68, -69, 3),
	FTKEY_EVENT_STICK(69, -32, 1),
	FTKEY_EVENT_STICK(68, -69, 11),
	FTKEY_EVENT_STICK(71, -26, 1),
	FTKEY_EVENT_STICK(75, -13, 1),
	FTKEY_EVENT_STICK(77, -3, 4),
	FTKEY_EVENT_STICK(77, -2, 2),
	FTKEY_EVENT_STICK(-2, -1, 1),
	FTKEY_EVENT_STICK(76, -2, 1),
	FTKEY_EVENT_STICK(75, -2, 7),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(2, -1, 3),
	FTKEY_EVENT_STICK(76, -3, 1),
	FTKEY_EVENT_STICK(77, -3, 9),
	FTKEY_EVENT_STICK(75, -3, 4),
	FTKEY_EVENT_STICK(-2, 0, 2),
	FTKEY_EVENT_STICK(71, 22, 1),
	FTKEY_EVENT_STICK(73, 34, 2),
	FTKEY_EVENT_STICK(73, 33, 3),
	FTKEY_EVENT_STICK(73, 32, 1),
	FTKEY_EVENT_STICK(73, 30, 1),
	FTKEY_EVENT_STICK(73, 27, 2),
	FTKEY_EVENT_STICK(73, 26, 1),
	FTKEY_EVENT_STICK(73, 25, 1),
	FTKEY_EVENT_STICK(73, 22, 7),
	FTKEY_EVENT_STICK(72, 25, 1),
	FTKEY_EVENT_STICK(72, 23, 1),
	FTKEY_EVENT_STICK(68, 45, 1),
	FTKEY_EVENT_STICK(-2, 0, 12),
	FTKEY_EVENT_STICK(78, 0, 31),
	FTKEY_EVENT_STICK(78, -4, 1),
	FTKEY_EVENT_STICK(78, -5, 1),
	FTKEY_EVENT_STICK(78, -4, 1),
	FTKEY_EVENT_STICK(78, -5, 4),
	FTKEY_EVENT_STICK(78, -4, 1),
	FTKEY_EVENT_STICK(78, -5, 4),
	FTKEY_EVENT_STICK(78, -4, 2),
	FTKEY_EVENT_STICK(75, 3, 1),
	FTKEY_EVENT_STICK(75, 2, 4),
	FTKEY_EVENT_STICK(76, 2, 4),
	FTKEY_EVENT_STICK(78, 1, 7),
	FTKEY_EVENT_STICK(75, 8, 7),
	FTKEY_EVENT_STICK(72, -71, 1),
	FTKEY_EVENT_STICK(74, 15, 2),
	FTKEY_EVENT_STICK(74, 18, 1),
	FTKEY_EVENT_STICK(74, 22, 1),
	FTKEY_EVENT_STICK(63, 22, 1),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(-2, -1, 2),
	FTKEY_EVENT_STICK(76, 13, 1),
	FTKEY_EVENT_STICK(76, 11, 1),
	FTKEY_EVENT_STICK(76, 10, 1),
	FTKEY_EVENT_STICK(76, 8, 1),
	FTKEY_EVENT_STICK(76, 10, 1),
	FTKEY_EVENT_STICK(75, 10, 4),
	FTKEY_EVENT_STICK(-2, -2, 1),
	FTKEY_EVENT_STICK(76, 4, 1),
	FTKEY_EVENT_STICK(76, 5, 1),
	FTKEY_EVENT_STICK(77, 5, 3),
	FTKEY_EVENT_STICK(77, 4, 1),
	FTKEY_EVENT_STICK(77, 5, 2),
	FTKEY_EVENT_STICK(76, 5, 4),
	FTKEY_EVENT_STICK(76, 4, 4),
	FTKEY_EVENT_STICK(76, 3, 1),
	FTKEY_EVENT_STICK(-1, 1, 1),
	FTKEY_EVENT_STICK(-1, 0, 4),
	FTKEY_EVENT_STICK(-1, 1, 17),
	FTKEY_EVENT_STICK(-2, -2, 25),
	FTKEY_EVENT_STICK(21, -75, 1),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-2, -1, 6),
	FTKEY_EVENT_STICK(23, -77, 1),
	FTKEY_EVENT_STICK(-1, 0, 1),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-3, -83, 3),
	FTKEY_EVENT_STICK(-1, -2, 4),
	FTKEY_EVENT_STICK(-1, -1, 63),
	FTKEY_EVENT_STICK(-1, 0, 26),
	FTKEY_EVENT_STICK(1, -83, 4),
	FTKEY_EVENT_STICK(-2, -1, 1),
	FTKEY_EVENT_STICK(-27, -82, 1),
	FTKEY_EVENT_STICK(-18, -82, 1),
	FTKEY_EVENT_STICK(0, 0, 1),
	FTKEY_EVENT_STICK(-1, -2, 32),
	FTKEY_EVENT_STICK(-1, -1, 2),
	FTKEY_EVENT_STICK(-2, -1, 1),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(-2, -1, 72),
	FTKEY_EVENT_STICK(10, -81, 1),
	FTKEY_EVENT_STICK(0, -2, 1),
	FTKEY_EVENT_STICK(-1, -2, 16),
	FTKEY_EVENT_STICK(-79, -3, 1),
	FTKEY_EVENT_STICK(-78, -3, 1),
	FTKEY_EVENT_STICK(0, -1, 7),
	FTKEY_EVENT_STICK(-1, 0, 3),
	FTKEY_EVENT_STICK(-1, 1, 1),
	FTKEY_EVENT_STICK(6, 77, 1),
	FTKEY_EVENT_STICK(-1, 0, 91),
	FTKEY_EVENT_STICK(-2, 0, 14),
	FTKEY_EVENT_STICK(0, -1, 2),
	FTKEY_EVENT_STICK(-1, 0, 28),
	FTKEY_EVENT_STICK(-8, 0, 1),
	FTKEY_EVENT_STICK(-25, 0, 1),
	FTKEY_EVENT_STICK(-27, 0, 1),
	FTKEY_EVENT_STICK(-34, 0, 1),
	FTKEY_EVENT_STICK(-25, -1, 1),
	FTKEY_EVENT_STICK(-2, 0, 24),
	FTKEY_EVENT_STICK(-2, -1, 1),
	FTKEY_EVENT_STICK(-2, 0, 33),
	FTKEY_EVENT_STICK(-2, -7, 1),
	FTKEY_EVENT_STICK(-2, -1, 13),
	FTKEY_EVENT_STICK(5, -82, 2),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-15, -78, 1),
	FTKEY_EVENT_STICK(-3, -81, 1),
	FTKEY_EVENT_STICK(-2, -2, 1),
	FTKEY_EVENT_STICK(-18, -83, 1),
	FTKEY_EVENT_STICK(1, -1, 1),
	FTKEY_EVENT_STICK(1, -2, 3),
	FTKEY_EVENT_STICK(0, -2, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_BUTTON(0, 3),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(0, -2, 4),
	FTKEY_EVENT_STICK(0, -1, 2),
	FTKEY_EVENT_STICK(0, -2, 10),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(0, -2, 2),
	FTKEY_EVENT_STICK(-35, -2, 1),
	FTKEY_EVENT_STICK(0, 0, 4),
	FTKEY_EVENT_STICK(-79, 5, 1),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-81, -8, 1),
	FTKEY_EVENT_STICK(-2, 0, 3),
	FTKEY_EVENT_STICK(-2, 79, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_STICK(-2, 78, 0),
	FTKEY_EVENT_BUTTON(0, 2),
	FTKEY_EVENT_STICK(-1, -1, 12),
	FTKEY_EVENT_STICK(-2, -1, 1),
	FTKEY_EVENT_STICK(-1, 0, 2),
	FTKEY_EVENT_STICK(-2, 0, 52),
	FTKEY_EVENT_STICK(-57, -1, 1),
	FTKEY_EVENT_STICK(-82, -2, 1),
	FTKEY_EVENT_STICK(-81, -2, 1),
	FTKEY_EVENT_STICK(-I_CONTROLLER_RANGE_MAX, -2, 6),
	FTKEY_EVENT_STICK(-69, -2, 1),
	FTKEY_EVENT_STICK(-2, -1, 4),
	FTKEY_EVENT_STICK(-1, -1, 18),
	FTKEY_EVENT_STICK(-1, 0, 3),
	FTKEY_EVENT_STICK(0, 0, 1),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(0, 1, 1),
	FTKEY_EVENT_STICK(77, -5, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_STICK(-2, 0, 0),
	FTKEY_EVENT_BUTTON(0, 42),
	FTKEY_EVENT_STICK(0, 0, 43),
	FTKEY_EVENT_STICK(-1, 0, 96),
	FTKEY_EVENT_BUTTON(L_TRIG, 3),
	FTKEY_EVENT_BUTTON(0, 1),
	FTKEY_EVENT_BUTTON(L_TRIG, 4),
	FTKEY_EVENT_STICK(0, 0, 0),
	FTKEY_EVENT_BUTTON(0, 20),
	FTKEY_EVENT_STICK(-1, 0, 9),
	FTKEY_EVENT_STICK(-1, 9, 1),
	FTKEY_EVENT_STICK(14, 75, 4),
	FTKEY_EVENT_STICK(-1, -2, 40),
	FTKEY_EVENT_STICK(-2, -1, 0),
	FTKEY_EVENT_BUTTON(B_BUTTON, 2),
	FTKEY_EVENT_BUTTON(0, 36),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(-2, -1, 1),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(-1, 0, 1),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(-1, 0, 4),
	FTKEY_EVENT_STICK(75, -6, 24),
	FTKEY_EVENT_STICK(77, -5, 2),
	FTKEY_EVENT_STICK(75, -2, 1),
	FTKEY_EVENT_STICK(75, 1, 3),
	FTKEY_EVENT_STICK(74, 1, 1),
	FTKEY_EVENT_STICK(-2, -1, 292),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_BUTTON(0, 42),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_BUTTON(0, 11),
	FTKEY_EVENT_BUTTON(A_BUTTON, 2),
	FTKEY_EVENT_BUTTON(0, 15),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_BUTTON(0, 30),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_BUTTON(0, 7),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_BUTTON(0, 1),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_BUTTON(0, 29),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_BUTTON(0, 22),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-28, -2, 3),
	FTKEY_EVENT_STICK(-27, -1, 1),
	FTKEY_EVENT_STICK(0, 1, 3),
	FTKEY_EVENT_STICK(-29, -1, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_STICK(-2, 0, 0),
	FTKEY_EVENT_BUTTON(0, 27),
	FTKEY_EVENT_STICK(3, 7, 1),
	FTKEY_EVENT_STICK(1, 1, 1),
	FTKEY_EVENT_STICK(0, 1, 13),
	FTKEY_EVENT_STICK(78, 0, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_STICK(0, 0, 0),
	FTKEY_EVENT_BUTTON(0, 3),
	FTKEY_EVENT_STICK(-1, 0, 39),
	FTKEY_EVENT_STICK(-78, -1, 0),
	FTKEY_EVENT_BUTTON(B_BUTTON, 1),
	FTKEY_EVENT_STICK(-2, -1, 0),
	FTKEY_EVENT_BUTTON(0, 34),
	FTKEY_EVENT_STICK(28, 0, 14),
	FTKEY_EVENT_STICK(37, 0, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON, 2),
	FTKEY_EVENT_STICK(-2, 0, 0),
	FTKEY_EVENT_BUTTON(0, 27),
	FTKEY_EVENT_STICK(-1, 0, 8),
	FTKEY_EVENT_STICK(-2, 0, 3),
	FTKEY_EVENT_STICK(-1, 0, 2),
	FTKEY_EVENT_STICK(-79, 0, 8),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-2, -1, 7),
	FTKEY_EVENT_STICK(75, -1, 2),
	FTKEY_EVENT_STICK(-2, 0, 5),
	FTKEY_EVENT_STICK(75, 1, 1),
	FTKEY_EVENT_STICK(-2, 0, 42),
	FTKEY_EVENT_STICK(-1, 0, 1),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-1, 0, 1),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-1, 0, 50),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-82, -2, 50),
	FTKEY_EVENT_STICK(-72, 69, 1),
	FTKEY_EVENT_STICK(-72, 68, 1),
	FTKEY_EVENT_STICK(-81, -17, 1),
	FTKEY_EVENT_STICK(-81, -14, 1),
	FTKEY_EVENT_STICK(-81, -11, 5),
	FTKEY_EVENT_STICK(-2, -1, 28),
	FTKEY_EVENT_STICK(-63, -14, 1),
	FTKEY_EVENT_STICK(-62, -16, 1),
	FTKEY_EVENT_STICK(-61, -18, 1),
	FTKEY_EVENT_STICK(-61, -19, 1),
	FTKEY_EVENT_STICK(-75, -23, 1),
	FTKEY_EVENT_STICK(-74, -22, 1),
	FTKEY_EVENT_STICK(-74, -23, 1),
	FTKEY_EVENT_STICK(-73, -23, 13),
	FTKEY_EVENT_STICK(-72, -23, 14),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-2, 1, 6),
	FTKEY_EVENT_STICK(-57, -27, 1),
	FTKEY_EVENT_STICK(-77, -24, 1),
	FTKEY_EVENT_STICK(-1, 0, 1),
	FTKEY_EVENT_STICK(-2, 0, 22),
	FTKEY_EVENT_STICK(-78, -2, 1),
	FTKEY_EVENT_STICK(-I_CONTROLLER_RANGE_MAX, -2, 6),
	FTKEY_EVENT_STICK(-75, -9, 1),
	FTKEY_EVENT_STICK(-77, -8, 1),
	FTKEY_EVENT_STICK(-77, -7, 5),
	FTKEY_EVENT_STICK(-I_CONTROLLER_RANGE_MAX, -7, 2),
	FTKEY_EVENT_STICK(-I_CONTROLLER_RANGE_MAX, -15, 1),
	FTKEY_EVENT_STICK(-78, -16, 1),
	FTKEY_EVENT_STICK(-79, -7, 7),
	FTKEY_EVENT_STICK(-79, -6, 1),
	FTKEY_EVENT_STICK(-78, -7, 2),
	FTKEY_EVENT_STICK(-79, -3, 2),
	FTKEY_EVENT_STICK(-75, 39, 1),
	FTKEY_EVENT_STICK(-74, 44, 1),
	FTKEY_EVENT_STICK(-72, 51, 1),
	FTKEY_EVENT_STICK(-1, 78, 2),
	FTKEY_EVENT_STICK(62, 67, 1),
	FTKEY_EVENT_STICK(-78, -2, 1),
	FTKEY_EVENT_STICK(-79, -3, 1),
	FTKEY_EVENT_STICK(-82, -3, 1),
	FTKEY_EVENT_STICK(-81, -3, 2),
	FTKEY_EVENT_STICK(-I_CONTROLLER_RANGE_MAX, -3, 5),
	FTKEY_EVENT_STICK(-I_CONTROLLER_RANGE_MAX, -2, 8),
	FTKEY_EVENT_STICK(-76, -2, 1),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(-2, -2, 1),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(-2, -1, 1),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(-2, -1, 23),
	FTKEY_EVENT_STICK(0, 1, 1),
	FTKEY_EVENT_STICK(-1, 1, 2),
	FTKEY_EVENT_STICK(-1, 78, 10),
	FTKEY_EVENT_STICK(-1, 1, 0),
	FTKEY_EVENT_BUTTON(B_BUTTON, 2),
	FTKEY_EVENT_BUTTON(0, 27),
	FTKEY_EVENT_STICK(-1, 0, 44),
	FTKEY_EVENT_STICK(0, 0, 5),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(0, 0, 3),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(0, -70, 1),
	FTKEY_EVENT_STICK(-9, -85, 1),
	FTKEY_EVENT_STICK(69, -32, 1),
	FTKEY_EVENT_STICK(70, -27, 1),
	FTKEY_EVENT_STICK(72, 24, 1),
	FTKEY_EVENT_STICK(66, 47, 1),
	FTKEY_EVENT_STICK(66, 48, 1),
	FTKEY_EVENT_STICK(66, 47, 10),
	FTKEY_EVENT_STICK(67, 44, 1),
	FTKEY_EVENT_STICK(69, 37, 2),
	FTKEY_EVENT_STICK(69, 36, 2),
	FTKEY_EVENT_STICK(69, 35, 3),
	FTKEY_EVENT_STICK(68, 35, 2),
	FTKEY_EVENT_STICK(68, 33, 2),
	FTKEY_EVENT_STICK(68, 32, 12),
	FTKEY_EVENT_STICK(68, 31, 11),
	FTKEY_EVENT_STICK(68, 30, 3),
	FTKEY_EVENT_STICK(0, -2, 6),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(-1, -11, 1),
	FTKEY_EVENT_STICK(57, -76, 1),
	FTKEY_EVENT_STICK(-30, -81, 2),
	FTKEY_EVENT_STICK(-8, -85, 31),
	FTKEY_EVENT_STICK(13, -77, 2),
	FTKEY_EVENT_STICK(16, -78, 1),
	FTKEY_EVENT_STICK(18, -78, 2),
	FTKEY_EVENT_STICK(19, -78, 4),
	FTKEY_EVENT_STICK(19, -81, 3),
	FTKEY_EVENT_STICK(19, -I_CONTROLLER_RANGE_MAX, 19),
	FTKEY_EVENT_STICK(20, -79, 4),
	FTKEY_EVENT_STICK(21, -I_CONTROLLER_RANGE_MAX, 29),
	FTKEY_EVENT_STICK(19, -79, 1),
	FTKEY_EVENT_STICK(-1, -2, 1),
	FTKEY_EVENT_STICK(-2, -1, 1),
	FTKEY_EVENT_STICK(-78, 0, 1),
	FTKEY_EVENT_STICK(-78, -1, 1),
	FTKEY_EVENT_STICK(-79, -2, 2),
	FTKEY_EVENT_STICK(-78, -2, 1),
	FTKEY_EVENT_STICK(-77, -1, 1),
	FTKEY_EVENT_STICK(-77, 12, 1),
	FTKEY_EVENT_STICK(-77, 11, 21),
	FTKEY_EVENT_STICK(-66, 66, 2),
	FTKEY_EVENT_STICK(-75, 5, 1),
	FTKEY_EVENT_STICK(-2, -1, 47),
	FTKEY_EVENT_STICK(-1, -1, 6),
	FTKEY_EVENT_STICK(-1, 0, 2),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(0, 0, 2),
	FTKEY_EVENT_STICK(-1, -2, 17),
	FTKEY_EVENT_STICK(0, 0, 4),
	FTKEY_EVENT_STICK(-2, 0, 0),
	FTKEY_EVENT_BUTTON(Z_TRIG, 16),
	FTKEY_EVENT_BUTTON(0, 11),
	FTKEY_EVENT_STICK(-3, -1, 3),
	FTKEY_EVENT_STICK(-73, -2, 2),
	FTKEY_EVENT_STICK(-2, -1, 4),
	FTKEY_EVENT_STICK(0, -2, 8),
	FTKEY_EVENT_STICK(1, -2, 1),
	FTKEY_EVENT_STICK(-2, -1, 4),
	FTKEY_EVENT_STICK(-82, -1, 0),
	FTKEY_EVENT_BUTTON(Z_TRIG, 1),
	FTKEY_EVENT_STICK(-76, 1, 1),
	FTKEY_EVENT_STICK(-76, -2, 1),
	FTKEY_EVENT_STICK(-1, -1, 0),
	FTKEY_EVENT_BUTTON(0, 1),
	FTKEY_EVENT_STICK(-2, 0, 8),
	FTKEY_EVENT_STICK(-2, -1, 1),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-2, -1, 1),
	FTKEY_EVENT_STICK(-2, 0, 3),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(0, 0, 1),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(0, 0, 5),
	FTKEY_EVENT_STICK(-2, -2, 1),
	FTKEY_EVENT_STICK(-2, -1, 2),
	FTKEY_EVENT_STICK(-2, -2, 4),
	FTKEY_EVENT_BUTTON(A_BUTTON, 1),
	FTKEY_EVENT_BUTTON(0, 19),
	FTKEY_EVENT_STICK(78, 2, 1),
	FTKEY_EVENT_STICK(79, 0, 1),
	FTKEY_EVENT_STICK(78, 0, 1),
	FTKEY_EVENT_STICK(78, 3, 1),
	FTKEY_EVENT_STICK(-1, 0, 2),
	FTKEY_EVENT_STICK(1, -1, 3),
	FTKEY_EVENT_STICK(-6, 77, 0),
	FTKEY_EVENT_BUTTON(A_BUTTON | Z_TRIG, 1),
	FTKEY_EVENT_STICK(-1, -1, 0),
	FTKEY_EVENT_BUTTON(0, 6),
	FTKEY_EVENT_STICK(0, -1, 3),
	FTKEY_EVENT_STICK(-1, -1, 22),
	FTKEY_EVENT_STICK(-1, -2, 1),
	FTKEY_EVENT_STICK(-1, 0, 16),
	FTKEY_EVENT_STICK(-I_CONTROLLER_RANGE_MAX, -6, 0),
	FTKEY_EVENT_BUTTON(Z_TRIG, 2),
	FTKEY_EVENT_STICK(-79, -6, 1),
	FTKEY_EVENT_STICK(-1, 0, 2),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-1, 0, 0),
	FTKEY_EVENT_BUTTON(0, 2),
	FTKEY_EVENT_STICK(-3, 0, 1),
	FTKEY_EVENT_STICK(-10, 0, 1),
	FTKEY_EVENT_STICK(-13, 0, 4),
	FTKEY_EVENT_STICK(-12, 0, 1),
	FTKEY_EVENT_STICK(-11, 0, 1),
	FTKEY_EVENT_STICK(-3, 0, 3),
	FTKEY_EVENT_STICK(-6, 0, 1),
	FTKEY_EVENT_STICK(-10, 0, 1),
	FTKEY_EVENT_STICK(-16, -1, 1),
	FTKEY_EVENT_STICK(-23, 0, 1),
	FTKEY_EVENT_STICK(-28, 0, 1),
	FTKEY_EVENT_STICK(-39, 0, 1),
	FTKEY_EVENT_STICK(-78, 1, 1),
	FTKEY_EVENT_STICK(-79, 0, 1),
	FTKEY_EVENT_STICK(-75, -12, 2),
	FTKEY_EVENT_STICK(-75, -13, 3),
	FTKEY_EVENT_STICK(-74, -14, 3),
	FTKEY_EVENT_STICK(-74, -15, 10),
	FTKEY_EVENT_STICK(-2, 0, 1),
	FTKEY_EVENT_STICK(-2, -1, 6),
	FTKEY_EVENT_STICK(-27, -14, 1),
	FTKEY_EVENT_STICK(-32, -14, 1),
	FTKEY_EVENT_STICK(-33, -15, 4),
	FTKEY_EVENT_STICK(0, -1, 1),
	FTKEY_EVENT_STICK(-81, -4, 1),
	FTKEY_EVENT_STICK(-82, -5, 1),
	FTKEY_EVENT_STICK(-81, -5, 2),
	FTKEY_EVENT_STICK(-71, -5, 1),
	FTKEY_EVENT_STICK(-65, -5, 1),
	FTKEY_EVENT_STICK(0, 0, 5),
	FTKEY_EVENT_STICK(-1, 0, 2),
	FTKEY_EVENT_STICK(0, 0, 65),
	FTKEY_EVENT_STICK(-2, -1, 1),
	FTKEY_EVENT_STICK(-2, -2, 1),
	FTKEY_EVENT_STICK(-1, -1, 1),
	FTKEY_EVENT_STICK(-2, -1, 166),
	FTKEY_EVENT_END(),
};


/* relocData/252_SCExplainMain.c:2455-2807 ExplainPhase[22], REGION_US
 * arm, verbatim (the JP arm's own text-sprite swap dropped, same
 * REGION_US convention as the KeyEvent scripts above) -- the 23-phase
 * script scExplainUpdatePhase below walks. Each entry's own Sprite*
 * (a cross-file pointer into relocData 198, fixRelocChain-rewritten at
 * ROM link time) is a numeric sprite_bank_get offset instead -- see
 * scexplain.h's header note and SCExplainPhaseEntry's own declaration. */
const SCExplainPhaseEntry dSCExplainPhase[22] = {
	{
		180, 0, 0, 0,
		0x10260,
		{ 0, 0, 0 },  /* control_stick_args */
		{ 0, 0, 0 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 0, 0, 0 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		180, 0, 20, 11,
		0x11f60,
		{ 257, 26, 6 },  /* control_stick_args */
		{ 0, 0, 0 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 0, 0, 0 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		170, 0, 20, 11,
		0x12b60,
		{ 257, 36, 4 },  /* control_stick_args */
		{ 0, 0, 0 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 0, 0, 0 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		180, 0, 20, 11,
		0x13658,
		{ 257, 36, 4 },  /* control_stick_args */
		{ 0, 0, 0 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 0, 0, 0 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		170, 0, 20, 11,
		0x139f0,
		{ 0, 0, 0 },  /* control_stick_args */
		{ 245, 18, 1 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 0, 0, 0 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		210, 0, 20, 11,
		0x14448,
		{ 237, 36, 2 },  /* control_stick_args */
		{ 262, 18, 1 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 253, 33, 1 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		200, 0, 20, 11,
		0x14e30,
		{ 237, 36, 6 },  /* control_stick_args */
		{ 262, 18, 1 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 253, 33, 1 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		180, 0, 20, 11,
		0x06c58,
		{ 0, 0, 0 },  /* control_stick_args */
		{ 0, 0, 0 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 115, 0, 1 },  /* phase_args3 */
		{ 0, 0, 0 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		180, 0, 20, 11,
		0x072d8,
		{ 237, 36, 3 },  /* control_stick_args */
		{ 262, 18, 1 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 115, 0, 1 },  /* phase_args3 */
		{ 253, 33, 1 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		180, 0, 20, 11,
		0x07c38,
		{ 237, 36, 3 },  /* control_stick_args */
		{ 262, 18, 1 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 115, 0, 1 },  /* phase_args3 */
		{ 253, 33, 1 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		300, 0, 20, 11,
		0x15c40,
		{ 237, 36, 6 },  /* control_stick_args */
		{ 262, 18, 1 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 253, 33, 1 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		300, 0, 20, 11,
		0x17fe0,
		{ 257, 36, 4 },  /* control_stick_args */
		{ 0, 0, 0 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 0, 0, 0 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		100, 0, 20, 11,
		0x17fe0,
		{ 237, 36, 4 },  /* control_stick_args */
		{ 0, 0, 0 },  /* phase_args0 */
		{ 262, 18, 1 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 253, 33, 1 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		360, 0, 20, 11,
		0x1a440,
		{ 237, 36, 1 },  /* control_stick_args */
		{ 0, 0, 0 },  /* phase_args0 */
		{ 262, 18, 1 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 253, 33, 1 },  /* phase_args4 */
		{ 237, 36, 1 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		180, 0, 20, 11,
		0x08218,
		{ 0, 0, 0 },  /* control_stick_args */
		{ 0, 0, 0 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 245, 18, 1 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 0, 0, 0 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		180, 0, 20, 11,
		0x1aa10,
		{ 269, 36, 6 },  /* control_stick_args */
		{ 0, 0, 0 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 221, 18, 1 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 245, 33, 1 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		180, 0, 20, 11,
		0x1b468,
		{ 0, 0, 0 },  /* control_stick_args */
		{ 262, 18, 1 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 230, 18, 1 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 253, 33, 1 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		180, 0, 20, 11,
		0x1b950,
		{ 0, 0, 0 },  /* control_stick_args */
		{ 245, 18, 1 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 0, 0, 0 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		180, 0, 20, 11,
		0x1beb0,
		{ 0, 0, 0 },  /* control_stick_args */
		{ 245, 18, 1 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 0, 0, 0 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		200, 0, 20, 11,
		0x1cd20,
		{ 237, 36, 6 },  /* control_stick_args */
		{ 262, 18, 1 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 189, 18, 1 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 213, 33, 1 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 253, 33, 1 },  /* phase_args5 */
	},
	{
		180, 0, 20, 11,
		0x08c78,
		{ 0, 0, 0 },  /* control_stick_args */
		{ 0, 0, 0 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 0, 0, 0 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
	{
		280, 0, 20, 11,
		0x091a8,
		{ 0, 0, 0 },  /* control_stick_args */
		{ 0, 0, 0 },  /* phase_args0 */
		{ 0, 0, 0 },  /* phase_args1 */
		{ 0, 0, 0 },  /* phase_args2 */
		{ 0, 0, 0 },  /* phase_args3 */
		{ 0, 0, 0 },  /* phase_args4 */
		{ 0, 0, 0 },  /* rgb_overlay_args */
		{ 0, 0, 0 },  /* phase_args5 */
	},
};

/* relocData/252_SCExplainMain.c:2444-2451, verbatim: slots 2/3's own
 * scripts are a bare FTKEY_EVENT_END() (never read -- see the comment
 * above dSCExplainKeyEvent1). */
static const FTKeyEvent dSCExplainKeyEventEnd[1] = { FTKEY_EVENT_END() };

/* scexplain.c:34-40 dSCExplainKeyKeyEventss, substituted: the decomp's
 * table holds &llSCExplainMainNKeyEvent file offsets into
 * sSCExplainMainFileHead; this port's file 252 half is compiled in
 * (see scexplain.h), so the table holds the real script pointers
 * directly. */
static const FTKeyEvent *const dSCExplainKeyEvents[4] =
{
    dSCExplainKeyEvent0,
    dSCExplainKeyEvent1,
    dSCExplainKeyEventEnd,
    dSCExplainKeyEventEnd
};

// // // // // // // // // // // //
//                               //
//   GLOBAL / STATIC VARIABLES   //
//                               //
// // // // // // // // // // // //

// 0x8018E7F0
SCBattleState sSCExplainBattleState;

// 0x8018E9E0
void *sSCExplainGraphicsFileHead;

/* The scene-heap record behind sSCExplainGraphicsFileHead, the same
 * shape src/dc/mncongra.c's own sMNCongraBanks is. */
static SpriteBank sSCExplainGraphicsBank;

/* ---- the control-stick diagram's three models ----------
 *
 * File 198's non-sprite half, one pack each
 * (tools/export/ssb_explainexport.py). The game has no counterpart: it reads
 * all three out of the one relocData file it already has open, through
 * sSCExplainGraphicsFileHead. Here each is a .mdl the way the character
 * select's spotlight and the off-screen arrows are -- so the pack is
 * loaded once and each GObj gets a clone of it with its own clip
 * positions (src/dc/objmodel.c). */
enum
{
    nSCExplainModelStick,
    nSCExplainModelSpark,
    nSCExplainModelRGB,
    nSCExplainModelCount
};

static const char *const dSCExplainModelFiles[nSCExplainModelCount] =
{
    "scstick.mdl", "scspark.mdl", "scrgb.mdl"
};

static Fighter sSCExplainPacks[nSCExplainModelCount];
static Fighter sSCExplainModels[nSCExplainModelCount];
static sb32 sSCExplainPacksLoaded[nSCExplainModelCount];

/* dSCExplainStickMatAnimJoints (scexplain.c:22-31): which of the stick's
 * five MatAnimJoint tables `control_stick_args.sprite_status` plays. The
 * decomp's entry 0 is a NULL the caller never reaches (sw == 0 hides the
 * GObj instead); the four names after Neutral repeat it once, so the
 * seven-entry table is six live entries over five tables.
 *
 * DIVERGES only in what an entry IS: the decomp's is a file offset the
 * game turns into an `AObjEvent32 ***`; here it is which of the pack's
 * whole MatAnimJoints to play (FPackMObjs.alt_count), in the order
 * tools/export/ssb_explainexport.py laid them down. Same five tables, same
 * order, reached by index instead of by address. */
static const s8 dSCExplainStickMatAnimJoints[7] =
{
    -1,     /* never read: sw == 0 hides the stick */
    0,      /* StickNeutral      -- texture ids 0, 1 */
    0,      /* StickNeutral again, for sw == 2 (the "+" child shows) */
    1,      /* StickHoldUp       -- 2, 0 */
    2,      /* StickTapUp        -- 0, 1, 2, on a loop */
    3,      /* StickHoldForward  -- 4 */
    4       /* StickTapForward   -- 0, 3, 4, on a loop */
};

// 0x8018E9E8, substituted: points into the compiled-in dSCExplainPhase
// table instead of a reloc-loaded file (see scexplain.h).
const SCExplainPhaseEntry *sSCExplainPhase;

// 0x8018E9F0
SCExplainMain sSCExplainStruct;

/* The stage this scene holds a reference on -- always Hyrule, the
 * fallback this scene's own FuncStart always takes (see scexplain.h's
 * header note); src/dc/scautodemo.c's own sSCAutoDemoStageHeld/Kind
 * pair, minus Kind since the kind here is never anything else. */
static u8 sSCExplainStageHeld;

// // // // // // // // // // // //
//                               //
//           FUNCTIONS           //
//                               //
// // // // // // // // // // // //

/* sc/sccommon/scexplainfiles.c:23-38 scExplainSetupFiles.
 * DIVERGES the same way scAutoDemoSetupFiles/scVSBattleSetupFiles are:
 * the reloc loader's status-buffer setup and
 * lbRelocLoadFilesListed(dGMCommonFileIDs, gGMCommonFiles) are gone;
 * what remains is the load, the port's own (src/dc/gmcommon.c), already
 * shared with every other battle-shaped scene. */
void scExplainSetupFiles(void)
{
    gmCommonLoadFiles();
}

/* scexplain.c:127-148 scExplainLoadExplainFiles.
 * DIVERGES: file 198 arrives as two things rather than one -- its sprite
 * bank (scexplaingraphics.spr, tools/export/ssb_spriteexport.py --file 198) and
 * the three packs its non-sprite half bakes to ( 4c,
 * tools/export/ssb_explainexport.py). See scexplain.h's header note on why file
 * 252 (KeyEvent scripts, the ExplainPhase table) is compiled in above
 * instead of loaded here. sSCExplainPhase just points at that
 * compiled-in table. */
void scExplainLoadExplainFiles(void)
{
    if (sprite_bank_load(&sSCExplainGraphicsBank, "scexplaingraphics.spr") < 0)
    {
        sSCExplainGraphicsFileHead = NULL;
    }
    else
    {
        sSCExplainGraphicsFileHead = &sSCExplainGraphicsBank;
    }
#ifndef FT_HOSTTEST
    {
        s32 i;

        for (i = 0; i < nSCExplainModelCount; i++)
        {
            int pal_bank = 0;

            sSCExplainPacksLoaded[i] =
                (fighter_load_scene(&sSCExplainPacks[i], dSCExplainModelFiles[i],
                              &pal_bank) == 0);
        }
    }
#endif
    sSCExplainPhase = dSCExplainPhase;
}

/* scexplain.c:151-169 scExplainSetBattleState, verbatim. */
void scExplainSetBattleState(void)
{
    sSCExplainBattleState = dSCManagerDefaultBattleState;

    gSCManagerBattleState = &sSCExplainBattleState;

    gSCManagerBattleState->game_type = nSCBattleGameTypeExplain;

    gSCManagerBattleState->gkind = nGRKindExplain;

    gSCManagerBattleState->pl_count = 2;
    gSCManagerBattleState->cp_count = 0;

    gSCManagerBattleState->players[0].fkind = nFTKindMario;
    gSCManagerBattleState->players[1].fkind = nFTKindLuigi;

    gSCManagerBattleState->players[0].pkind = nFTPlayerKindGameKey;
    gSCManagerBattleState->players[1].pkind = nFTPlayerKindGameKey;
}

/* scexplain.c:172-188 scExplainStartBattle, verbatim. */
void scExplainStartBattle(void)
{
    GObj *fighter_gobj = gGCCommonLinks[nGCCommonLinkIDFighter];

    while (fighter_gobj != NULL)
    {
        FTStruct *fp = ftGetStruct(fighter_gobj);

        ftCommonAppearSetStatus(fighter_gobj);
        ftParamUnlockPlayerControl(fighter_gobj);

        fp->camera_mode = nFTCameraModeExplain;

        fighter_gobj = fighter_gobj->link_next;
    }
    gSCManagerBattleState->game_status = nSCBattleGameStatusGo;
}

/* scexplain.c:190-203 scExplainMakeCamera. Not ported: gcMakeDefaultCameraGObj
 * is the black clear camera every scene in this port already cuts (the
 * PVR clears its own framebuffer -- src/dc/scvsbattle.c's own header
 * names it first); this call is that same camera under different
 * parameters (COBJ_FLAG_ZBUFFER, not COBJ_FLAG_FILLCOLOR), not the real
 * battle camera (gmCameraMakeBattleCamera, called later, is). */

/* scexplain.c:206-215 scExplainWindowProcDisplay. DIVERGES: the
 * decomp's raw gDPSetScissor/gDPSetFillColor/gDPFillRectangle sequence
 * (a scissored, fully-opaque black fill over 10,160-310,230) is
 * lbCommonSpriteFillRect instead, in the port's own spelling for this
 * exact RDP idiom (src/dc/lbcommon.h's own comment on it, and
 * src/dc/mnvsrecord.c's grid lines are the established precedent) --
 * which is also what drops syVideoGetFillColor, the port's most-applied
 * divergence (src/dc/mnvsrecord.h, src/dc/mnsoundtest.h). The scissor
 * rectangle and the
 * fill rectangle are the same box here, so one call covers both. */
void scExplainWindowProcDisplay(GObj *gobj)
{
    lbCommonSpriteFillRect(10, 160, 310, 230, 0x00, 0x00, 0x00, 0xFF);
}

/* scexplain.c:218-236 scExplainMakeWindowCamera, verbatim. */
void scExplainMakeWindowCamera(void)
{
    gcMakeCameraGObj
    (
        nGCCommonKindScissorCamera,
        NULL,
        nGCCommonLinkIDCamera,
        GOBJ_PRIORITY_DEFAULT,
        scExplainWindowProcDisplay,
        15,
        0,
        0,
        FALSE,
        nGCProcessKindThread,
        NULL,
        0,
        FALSE
    );
}

/* scexplain.c:239-243 scExplainSetPlayerInterfacePositions, verbatim. */
void scExplainSetPlayerInterfacePositions(void)
{
    gIFCommonPlayerInterface.player_pos_x = dSCExplainInterfacePositions;
    gIFCommonPlayerInterface.player_pos_y = 150;
}

/* scexplain.c:246-269 scExplainMakeTextCamera, verbatim: the scissor
 * camera that draws the textbox and the six phase-indicator SObjs
 * (DL-link 26, lbCommonDrawSprite -- already ported, used the same way
 * by every menu scene's own sprite camera). */
GObj* scExplainMakeTextCamera(void)
{
    GObj *camera_gobj = gcMakeCameraGObj
    (
        nGCCommonKindScissorCamera,
        NULL,
        9,
        GOBJ_PRIORITY_DEFAULT,
        lbCommonDrawSprite,
        15,
        COBJ_MASK_DLLINK(26),
        -1,
        FALSE,
        nGCProcessKindFunc,
        NULL,
        1,
        FALSE
    );
    CObj *cobj = CObjGetStruct(camera_gobj);

    syRdpSetViewport(&cobj->viewport, 10.0F, 160.0F, 310.0F, 230.0F);

    return camera_gobj;
}

/* scexplain.c:272-303 scExplainMakeControlStickCamera, verbatim: the
 * ortho camera the diagram stands in, on DL link 27 with
 * func_80017EC0 as its display proc (already ported, src/dc/objdisplay.c
 * -- src/dc/mnsoundtest.c and src/dc/mnplayersvs.c call it the same
 * way). The decomp sets only the box's l/r/b/t; n, f and scale stay at
 * gcMakeCameraGObj's own dGCOrthoDefault (100, 12800, 1), and so do the
 * eye/at/up its second XObj reads -- eye (0, 0, 1500) looking at the
 * origin, which is why the diagram at z = 0 is inside the box. */
GObj* scExplainMakeControlStickCamera(void)
{
    GObj *camera_gobj = gcMakeCameraGObj
    (
        nGCCommonKindScissorCamera,
        NULL,
        nGCCommonLinkIDCamera,
        GOBJ_PRIORITY_DEFAULT,
        func_80017EC0,
        15,
        COBJ_MASK_DLLINK(27),
        -1,
        FALSE,
        nGCProcessKindFunc,
        NULL,
        1,
        FALSE
    );
    CObj *cobj = CObjGetStruct(camera_gobj);

    gcAddXObjForCamera(cobj, nGCMatrixKindOrtho, 1);
    gcAddXObjForCamera(cobj, 6, 1);

    syRdpSetViewport(&cobj->viewport, 10.0F, 10.0F, 310.0F, 230.0F);

    cobj->projection.ortho.l = -150.0F;
    cobj->projection.ortho.r = 150.0F;
    cobj->projection.ortho.b = -110.0F;
    cobj->projection.ortho.t = 110.0F;

    return camera_gobj;
}

/* ---- the diagram's three GObjs -------------------------
 *
 * The shared half of what the decomp's three makers do with one relocData
 * file: clone the pack and hang a DObj tree off the GObj, which is
 * gcSetupCustomDObjs over a DObjDesc (the stick) and gcAddDObjForGObj +
 * gcAddXObjForDObjFixed over a bare display list (the spark, the RGB
 * overlay) said in the port's terms -- src/dc/mnplayersvs.c's own
 * spotlight and src/dc/ifcommon.c's own arrows make the same two calls
 * for the same reason.
 *
 * A pack that did not load leaves the GObj without a tree, and the caller
 * returns NULL rather than a GObj whose every later read would
 * dereference nothing. */
#ifndef FT_HOSTTEST
static sb32 scExplainAddModel(GObj *gobj, s32 which)
{
    Fighter *pack = &sSCExplainPacks[which];

    if (!sSCExplainPacksLoaded[which])
    {
        return FALSE;
    }
    fighter_clone(&sSCExplainModels[which], pack,
                  syTaskmanMalloc(sizeof(float[4]) * pack->hd->vert_count,
                                  0x8));

    return dc_model_add_dobjs(gobj, NULL, &sSCExplainModels[which],
                              NULL) > 0;
}

/* gcAddAnimAll(gobj, NULL, <one of the file's MatAnimJoint tables>, 0.0F)
 * said in the port's terms: re-point this tree's MObjs at another of its
 * pack's whole MatAnimJoints. src/dc/stage.c's own stage_model_set_anim
 * is the same walk for the same reason -- `k` runs across the tree in the
 * order dc_model_add_mobjs_alt numbered the MObjs in, which is why the
 * two agree on which entry is whose -- and the anim_frame the decomp
 * passes is what gcAddAnimAll writes into gobj->anim_frame. */
static void scExplainSetMatAnim(GObj *gobj, s32 which, s32 alt)
{
    const Fighter *m = &sSCExplainModels[which];
    const FPackMObjs *mo;
    DObj *dobj = DObjGetStruct(gobj);
    MObj *mobj;
    u32 k;

    if ((m->hd == NULL) || (m->mobjs == NULL) || (alt < 0))
    {
        return;
    }
    mo = m->mobjs;

    if ((u32)alt >= mo->alt_count)
    {
        return;
    }
    gobj->anim_frame = 0.0F;
    k = 0;

    while (dobj != NULL)
    {
        for (mobj = dobj->mobj;
             (mobj != NULL) && (k < mo->mobj_count);
             mobj = mobj->next, k++)
        {
            s32 e = ((const s32 *)((const u8 *)m->blob + mo->off_entry))
                [(u32)alt * mo->mobj_count + k];

            if (e >= 0)
            {
                gcAddMObjMatAnimJoint(mobj,
                    (AObjEvent32 *)((const u8 *)m->blob + mo->off_words +
                                    (u32)e * 4), 0.0F);
            }
        }
        dobj = gcGetTreeDObjNext(dobj);
    }
}
#endif

/* scexplain.c:306-317 scExplainControlStickProcDisplay, and 415-426
 * scExplainTapSparkProcDisplay. DIVERGES: the two lines of RDP state
 * both of them queue ahead of the geometry -- gSPClearGeometryMode
 * (G_ZBUFFER) and gDPSetRenderMode(G_RM_AA_XLU_SURF, ...) -- and the two
 * that put it back afterwards are properties of the batches between
 * them, so tools/export/ssb_explainexport.py bakes them in (FPACK_NOZ and the
 * translucent list) exactly as tools/export/ssb_arrowexport.py bakes the
 * identical pair for the off-screen arrows. What is left is the draw:
 * gcDrawDObjTreeDLLinksForGObj and gcDrawDObjDLHead1 both become
 * dc_model_draw_tree_layered, the ortho, Z-less, sprite-depth submission
 * src/dc/ifcommon.c's own magnifying-glass frame already uses -- which
 * is also what keeps the diagram above the textbox sprites drawn before
 * it, since this camera is made after the text camera. */
void scExplainControlStickProcDisplay(GObj *gobj)
{
#ifndef FT_HOSTTEST
    dc_model_draw_tree_layered(gobj);
#else
    (void)gobj;
#endif
}

/* scexplain.c:320-330 scExplainProcUpdateControlStickSprite, verbatim.
 * The MObj's anim_frame is the game's own parser's (sys/objanim.c,
 * compiled unmodified), so the frame-15 test reads the same number it
 * does on the N64. */
void scExplainProcUpdateControlStickSprite(GObj *gobj)
{
    gcPlayAnimAll(gobj);

    if (DObjGetStruct(gobj)->mobj == NULL)
    {
        return;
    }

    if (DObjGetStruct(gobj)->mobj->anim_frame == 15.0F)
    {
        if ((sSCExplainStruct.stick_status == 4) ||
            (sSCExplainStruct.stick_status == 6))
        {
            scExplainUpdateTapSparkEffect();
        }
    }
}

/* scexplain.c:333-367 scExplainMakeControlStickInterface. DIVERGES the
 * two ways src/dc/mnplayersvs.c's own mnPlayersVSMakeSpotlight already
 * documents: gcSetupCustomDObjs over the file's DObjDesc becomes
 * dc_model_add_dobjs over the pack's joints, and gcAddMObjAll over the
 * file's `MObjSub ***` becomes dc_model_add_mobjs, which builds that
 * same shape back out of the pack and hands it to the game's own
 * gcAddMObjAll. The three matrix kinds the decomp names (Tra, Null,
 * Null) are gcAddDObjMatrixSetsRpyR's, which is what dc_model_add_dobjs
 * installs. */
GObj* scExplainMakeControlStickInterface(void)
{
    GObj *interface_gobj = gcMakeGObjSPAfter
    (
        nGCCommonKindInterface,
        NULL,
        nGCCommonLinkIDInterface,
        GOBJ_PRIORITY_DEFAULT
    );
    gcAddGObjDisplay(interface_gobj, scExplainControlStickProcDisplay, 27, GOBJ_PRIORITY_DEFAULT, ~0);

#ifndef FT_HOSTTEST
    if (!scExplainAddModel(interface_gobj, nSCExplainModelStick))
    {
        return NULL;
    }
    dc_model_add_mobjs(interface_gobj, &sSCExplainModels[nSCExplainModelStick], 0.0F);
#else
    /* As the spotlight's and the arrows': the host cross-test links the
     * scene and not the renderer, so there is no pack to build a tree
     * from and func_ovl63_8018DDBC's own placement still needs one DObj
     * to land on. Its child, which sw == 2 shows, is the second joint. */
    gcAddDObjRpyR(interface_gobj, NULL);
    gcAddDObjRpyR(DObjGetStruct(interface_gobj), NULL);
#endif
    gcAddGObjProcess(interface_gobj, scExplainProcUpdateControlStickSprite, nGCProcessKindFunc, 5);

    interface_gobj->flags = GOBJ_FLAG_HIDDEN;

    return interface_gobj;
}

/* scexplain.c:429-448 scExplainUpdateTapSparkEffect, substituted at the
 * one line: gcAddAnimAll over the file's TapSparkMatAnimJoint becomes
 * scExplainSetMatAnim over the pack's only alternate (0). */
void scExplainUpdateTapSparkEffect(void)
{
    GObj *gobj = sSCExplainStruct.spark_gobj;
    DObj *dobj;
    Vec3f *pos;

    if ((gobj == NULL) || (sSCExplainStruct.stick_gobj == NULL))
    {
        return;
    }
    dobj = DObjGetStruct(gobj);
    pos = &DObjGetStruct(sSCExplainStruct.stick_gobj)->translate.vec.f;

    if (sSCExplainStruct.stick_status == 4)
    {
        dobj->translate.vec.f.x = pos->x + 5.0F;
        dobj->translate.vec.f.y = pos->y + 15.0F;
    }
    else
    {
        dobj->translate.vec.f.x = pos->x + 15.0F;
        dobj->translate.vec.f.y = pos->y + 5.0F;
    }
#ifndef FT_HOSTTEST
    scExplainSetMatAnim(gobj, nSCExplainModelSpark, 0);
#endif
    gcPlayAnimAll(gobj);

    gobj->flags = GOBJ_FLAG_NONE;
}

/* scexplain.c:451-459 scExplainTapSparkProcUpdate, verbatim: the spark
 * hides itself again the frame its own material animation runs out. */
void scExplainTapSparkProcUpdate(GObj *gobj)
{
    gcPlayAnimAll(gobj);

    if (DObjGetStruct(gobj)->mobj == NULL)
    {
        return;
    }

    if (DObjGetStruct(gobj)->mobj->anim_wait == AOBJ_ANIM_NULL)
    {
        gobj->flags = GOBJ_FLAG_HIDDEN;
    }
}

/* scexplain.c:462-473 scExplainMakeTapSpark. DIVERGES: gcAddDObjForGObj
 * over the file's raw display list plus gcAddXObjForDObjFixed becomes
 * dc_model_add_dobjs over a pack whose one joint carries that list --
 * which is not a nicety. Handing gcAddDObjForGObj a raw N64 Gfx* makes
 * that pointer the DObj's `dv`, the union member gcSubmitDObj calls
 * through as a DCDisplay*, and that crashed real hardware on frame 1 the
 * last time this port tried it (src/dc/scstaffroll.h's fifth DIVERGES).
 * gcAddMObjAll is dc_model_add_mobjs, as the stick's. */
GObj* scExplainMakeTapSpark(void)
{
    GObj *interface_gobj = gcMakeGObjSPAfter(nGCCommonKindInterface, NULL, nGCCommonLinkIDInterface, GOBJ_PRIORITY_DEFAULT);

    gcAddGObjDisplay(interface_gobj, scExplainControlStickProcDisplay, 27, GOBJ_PRIORITY_DEFAULT, ~0);

#ifndef FT_HOSTTEST
    if (!scExplainAddModel(interface_gobj, nSCExplainModelSpark))
    {
        return NULL;
    }
    dc_model_add_mobjs(interface_gobj, &sSCExplainModels[nSCExplainModelSpark], 0.0F);
#else
    gcAddDObjRpyR(interface_gobj, NULL);
#endif
    gcAddGObjProcess(interface_gobj, scExplainTapSparkProcUpdate, nGCProcessKindFunc, 5);

    interface_gobj->flags = GOBJ_FLAG_HIDDEN;

    sSCExplainStruct.stick_status = 0;

    return interface_gobj;
}

/* scexplain.c:437-454 scExplainSpecialMoveRGBProcUpdate. The NULL guard
 * is the port's: a pack that did not load leaves rgb_gobj NULL, which on
 * the N64 cannot happen. */
void scExplainSpecialMoveRGBProcUpdate(void)
{
    s32 sw = sSCExplainPhase->rgb_overlay_args.sprite_status;
    GObj *gobj = sSCExplainStruct.rgb_gobj;

    if (gobj == NULL)
    {
        return;
    }

    if (sw == 1)
    {
        DObj *dobj = DObjGetStruct(gobj);

        dobj->translate.vec.f.x = (sSCExplainPhase->control_stick_args.sprite_pos_x - 0x96);
        dobj->translate.vec.f.y = (-0x28 - sSCExplainPhase->control_stick_args.sprite_pos_y);

        gobj->flags = GOBJ_FLAG_NONE;
    }
    else gobj->flags = GOBJ_FLAG_HIDDEN;
}

/* scexplain.c:462-473 scExplainMakeSpecialMoveRGB. The same shape
 * scExplainMakeTapSpark above is, with no MObj: this quad's tile and
 * TLUT are its own display list's, so the pack carries them baked and
 * there is nothing for gcAddMObjAll to add. */
GObj* scExplainMakeSpecialMoveRGB(void)
{
    GObj *interface_gobj = gcMakeGObjSPAfter
    (
        nGCCommonKindInterface,
        NULL,
        nGCCommonLinkIDInterface,
        GOBJ_PRIORITY_DEFAULT
    );
    gcAddGObjDisplay(interface_gobj, scExplainControlStickProcDisplay, 27, GOBJ_PRIORITY_DEFAULT, ~0);

#ifndef FT_HOSTTEST
    if (!scExplainAddModel(interface_gobj, nSCExplainModelRGB))
    {
        return NULL;
    }
#else
    gcAddDObjRpyR(interface_gobj, NULL);
#endif
    interface_gobj->flags = GOBJ_FLAG_HIDDEN;

    return interface_gobj;
}

/* scexplain.c:476-481 scExplainSetInterfaceGObjs, verbatim. Each maker
 * returns NULL where its pack did not load, which is what every guarded
 * read of the three still checks. */
void scExplainSetInterfaceGObjs(void)
{
    sSCExplainStruct.stick_gobj = scExplainMakeControlStickInterface();
    sSCExplainStruct.spark_gobj = scExplainMakeTapSpark();
    sSCExplainStruct.rgb_gobj   = scExplainMakeSpecialMoveRGB();
}

/* scexplain.c:484-503 scExplainMakeSObjOffset, verbatim but for the
 * offset argument: the decomp passes &llSCExplainGraphicsXxxSprite (a
 * file-offset address); this port's call sites below pass the same
 * numeric offset directly, the same substitution src/dc/mncongra.c's
 * own llMNCongraPictureSprite makes. */
SObj* scExplainMakeSObjOffset(intptr_t offset)
{
    GObj *interface_gobj;
    SObj *sobj;

    interface_gobj = gcMakeGObjSPAfter
    (
        nGCCommonKindInterface,
        NULL,
        nGCCommonLinkIDInterface,
        GOBJ_PRIORITY_DEFAULT
    );
    gcAddGObjDisplay(interface_gobj, lbCommonDrawSObjAttr, 26, GOBJ_PRIORITY_DEFAULT, ~0);

    sobj = lbCommonMakeSObjForGObj(interface_gobj, lbRelocGetFileData(Sprite*, sSCExplainGraphicsFileHead, offset));

    sobj->sprite.attr |= SP_HIDDEN;

    return sobj;
}

/* scexplain.c:506-515 scExplainSetPhaseSObjs, offsets substituted for
 * &llSCExplainGraphicsXxxSprite -- see scExplainMakeSObjOffset above.
 * Offsets from tools/relocFileDescriptions.us.txt's own [198] catalogue
 * (confirmed against tools/export/ssb_spriteexport.py --file 198 --list). */
void scExplainSetPhaseSObjs(void)
{
    sSCExplainStruct.textbox_sobj = scExplainMakeSObjOffset(0x11f60); /* TapTheStick */
    sSCExplainStruct.phase_sobj0  = scExplainMakeSObjOffset(0x1d338); /* AButton */
    sSCExplainStruct.phase_sobj1  = scExplainMakeSObjOffset(0x1d948); /* BButton */
    sSCExplainStruct.phase_sobj2  = scExplainMakeSObjOffset(0x1df58); /* ZButton */
    sSCExplainStruct.phase_sobj3  = scExplainMakeSObjOffset(0x09628); /* HereText */
    sSCExplainStruct.phase_sobj4  = scExplainMakeSObjOffset(0x1e018); /* PlusSymbol */
    sSCExplainStruct.phase_sobj5  = scExplainMakeSObjOffset(0x1e018); /* PlusSymbol */
}

/* scexplain.c:518-526 scExplainUpdateTextBoxSprite, substituted for the
 * ExplainPhase.sprite -> sprite_offset rename (see scexplain.h). */
void scExplainUpdateTextBoxSprite(void)
{
    sSCExplainStruct.textbox_sobj->sprite = *lbRelocGetFileData(Sprite*, sSCExplainGraphicsFileHead, sSCExplainPhase->sprite_offset);

    sSCExplainStruct.textbox_sobj->pos.x = sSCExplainPhase->textbox_pos_x + 10;
    sSCExplainStruct.textbox_sobj->pos.y = sSCExplainPhase->textbox_pos_y + 160;

    sSCExplainStruct.textbox_sobj->sprite.attr = SP_TEXSHUF | SP_TRANSPARENT;
}

/* scexplain.c:529-558 func_ovl63_8018DDBC (unnamed in the decomp, so
 * kept unnamed here): show, place and animate the control-stick diagram
 * for the phase that has just become current. DIVERGES only in what
 * dSCExplainStickMatAnimJoints[sw] is -- a pack alternate rather than a
 * file offset (see that table above) -- plus the NULL guard a scene
 * whose pack may not have loaded needs. */
void func_ovl63_8018DDBC(void)
{
    s32 sw = sSCExplainPhase->control_stick_args.sprite_status;
    GObj *stick_gobj = sSCExplainStruct.stick_gobj;

    if (stick_gobj == NULL)
    {
        sSCExplainStruct.stick_status = sw;
        return;
    }

    if (sw == 0)
    {
        stick_gobj->flags = GOBJ_FLAG_HIDDEN;
    }
    else
    {
        DObj *dobj = DObjGetStruct(stick_gobj);

        dobj->translate.vec.f.x = sSCExplainPhase->control_stick_args.sprite_pos_x - 150;
        dobj->translate.vec.f.y = -40 - sSCExplainPhase->control_stick_args.sprite_pos_y;

        if (dobj->child != NULL)
        {
            dobj->child->flags = (sw == 2) ? DOBJ_FLAG_NONE : DOBJ_FLAG_HIDDEN;
        }
#ifndef FT_HOSTTEST
        if ((u32)sw < ARRAY_COUNT(dSCExplainStickMatAnimJoints))
        {
            scExplainSetMatAnim(stick_gobj, nSCExplainModelStick,
                                dSCExplainStickMatAnimJoints[sw]);
        }
#endif
        gcPlayAnimAll(stick_gobj);

        stick_gobj->flags = GOBJ_FLAG_NONE;
    }
    sSCExplainStruct.stick_status = sw;
}

/* scexplain.c:561-565 scExplainHideTapSpark, guarded: sSCExplainStruct.
 * spark_gobj is always NULL in this port -- see scexplain.h. */
void scExplainHideTapSpark(void)
{
    if (sSCExplainStruct.spark_gobj != NULL)
    {
        sSCExplainStruct.spark_gobj->flags = GOBJ_FLAG_HIDDEN;
    }
}

/* scexplain.c:568-578 scExplainUpdateArgsSObj, verbatim. */
void scExplainUpdateArgsSObj(SCExplainArgs *args, SObj *sobj)
{
    if (args->sprite_status == 1)
    {
        sobj->sprite.attr &= ~SP_HIDDEN;

        sobj->pos.x = args->sprite_pos_x + 10;
        sobj->pos.y = args->sprite_pos_y + 160;
    }
    else sobj->sprite.attr |= SP_HIDDEN;
}

/* scexplain.c:581-599 scExplainDetectExit, verbatim: any pad's A/B/START
 * ends the demo early, back to the title. */
void scExplainDetectExit(void)
{
    s32 player;

    for (player = 0; player < (s32)ARRAY_COUNT(gSYControllerDevices); player++)
    {
        u16 button_tap = gSYControllerDevices[player].button_tap;

        if (button_tap & (A_BUTTON | B_BUTTON | START_BUTTON))
        {
            gSCManagerSceneData.scene_prev = gSCManagerSceneData.scene_curr;
            gSCManagerSceneData.scene_curr = nSCKindTitle;

            syTaskmanSetLoadScene();

            break;
        }
    }
}

/* scexplain.c:602-618 scExplainTryMakeFireFlower, verbatim: a real Fire
 * Flower item spawn at phase 16 (itManagerMakeItemSetupCommon, ported
 *  2). */
void scExplainTryMakeFireFlower(void)
{
    Vec3f pos;
    Vec3f vel;

    if (sSCExplainStruct.phase == 16)
    {
        pos.x = -1400.0F;
        pos.y = 1500.0F;
        pos.z = 0.0F;

        vel.x = vel.z = 0.0F;
        vel.y = 10.0F;

        itManagerMakeItemSetupCommon(NULL, nITKindFFlower, &pos, &vel, ITEM_FLAG_PARENT_DEFAULT);
    }
}

/* scexplain.c:621-657 scExplainUpdatePhase, verbatim: the 23-phase
 * (0-22) script's own timer/advance -- each entry's own phase_time is
 * read AFTER it becomes current, unlike src/dc/scautodemo.c's own
 * dSCAutoDemoFuncList (whose focus_end_wait governs the NEXT entry's
 * dwell, not its own) -- there is no "off by one entry" trap here, only
 * the ordinary "read the new entry's own timer once you have advanced
 * onto it" shape. */
void scExplainUpdatePhase(void)
{
    if (sSCExplainStruct.phase_advance_wait == 0)
    {
        scExplainTryMakeFireFlower();

        sSCExplainStruct.phase++;

        if (sSCExplainStruct.phase > 22)
        {
            gSCManagerSceneData.scene_prev = gSCManagerSceneData.scene_curr;
            gSCManagerSceneData.scene_curr = nSCKindCharacters;

            syTaskmanSetLoadScene();

            return;
        }
        else
        {
            scExplainUpdateTextBoxSprite();
            func_ovl63_8018DDBC();
            scExplainHideTapSpark();
            scExplainSpecialMoveRGBProcUpdate();
            scExplainUpdateArgsSObj(&sSCExplainPhase->phase_args0, sSCExplainStruct.phase_sobj0);
            scExplainUpdateArgsSObj(&sSCExplainPhase->phase_args1, sSCExplainStruct.phase_sobj1);
            scExplainUpdateArgsSObj(&sSCExplainPhase->phase_args2, sSCExplainStruct.phase_sobj2);
            scExplainUpdateArgsSObj(&sSCExplainPhase->phase_args3, sSCExplainStruct.phase_sobj3);
            scExplainUpdateArgsSObj(&sSCExplainPhase->phase_args4, sSCExplainStruct.phase_sobj4);
            scExplainUpdateArgsSObj(&sSCExplainPhase->phase_args5, sSCExplainStruct.phase_sobj5);

            sSCExplainStruct.phase_advance_wait = sSCExplainPhase->phase_time;

            sSCExplainPhase++;
        }
    }
    sSCExplainStruct.phase_advance_wait--;
}

/* scexplain.c:660-664 scExplainSceneInterfaceProcUpdate, verbatim. */
void scExplainSceneInterfaceProcUpdate(GObj *gobj)
{
    (void)gobj;

    scExplainDetectExit();
    scExplainUpdatePhase();
}

/* scexplain.c:667-684 scExplainMakeSceneInterface, verbatim. */
GObj* scExplainMakeSceneInterface(void)
{
    GObj *interface_gobj = gcMakeGObjSPAfter
    (
        nGCCommonKindInterface,
        NULL,
        nGCCommonLinkIDInterface,
        GOBJ_PRIORITY_DEFAULT
    );
    gcAddGObjProcess(interface_gobj, scExplainSceneInterfaceProcUpdate, nGCProcessKindFunc, 5);

    sSCExplainStruct.phase_advance_wait = 0;
    sSCExplainStruct.phase = 0;

    scExplainSceneInterfaceProcUpdate(interface_gobj);

    return interface_gobj;
}

/* scexplain.c:687-799 scExplainFuncStart, the setup: SYTaskmanSetup.
 * func_start, called once the pools exist. Cuts here are the same
 * classes src/dc/scvsbattle.c's own scVSBattleStartBattle and
 * src/dc/scautodemo.c's own scAutoDemoFuncStart already name for this
 * battle spine (scExplainSetupFiles above stands in for the reloc
 * loader; the black clear camera, scExplainMakeCamera, is gone; the
 * wallpaper camera is gone, its substitute grWallpaperMakeDecideKind
 * moved after gmCameraMakeBattleCamera; efManagerInitEffects is
 * efManagerLoadEffectBank; mpCollisionInitGroundData is
 * stage_bind_collision) plus this file's own two: the Hyrule ground
 * fallback block (see scexplain.h) where the decomp has none at all,
 * and scExplainMakeControlStickCamera dropped from the call sequence
 * entirely (see scexplain.h; nothing else here reads what it would
 * have drawn). */
void scExplainFuncStart(void)
{
    GObj *fighter_gobj;
    s32 player;
    FTDesc desc;
    SYColorRGBA color;

    scExplainSetBattleState();

    /* DIVERGES: nGRKindExplain has no exported pack (relocData 267/115
     * are real ground/map data but no tool in this port exports them --
     * see scexplain.h) -- fall back to Hyrule for ground, collision and
     * wallpaper, the same "no pack -> Hyrule" substitute
     * src/dc/scvsbattle.c's own scVSBattleStartScene and
     * src/dc/scautodemo.c's own scAutoDemoFuncStart already use,
     * unconditional here since Explain's gkind never has a pack to try
     * first. Without some bound stage, stage_bind_collision below
     * leaves gMPCollisionGeometry untouched and the player-position
     * read a few lines down dereferences it unconditionally. */
    {
        Stage *stage = grStageAcquire(nGRKindHyrule);

        sSCExplainStageHeld = (stage != NULL);
        if (stage != NULL)
        {
            stage_bind(stage);
        }
    }

    scExplainSetupFiles();
    scExplainLoadExplainFiles();
    gmCameraSetViewportDimensions(10, 10, 310, 160);
    efParticleInitAll();
    ftParamInitGame();
    stage_bind_collision();
    gmCameraMakeBattleCamera();
    /* DIVERGES, port-only, as in scvsbattle.c/scautodemo.c/sc1pgame.c:
     * gmCameraMakeBattleCamera leaves camera_mask empty, and an empty
     * mask walks no DL link -- How to Play drew its wallpaper and HUD
     * and not one stage or fighter triangle until this line. */
    gGMCameraGObj->camera_mask = GMCAMERA_BATTLE_DLLINK_MASK;
    grWallpaperMakeDecideKind();
    itManagerInitItems();
    grCommonSetupInitAll();
    ftManagerAllocFighter(FTDATA_FLAG_MAINMOTION, 2);
    wpManagerAllocWeapons();
    efManagerLoadEffectBank();
    /* DIVERGES (port only): the three model preloads scVSBattleStartBattle
     * runs, so the demo's fireball, items and effects are not each read
     * off the disc the first time they appear -- a DB_IO_TRACE probe
     * showed a dozen such reads mid-scene. */
    efManagerPreloadModels();
    wpManagerPreloadModels();
    itemModelPreloadAll();
    ifScreenFlashMakeInterface(0xFF);
    gmRumbleMakeActor();
    ftPublicMakeActor();

    for (player = 0; player < (s32)ARRAY_COUNT(gSCManagerBattleState->players); player++)
    {
        desc = dFTManagerDefaultFighterDesc;

        if (gSCManagerBattleState->players[player].pkind == nFTPlayerKindNot)
        {
            continue;
        }
        ftManagerSetupFilesAllKind(gSCManagerBattleState->players[player].fkind);

        desc.fkind = gSCManagerBattleState->players[player].fkind;

        mpCollisionGetPlayerMapObjPosition(player, &desc.pos);

        desc.lr = (desc.pos.x >= 0.0F) ? -1 : +1;

        desc.team = gSCManagerBattleState->players[player].team;

        desc.player = player;

        desc.detail = ((gSCManagerBattleState->pl_count + gSCManagerBattleState->cp_count) < 3) ? nFTPartsDetailHigh : nFTPartsDetailLow;

        desc.costume = gSCManagerBattleState->players[player].costume;

        desc.handicap = gSCManagerBattleState->players[player].handicap;

        desc.level = gSCManagerBattleState->players[player].level;

        desc.stock_count = gSCManagerBattleState->stocks;

        desc.damage = 0;

        desc.pkind = gSCManagerBattleState->players[player].pkind;

        desc.controller = &gSYControllerDevices[player];

        desc.figatree_heap = ftManagerAllocFigatreeHeapKind(gSCManagerBattleState->players[player].fkind);

        fighter_gobj = ftManagerMakeFighter(&desc);

        gSCManagerBattleState->players[player].color = player;
        gSCManagerBattleState->players[player].tag = player;

        ftParamInitPlayerBattleStats(player, fighter_gobj);

        ftParamSetKey(fighter_gobj, (FTKeyEvent *)dSCExplainKeyEvents[player]);
    }
    scExplainStartBattle();
    gmCameraMakePlayerArrowsCamera();
    ifCommonPlayerArrowsInitInterface();
    gmCameraMakePlayerMagnifyCamera();
    ifCommonPlayerMagnifyMakeInterface();

    gIFCommonPlayerInterface.is_magnify_display = TRUE;

    gmCameraScreenFlashMakeCamera();
    gmCameraMakeInterfaceCamera();
    gmCameraMakeEffectCamera();
    ifCommonPlayerTagMakeInterface();
    scExplainSetPlayerInterfacePositions();
    ifCommonPlayerDamageInitInterface();
    ifCommonPlayerDamageSetShowInterface();
    ifCommonPlayerStockInitInterface();
    scExplainMakeWindowCamera();
    scExplainMakeTextCamera();
    scExplainMakeControlStickCamera();
    scExplainSetInterfaceGObjs();
    scExplainSetPhaseSObjs();
    scExplainMakeSceneInterface();
    mpCollisionSetPlayBGM();
    func_800269C0_275C0(nSYAudioVoiceAnnounceHowToPlay);

    color = dSCExplainFadeColor;

    lbFadeMakeActor(nGCCommonKindTransition, nGCCommonLinkIDTransition, 10, &color, 12, TRUE, NULL);
    /* From here to the scene's end nothing should be read: any file that
     * is gets a line naming it (src/dc/assetroot.h), the same guard
     * scVSBattleStartBattle ends on. */
    asset_io_expect_none("How to Play");
}

/* scexplain.c:801-807 scExplainFuncLights. Not ported -- see
 * dSCExplainTaskmanSetup's own pre-render field below: ftDisplayLightsDrawReflect
 * is the same dropped reflection lighting every scene's func_lights
 * drops (src/dc/scvsbattle.c's own header names it first). */

/* scexplain.c:809-814 scExplainFuncUpdate, verbatim: the update draws
 * from the first stream. sys/utils.c is compiled unmodified, so the
 * pointer swap is the game's own. */
void scExplainFuncUpdate(void)
{
    syUtilsSetRandomSeedPtr(&dSCExplainRandomSeed1);
    gcRunAll();
}

/* scexplain.c:816-821 scExplainFuncDraw, verbatim: the draw takes the
 * second stream, so however many random numbers the display procs use,
 * the demo's own play stays the same. The port's draw runs once per PVR
 * list (src/dc/taskman.c), so a display proc that draws a random
 * number takes three a frame from this stream where the N64 took one.
 * That changes only what is drawn, never the play, which is the point
 * of the second stream. */
void scExplainFuncDraw(void)
{
    syUtilsSetRandomSeedPtr(&dSCExplainRandomSeed2);
    scManagerFuncDraw();
}

/* scexplain.c:824-838 scExplainStartScene, the scene manager's entry.
 * DIVERGES: syVideoInit/the zbuffer allocation/arena_size are the same
 * cuts src/dc/scautodemo.c's own scAutoDemoStartScene documents (one
 * video mode, set once at boot; the link-map address again). Unlike
 * that scene, this one's own scExplainUpdatePhase sets scene_curr
 * itself only on the exit paths (23rd phase, or scExplainDetectExit's
 * own A/B/START), from inside the task, before scManagerFuncUpdate
 * below returns -- so this does not set it again either, the same
 * reasoning scAutoDemoStartScene's own header gives. The Hyrule release
 * is this file's own addition (the decomp has no stage of its own to
 * release) -- see scexplain.h. */
void scExplainStartScene(void)
{
    syUtilsSetRandomSeedPtr(&dSCExplainRandomSeed1);

    dSCExplainTaskmanSetup.func_start = scExplainFuncStart;

    scManagerFuncUpdate(&dSCExplainTaskmanSetup);

    gmRumbleInitPlayers();
    syUtilsSetRandomSeedPtr(NULL);

    if (sSCExplainStageHeld)
    {
        grStageRelease(nGRKindHyrule);
        sSCExplainStageHeld = 0;
    }
    lbpTexFreeAll();
}

/* The port's own bzero arm for dSCManagerOverlays[63] (src/dc/overlay.c),
 * the same role src/dc/scautodemo.c's own scAutoDemoOverlayLoad plays
 * for overlay 64. */
void scExplainOverlayLoad(void)
{
#ifndef FT_HOSTTEST
    /* Before the clear, not after: the release needs the pointers the
     * clear is about to drop. The three instances hold nothing of their
     * own -- fighter_clone shares the pack's blob and never owns it --
     * so releasing the packs is the whole of it (src/dc/mnplayersvs.c's
     * own spotlight note). */
    {
        s32 i;

        for (i = 0; i < nSCExplainModelCount; i++)
        {
            if (sSCExplainPacksLoaded[i])
            {
                fighter_release(&sSCExplainPacks[i]);
            }
        }
    }
#endif
    OVERLAY_CLEAR(sSCExplainPacks);
    OVERLAY_CLEAR(sSCExplainModels);
    OVERLAY_CLEAR(sSCExplainPacksLoaded);
    OVERLAY_CLEAR(dSCExplainFadeColor);
    OVERLAY_CLEAR(sSCExplainBattleState);
    OVERLAY_CLEAR(sSCExplainGraphicsFileHead);
    OVERLAY_CLEAR(sSCExplainGraphicsBank);
    OVERLAY_CLEAR(sSCExplainPhase);
    OVERLAY_CLEAR(sSCExplainStruct);
    OVERLAY_CLEAR(sSCExplainStageHeld);
    /* .data the game writes (see their definition): the N64's reload
     * brings them back from ROM, so they go back to 1 here. */
    dSCExplainRandomSeed1 = 0x00000001;
    dSCExplainRandomSeed2 = 0x00000001;
}
