/* scprefetch.h -- GENERATED by tools/export/prefetch_lists.py from a
 * -DDB_IO_TRACE boot through the opening movie; do not edit. What each
 * scene opens, in the order it runs, for the loader to read ahead
 * (src/dc/assetroot.h, "Reading ahead"; src/dc/scmanager.c queues it). */

#ifndef SSB_DC_SCPREFETCH_H
#define SSB_DC_SCPREFETCH_H

/* openingroom: 25 files, 1458984 bytes in the log's run */
static const char *const sSCPrefetch_openingroom[] = {
    "mvopeningroomwallpaper.spr",
    "mvopeningroom.cam",
    "mvroomwipe.bin",
    "efcommon.scb",
    "efcommon.txb",
    "efcommon.txp",
    "boss.pack",
    "boss.anm",
    "mvopeningroomoutside.mdl",
    "mvopeningroomhaze.mdl",
    "mvopeningroombackground0.mdl",
    "mvopeningroombackground1.mdl",
    "mvopeningroomsunlight.mdl",
    "mvopeningroomdesk.mdl",
    "mvopeningroomlogo.mdl",
    "mvopeningroombooks.mdl",
    "mvopeningroomlamp.mdl",
    "mvopeningroomtissues.mdl",
    "mvopeningroombossshadow.mdl",
    "mvopeningroompencils.mdl",
    "mvopeningroomspotlight.mdl",
    "mvopeningroomsnap.mdl",
    "mvopeningroomdeskground.mdl",
    "mvopeningroomcloseupair.mdl",
    "mvopeningroomcloseupground.mdl",
};

/* openingportraits: 2 files, 657760 bytes in the log's run */
static const char *const sSCPrefetch_openingportraits[] = {
    "mvopeningportraitsset1.spr",
    "mvopeningportraitsset2.spr",
};

/* openingmario: 13 files, 1124152 bytes in the log's run */
static const char *const sSCPrefetch_openingmario[] = {
    "ifannounce.spr",
    "mvopeningcommon.cam",
    "castle.stg",
    "itcommon.itp",
    "itcommon.scb",
    "itcommon.txb",
    "itcommon.txp",
    "ifcommonitem.spr",
    "itgbumper.mdl",
    "ftshadow.mdl",
    "mario.pack",
    "mario.anm",
    "ftmario.spr",
};

/* openingdonkey: 4 files, 1203032 bytes in the log's run */
static const char *const sSCPrefetch_openingdonkey[] = {
    "jungle.stg",
    "donkey.pack",
    "donkey.anm",
    "ftdonkey.spr",
};

/* openinglink: 7 files, 409804 bytes in the log's run */
static const char *const sSCPrefetch_openinglink[] = {
    "hyrule.stg",
    "grhyrule.scb",
    "grhyrule.txb",
    "grhyrule.txp",
    "link.pack",
    "link.anm",
    "ftlink.spr",
};

/* openingsamus: 4 files, 1126444 bytes in the log's run */
static const char *const sSCPrefetch_openingsamus[] = {
    "zebes.stg",
    "samus.pack",
    "samus.anm",
    "ftsamus.spr",
};

/* openingyoshi: 10 files, 516452 bytes in the log's run */
static const char *const sSCPrefetch_openingyoshi[] = {
    "yoster.stg",
    "gryoster.scb",
    "gryoster.txb",
    "gryoster.txp",
    "yoshi.pack",
    "yoshi.anm",
    "particles_unk2.scb",
    "particles_unk2.txb",
    "particles_unk2.txp",
    "ftyoshi.spr",
};

/* openingkirby: 10 files, 1239532 bytes in the log's run */
static const char *const sSCPrefetch_openingkirby[] = {
    "pupupu.stg",
    "grpupupu.scb",
    "grpupupu.txb",
    "grpupupu.txp",
    "kirby.pack",
    "kirby.anm",
    "particles_unk0.scb",
    "particles_unk0.txb",
    "particles_unk0.txp",
    "ftkirby.spr",
};

/* openingfox: 5 files, 972972 bytes in the log's run */
static const char *const sSCPrefetch_openingfox[] = {
    "sector.stg",
    "wpfoxblaster.mdl",
    "fox.pack",
    "fox.anm",
    "ftfox.spr",
};

/* openingpikachu: 4 files, 1198380 bytes in the log's run */
static const char *const sSCPrefetch_openingpikachu[] = {
    "yamabuki.stg",
    "pikachu.pack",
    "pikachu.anm",
    "ftpikachu.spr",
};

/* openingrun: 3 files, 109320 bytes in the log's run */
static const char *const sSCPrefetch_openingrun[] = {
    "mvopeningrun.spr",
    "mvopeningrun.cam",
    "mvopeningruncrash.mdl",
};

/* openingcliff: 4 files, 150024 bytes in the log's run */
static const char *const sSCPrefetch_openingcliff[] = {
    "mvopeningcliff.spr",
    "mvopeningcliff.cam",
    "mvopeningcliffhills.mdl",
    "mvopeningcliffocarina.mdl",
};

/* openingyamabuki: 5 files, 584916 bytes in the log's run */
static const char *const sSCPrefetch_openingyamabuki[] = {
    "mvopeningyamabuki.spr",
    "mvopeningyamabuki.cam",
    "mvopeningyamabukilegs.mdl",
    "mvopeningyamabukilegsshadow.mdl",
    "mvopeningyamabukimball.mdl",
};

/* openingjungle: 3 files, 525328 bytes in the log's run */
static const char *const sSCPrefetch_openingjungle[] = {
    "mvopeningjungle.cam",
    "jungle.stg",
    "wpsamuschargeshot.mdl",
};

/* openingyoster: 5 files, 339324 bytes in the log's run */
static const char *const sSCPrefetch_openingyoster[] = {
    "mvopeningyoster.spr",
    "mvopeningyoster.cam",
    "mvopeningyosternest.mdl",
    "mvopeningyosternestrest.mdl",
    "mvopeningyosterground.mdl",
};

/* openingsector: 5 files, 645620 bytes in the log's run */
static const char *const sSCPrefetch_openingsector[] = {
    "mvopeningsector.spr",
    "mvopeningsectorwallpaper.spr",
    "mvopeningsector.cam",
    "mvopeningsectorgreatfox.mdl",
    "mvopeningsectorarwing.mdl",
};

/* openingstandoff: 4 files, 209404 bytes in the log's run */
static const char *const sSCPrefetch_openingstandoff[] = {
    "mvopeningcliff.spr",
    "mvopeningstandoff.cam",
    "mvopeningstandoffground.mdl",
    "mvopeningstandofflightning.mdl",
};

/* openingclash: 5 files, 99076 bytes in the log's run */
static const char *const sSCPrefetch_openingclash[] = {
    "mvopeningclash.cam",
    "mvopeningclashwallll.mdl",
    "mvopeningclashwalllr.mdl",
    "mvopeningclashwallul.mdl",
    "mvopeningclashwallur.mdl",
};

/* openingnewcomers: 4 files, 441904 bytes in the log's run */
static const char *const sSCPrefetch_openingnewcomers[] = {
    "mvopeningncpurinhide.mdl",
    "mvopeningnccaptainhide.mdl",
    "mvopeningncluigihide.mdl",
    "mvopeningncnesshide.mdl",
};

/* title: 10 files, 815696 bytes in the log's run */
static const char *const sSCPrefetch_title[] = {
    "mntitle.spr",
    "mntitlefire.spr",
    "mntitle.scb",
    "mntitle.txb",
    "mntitle.txp",
    "mntitlelogo.tra",
    "mntitlelabels.tra",
    "mntitlepress.tra",
    "mntitleslash.mdl",
    "mntitlefiretree.tra",
};

typedef struct SCPrefetchScene
{
    s32 scene;
    const char *const *files;
    int count;
} SCPrefetchScene;

static const SCPrefetchScene dSCPrefetchOpening[] = {
    { nSCKindStartup, NULL, 0 },
    { nSCKindOpeningRoom, sSCPrefetch_openingroom, 25 },
    { nSCKindOpeningPortraits, sSCPrefetch_openingportraits, 2 },
    { nSCKindOpeningMario, sSCPrefetch_openingmario, 13 },
    { nSCKindOpeningDonkey, sSCPrefetch_openingdonkey, 4 },
    { nSCKindOpeningLink, sSCPrefetch_openinglink, 7 },
    { nSCKindOpeningSamus, sSCPrefetch_openingsamus, 4 },
    { nSCKindOpeningYoshi, sSCPrefetch_openingyoshi, 10 },
    { nSCKindOpeningKirby, sSCPrefetch_openingkirby, 10 },
    { nSCKindOpeningFox, sSCPrefetch_openingfox, 5 },
    { nSCKindOpeningPikachu, sSCPrefetch_openingpikachu, 4 },
    { nSCKindOpeningRun, sSCPrefetch_openingrun, 3 },
    { nSCKindOpeningCliff, sSCPrefetch_openingcliff, 4 },
    { nSCKindOpeningYamabuki, sSCPrefetch_openingyamabuki, 5 },
    { nSCKindOpeningJungle, sSCPrefetch_openingjungle, 3 },
    { nSCKindOpeningYoster, sSCPrefetch_openingyoster, 5 },
    { nSCKindOpeningSector, sSCPrefetch_openingsector, 5 },
    { nSCKindOpeningStandoff, sSCPrefetch_openingstandoff, 4 },
    { nSCKindOpeningClash, sSCPrefetch_openingclash, 5 },
    { nSCKindOpeningNewcomers, sSCPrefetch_openingnewcomers, 4 },
    { nSCKindTitle, sSCPrefetch_title, 10 },
};

#endif /* SSB_DC_SCPREFETCH_H */
