/* wpmanager.c -- wp/wpmanager.c, the weapon manager: the WPStruct pool
 * every projectile is drawn from, and making a weapon GObj from a WPDesc.
 * Function-for-function against the game's own WPStruct (wp/wptypes.h);
 * every function names its decomp line range, and what is left out is
 * marked DIVERGES where it happens.
 *
 * The pool half -- wpManagerAllocWeapons, GetNextStructAlloc,
 * SetPrevStructAlloc, GetGroupID -- is verbatim: it touches nothing but
 * the free list and syTaskmanMalloc.
 *
 * wpManagerMakeWeapon (0x801655C8) is ported whole with ONE divergence,
 * the model. The game builds the weapon's DObj tree by reading a
 * DObjDesc (or a bare display list) out of the weapon's relocData file
 * -- WPAttributes.data -- through gcSetupCustomDObjs / gcAddDObjForGObj,
 * then hangs an MObj chain and animation joints off it. The port has no
 * such file loaded (as src/dc/efmanager.c has none of its three effect
 * files): a model is a pack built ahead of time by a per-fighter
 * exporter out of the very same DObjDesc, resolved from a small table
 * keyed on the WPDesc, and drawn by src/dc/fighter.c. That is the same
 * substitution efManagerAddModel makes for effects, and it is confined
 * to wpManagerAddModel below -- everything else in MakeWeapon is
 * verbatim, including the WPAttributes read (lbRelocGetFileData works
 * over whatever base the caller's WPDesc names, which is the fighter's
 * data file in game and a caller-owned buffer under test).
 *
 * The table is empty for now: no fighter's weapon is exported yet (ft/ftchar/
 * is the next frontier), so a real spawn is refused with a line on the serial
 * log rather than drawing nothing -- exactly efManagerAddModel's contract.
 * Because no fighter special is ported, MakeWeapon has no in-game caller yet
 * either, so the refuse path is all that runs on target; the host cross-test
 * builds a stub DObj so every field-fill and proc wiring is verified against
 * the decomp.
 *
 * The decomp's 52-byte BSS pad at 0x8018CFFC is N64 link padding with
 * no field of its own; the port has its own memory map and drops it.
 */
#include <wp/weapon.h>
#include <wp/wpmanager.h>
#include <ft/fighter.h>
#include <it/item.h>
#include <gm/generic.h>
#include <reloc_data.h>
#include <sys/objhelper.h>
#include <sys/debug.h>         /* syDebugPrintf */
#include <sc/scmanager.h>      /* scManagerRunPrintGObjStatus */

#ifdef FT_HOSTTEST
#include "hoststubs.h"
#else
#include <kos.h>
#endif

#include <stdlib.h>
#include <string.h>

#include <sys/taskman.h>
#include <sys/develop.h>

#include "fighter.h"
#include "itempack.h"          /* itemPackWeaponAttr */
#include "wpattrs.h"           /* wpAttrsBindJoltB */
#include "objmodel.h"
#include "taskman.h"          /* syTaskmanSetDrawPassHook */

/* // // // // // // // // // // // //
 *                                   //
 *   GLOBAL / STATIC VARIABLES       //
 *                                   //
 * // // // // // // // // // // // // */

/* 0x8018CFF0 - Points to next available weapon struct */
WPStruct *sWPManagerStructsAllocFree;

/* 0x8018CFF4 */
s32 sWPManagerDisplayMode;

/* 0x8018CFF8 */
u32 sWPManagerGroupID;

/* reloc_data.us.h declares a per-fighter weapon's attribute offset as an
 * `extern int ll<Char><File><Weapon>WeaponAttributes` whose ADDRESS is the
 * offset into the fighter's loaded relocData file -- the same absolute
 * linker symbol scheme mp/mpcollision.c leans on for stage files (see the
 * MPSHIM note in src/dc/mpshim.c). The 15 weapon-table symbols have their
 * real values: wpattrs.ld, generated by tools/export/ssb_wpattrexport.py from
 * the same header, defines each as its table's ROM offset, and
 * src/dc/wpattrs.c binds the file pointer the WPDesc names to a baked
 * blob of that file's tables, so wpManagerMakeWeapon's verbatim
 * lbRelocGetFileData lands on the real hitbox. (A 4-byte `int`
 * stand-in would be read as a 0x34-byte table, so every projectile
 * would spawn model-less with a zero hitbox.) A definition here would
 * collide with the .ld's --
 * tools/check/wpattr_check.py refuses one.
 *
 * The jolt's second animation. wpPikachuThunderJoltGround-
 * AddAnim reads llPikachuSpecial3ThunderJoltB{,Mat}AnimJoint out of
 * gFTDataPikachuSpecial3 every time the crawler changes which line it is
 * riding. Those two are defined in src/dc/wpattrs.c, which says why they
 * cannot be `int`s here and how they are bound to the pack's tables.
 * (Kirby's copy table is src/dc/ftcommon.c's ftKirbyMainMotionBindOffsets.) */

/* sys/taskman.c:147 gSYTaskmanDLHeads, DIVERGES: the four
 * RSP display-list heads. The port has no display lists -- a port source
 * that would write one goes through src/dc/lbpdraw.h, whose LBPDRAW_MODEL
 * macros turn the gDP/gSP calls into PVR state or into nothing -- so the
 * heads exist for the display procs that still write the game's commands
 * and have nothing to read them:
 *   - wp/wpyoshi/wpyoshieggthrow.c's wpYoshiEggThrowProcDisplay, compiled
 *     unmodified: a pipe sync and an env colour on head 1 before
 *     wpDisplayDLHead1;
 *   - src/dc/itkabigon.c, itspear.c and itpippi.c, verbatim: pipe syncs
 *     and render modes on head 0 around Snorlax's, Clefairy's and the
 *     swarm's draws.
 * The definition lives here rather than in src/dc/taskman.c because
 * tools/check/lbparticle_check.py's oracle links taskman.c beside its own
 * driver, which defines these heads itself to count what the decomp's
 * particle code writes.
 *
 * The heads point into a scratch buffer, and wpManagerResetDLHeads puts
 * them back at its start before every draw pass. The N64 did that at the
 * top of each frame (sys/taskman.c:297-310). Without the reset, the
 * Yoshi's egg's 16 bytes a frame walk off a 64-command buffer and on
 * through .bss until they zero the item spawner's pool
 * (gITManagerAppearActor), whose search then never ends. The fifth row
 * is slack, so an overflow lands in the scratch; the check below stops
 * the game on it, as sys/taskman.c:324-327 prints it. Nothing ever reads
 * the buffer.
 *
 * The reset must not depend on a scene allocating a weapon pool: a scene
 * that left sSYTaskmanDrawPassHook NULL would never put the heads back
 * and every display-list command it wrote would advance them for good.
 * That is the Yoshi's-egg walk again, one level up: mvending.c's
 * room fade/light procs and scstaffroll.c's highlight proc write the
 * game's own gDPFillRectangle strokes here every pass, ~50-90 bytes a
 * frame, and with nothing resetting the head they marched out of this
 * buffer and straight through .bss -- through fgm.c's sLock (hence
 * nSCKindEnding's "m->type <= MUTEX_TYPE_RECURSIVE" assert in
 * fgm_advance, ~10 KB along) and on into taskman.c's own
 * sSYTaskmanDefaultFunction (hence nSCKindStaffroll's wild jump through
 * scene_draw, ~26 KB along). Both crashes were this one walk
 * at two different distances. The reset is installed at boot
 * (wpManagerInitDLHeads, called from src/game/ssb64/main.c) so it does
 * not depend on a scene having weapons; wpManagerAllocWeapons keeps its
 * own call, which is simply redundant. */
/* 64 commands, which every scene up to here lived inside,
 * is not enough for a 1P intro card. sc1pintro.c:1081
 * sc1PIntroVSFighterProcDisplay -- compiled unmodified, like the procs
 * above -- writes seven commands on head 0 for every fighter on the
 * card, four before the fighter and three after, and a card holds one
 * fighter per enemy the rung deals. The Fighting Polygons' rung
 * overflowed it at 560 bytes: ten fighters (the ten Polygon kinds
 * sc1PIntroSetupFighterFiles loads) times seven commands times eight
 * bytes, exactly. The Yoshi Team's rung shows twenty-one, which is
 * 1176. 512 commands is that worst card with the shadow, effect and
 * particle procs that share the head beside it, and room over. Nothing
 * reads the buffer -- the size is a bound on the walk the check below
 * catches, not a capacity -- so the cost is 20 K of .bss for the five. */
#define WPMANAGER_DL_SCRATCH_CMDS 512
static Gfx sWPManagerDLScratch[5][WPMANAGER_DL_SCRATCH_CMDS];
Gfx *gSYTaskmanDLHeads[4] = {
    sWPManagerDLScratch[0], sWPManagerDLScratch[1],
    sWPManagerDLScratch[2], sWPManagerDLScratch[3]
};

/* Installed by wpManagerAllocWeapons; syTaskmanCommonTaskDraw calls it
 * before each pass. */
static void wpManagerResetDLHeads(void)
{
    s32 i;

    for (i = 0; i < ARRAY_COUNT(gSYTaskmanDLHeads); i++)
    {
        if (gSYTaskmanDLHeads[i] > &sWPManagerDLScratch[i][WPMANAGER_DL_SCRATCH_CMDS])
        {
            syDebugPrintf("gtl : DLBuffer over flow !  kind = %d  vol = %d byte\n", i,
                          (s32)((uintptr_t)gSYTaskmanDLHeads[i] - (uintptr_t)sWPManagerDLScratch[i]));
            scManagerRunPrintGObjStatus();
#if defined(DB_HEAP_WALK) || defined(DB_STACK_GUARD) || defined(DB_HEAP_GUARD)
            /* src/dc/db.h's memory hunt: a head past the fifth row walked
             * through .bss, one pass ago -- stop here, where the print
             * above names the pass, and not wherever that write lands */
            if (gSYTaskmanDLHeads[i] >
                &sWPManagerDLScratch[4][WPMANAGER_DL_SCRATCH_CMDS])
            {
                abort();
            }
#endif
        }
        gSYTaskmanDLHeads[i] = sWPManagerDLScratch[i];
    }
}

/* Installs that reset for the whole run, not just for a scene that
 * allocates weapons -- see the walk this fixes in the comment above.
 * Called once from src/game/ssb64/main.c's boot, before the scene
 * manager's first scene; the host test's own driver gets it through
 * wpManagerAllocWeapons as before. */
void wpManagerInitDLHeads(void)
{
    syTaskmanSetDrawPassHook(wpManagerResetDLHeads);
    wpManagerResetDLHeads();
}

/* // // // // // // // // // // // //
 *                                   //
 *           FUNCTIONS               //
 *                                   //
 * // // // // // // // // // // // // */

/* wp/wpmanager.c:28-49 wpManagerAllocWeapons 0x801654B0, verbatim.
 * No bzero: the game leaves the pool uninitialised and lets
 * wpManagerMakeWeapon fill every field. */
void wpManagerAllocWeapons(void)
{
    WPStruct *wp;
    s32 i;

    syTaskmanSetDrawPassHook(wpManagerResetDLHeads);

    sWPManagerStructsAllocFree = wp = syTaskmanMalloc(sizeof(WPStruct) * WEAPON_ALLOC_MAX, 0x8);

    for (i = 0; i < (WEAPON_ALLOC_MAX - 1); i++)
    {
        wp[i].next = &wp[i + 1];
    }
    if (wp != NULL)
    {
        wp[i].next = NULL;
    }
    sWPManagerGroupID = 1;
    sWPManagerDisplayMode = nDBDisplayModeMaster;
}

/* wp/wpmanager.c:52-64 wpManagerGetNextStructAlloc 0x80165558, verbatim */
WPStruct* wpManagerGetNextStructAlloc(void)
{
    WPStruct *new_weapon = sWPManagerStructsAllocFree;
    WPStruct *get_weapon;

    if (new_weapon == NULL)
    {
        return NULL;
    }
    get_weapon = new_weapon;

    sWPManagerStructsAllocFree = new_weapon->next;

    return get_weapon;
}

/* wp/wpmanager.c:67-72 wpManagerSetPrevStructAlloc 0x80165588, verbatim */
void wpManagerSetPrevStructAlloc(WPStruct *wp)
{
    wp->next = sWPManagerStructsAllocFree;

    sWPManagerStructsAllocFree = wp;
}

/* wp/wpmanager.c:75-83 wpManagerGetGroupID 0x801655A0, verbatim.
 * The decomp warns: do NOT declare with a void argument -- PK Thunder
 * passes unused arguments to it. Kept as an empty-parens (unprototyped)
 * declaration to match, so a caller with extra args still links. */
u32 wpManagerGetGroupID()
{
    u32 group_id = sWPManagerGroupID++;

    if (sWPManagerGroupID == 0)
    {
        sWPManagerGroupID++;
    }
    return group_id;
}

/* DIVERGES: wp/wpmanager.c:227-260, the model -- and only there.
 *
 * The port's own: which pack a WPDesc's model was exported into. Keyed on
 * the WPDesc itself, for the same reason efManagerAddModel keys on the
 * EFDesc: the pair the game finds the model with -- which relocData file
 * (*wp_desc->p_weapon) and the DObjDesc's offset in it -- is not a number
 * the port holds, because the file is never loaded; the descriptor is the
 * same fact by a name the port really has.
 *
 * Every weapon has its row, each pointing wp_desc
 * at a baked .mdl; a WPDesc without one makes wpModelPackFor return NULL
 * and the spawn is refused on the serial log. The whole table and its helpers are
 * target-only: the host cross-test's wpManagerAddModel builds a stub
 * DObj instead (below), so none of this is compiled under FT_HOSTTEST. */
#ifndef FT_HOSTTEST
typedef struct WPModel
{
    const WPDesc *desc;
    const char *pack;
    Fighter *loaded;
    sb32 is_loaded;
} WPModel;

/* wpmariofireball.c's WPDesc, the key wpMarioFireballMakeWeapon hands to
 * wpManagerMakeWeapon (and thus to wpModelPackFor). Its p_weapon/o_attributes
 * are rewritten per shot, but the descriptor's address is stable, which is
 * what the table matches on. */
extern WPDesc dWPMarioFireballWeaponDesc;
extern WPDesc dWPFoxBlasterWeaponDesc;
extern WPDesc dWPSamusChargeShotWeaponDesc;
extern WPDesc dWPPikachuThunderJoltAirWeaponDesc;
extern WPDesc dWPYoshiStarWeaponDesc;
extern WPDesc dWPYoshiEggThrowWeaponDesc;
extern WPDesc dWPSamusBombWeaponDesc;
extern WPDesc dWPLinkBoomerangWeaponDesc;
extern WPDesc dWPKirbyCutterWeaponDesc;
extern WPDesc dWPPikachuThunderJoltGroundWeaponDesc;
extern WPDesc dWPPikachuThunderHeadWeaponDesc;
extern WPDesc dWPPikachuThunderTrailWeaponDesc;
extern WPDesc dWPLinkSpinAttackWeaponDesc;
extern WPDesc dWPNessPKFireWeaponDesc;
extern WPDesc dWPNessPKThunderHeadWeaponDesc;
extern WPDesc dWPNessPKThunderTrailWeaponDesc;
extern WPDesc dWPNessPKReflectHeadWeaponDesc;
extern WPDesc dWPNessPKReflectTrailWeaponDesc;
/* The Poké Ball monsters' own weapons. Their WPDdescs live
 * in the monster's file (it/itmonster/itnyars.c and its six siblings) and
 * their packs come from ITCommonObject rather than from a fighter's file,
 * which is why they are the first rows here whose model is not
 * tools/export/ssb_effectexport.py's. */
extern WPDesc dITNyarsWeaponCoinWeaponDesc;
extern WPDesc dITDogasWeaponSmogWeaponDesc;
extern WPDesc dITIwarkWeaponRockWeaponDesc;
extern WPDesc dITStarmieWeaponSwiftWeaponDesc;
/* TWO descriptors for one weapon kind. Beedrill's swarm
 * and the one Clefairy summons are the same nWPKindSpearSwarm and the
 * same procs; what differs is the WeaponAttributes table they read --
 * and so the model, which is why both have their own row. */
extern WPDesc dITSpearWeaponSwarmWeaponDesc;
extern WPDesc dITPippiWeaponSwarmWeaponDesc;
extern WPDesc dITKamexWeaponHydroWeaponDesc;
extern WPDesc dITFushigibanaWeaponRazorWeaponDesc;
extern WPDesc dGRSectorArwingWeaponLaser2DWeaponDesc;
extern WPDesc dGRSectorArwingWeaponLaser3DWeaponDesc;
extern WPDesc dITLGunAmmoWeaponDesc;
extern WPDesc dITStarRodWeaponStarWeaponDesc;
extern WPDesc dWPBossBulletNormalWeaponDesc;
extern WPDesc dWPBossBulletHardWeaponDesc;

static WPModel sWPManagerModels[] =
{
    /* Mario's (and Luigi's) fireball. One quad + CI4 sprite out
     * of relocData file 297, baked to romdisk/wpmariofireball.mdl by
     * tools/export/ssb_effectexport.py --what fireball. */
    { &dWPMarioFireballWeaponDesc, "wpmariofireball.mdl", NULL, FALSE },
    /* Fox's Blaster. One flat SHADE-coloured quad, no
     * texture, out of relocData file 316, baked to romdisk/wpfoxblaster.mdl
     * by tools/export/ssb_effectexport.py --what blaster. */
    { &dWPFoxBlasterWeaponDesc, "wpfoxblaster.mdl", NULL, FALSE },
    /* Samus's Charge Shot (relocData file 321) and Pikachu's
     * airborne Thunder Jolt (file 342). Both are one CI4-textured quad
     * bound straight to the weapon DObj -- the same path as the two
     * above, and the first projectiles modelled after the
     * Blaster.
     *
     * Both are the fighter's Special3 file while their WPAttributes are
     * in Special1, and both bake a 64x64 tile with its TLUT folded in --
     * no separate palette, so no MObj and no palette winding. */
    { &dWPSamusChargeShotWeaponDesc, "wpsamuschargeshot.mdl", NULL, FALSE },
    { &dWPPikachuThunderJoltAirWeaponDesc, "wppikachujolt.mdl", NULL, FALSE },
    /* Yoshi's stars (relocData 86) and his thrown egg (338).
     * Neither list is in one of Yoshi's own four files, which is why they
     * waited for the extern reloc walk -- see the Makefile's rules. The
     * stars are the first weapon in this port whose batch lerps ENV and
     * PRIM by the texel instead of reading SHADE; the env colour baked
     * into the pack is 0xFFFF00, and that is their yellow. */
    { &dWPYoshiStarWeaponDesc, "wpyoshistar.mdl", NULL, FALSE },
    { &dWPYoshiEggThrowWeaponDesc, "wpyoshieggthrow.mdl", NULL, FALSE },
    /* Samus's Bomb, the last weapon on the one-display-list
     * path and the only one of the five that carries an MObj -- which is
     * exactly why it needed the extern walk to
     * reach its MObjSub table. Two palettes, two frames of that MObj:
     * wpsamusbomb.c winds palette_id between them as the fuse burns, and
     * the pack carries both the way Mario's and Luigi's fireballs are
     * carried. */
    { &dWPSamusBombWeaponDesc, "wpsamusbomb.mdl", NULL, FALSE },
    /* Link's boomerang, the first weapon here whose model is
     * a DObjDesc TREE -- WEAPON_FLAG_DOBJDESC, so wpManagerMakeWeapon
     * takes gcSetupCustomDObjs' path above and its proc_display is
     * func_ovl3_80167618. Three joints, and the first weapon pack in this
     * port to carry an animation: the boomerang's tumble is an AnimJoint,
     * which dc_model_add_mobjs rebuilds the way an effect's is. */
    { &dWPLinkBoomerangWeaponDesc, "wplinkboomerang.mdl", NULL, FALSE },
    /* Kirby's Final Cutter blade. Flags 0x03 -- a tree, like
     * the boomerang, but one whose geometry hangs off DObjDLLink lists
     * rather than each node's own dl pointer, so its proc_display is
     * wpDisplayDObjTreeDLLinks. Both of its nodes carry exactly one link,
     * so every batch the pack holds is on the link the game would draw. */
    { &dWPKirbyCutterWeaponDesc, "wpkirbycutter.mdl", NULL, FALSE },
    /* Pikachu's ground Thunder Jolt -- the crawler his
     * airborne jolt becomes on contact, and the first weapon here whose
     * joints carry MObjs (six of them, one sprite array each) and whose
     * pack carries a MatAnimJoint to step through them. */
    { &dWPPikachuThunderJoltGroundWeaponDesc, "wppikachugjolt.mdl", NULL, FALSE },
    /* Pikachu's Thunder, the bolt's head and the trail
     * segments it drops behind it. They share one model -- one link
     * array, one display list, one MObj with four sprite frames -- so
     * both rows name the same pack, and wpModelLoad's is_loaded flag
     * means the second spawn of a bolt reads nothing. Their WPDesc flags
     * are 0x02, the one shape where attr->data is a DObjDLLink array
     * rather than a display list. */
    { &dWPPikachuThunderHeadWeaponDesc, "wppikachuthunder.mdl", NULL, FALSE },
    { &dWPPikachuThunderTrailWeaponDesc, "wppikachuthunder.mdl", NULL, FALSE },
    /* Link's Spin Attack, the thirteenth WPDesc this port
     * compiles. Flags 0x03 -- a DObjDesc tree with DL links, the cutter's
     * shape -- and the only weapon here whose attributes are in a
     * fighter's MAIN file rather than one of his Specials. Nine MObjs
     * over two joints, none of them stepping a sprite array: what their
     * MatAnimJoint moves is a colour. */
    { &dWPLinkSpinAttackWeaponDesc, "wplinkspin.mdl", NULL, FALSE },
    /* Ness's PK Fire spark. Flags 0x00, so its `data` is a
     * display list bound to one DObj, but unlike every other such weapon
     * here it draws through two MObjs with no picture -- one lit triangle
     * each -- and wpnesspkfire.c never touches them: the flicker is the
     * MatAnimJoint moving their light colours (p_matanim_joints, 336 +
     * 0x1E0). Baked by tools/export/ssb_effectexport.py --what pkfire. */
    { &dWPNessPKFireWeaponDesc, "wpnesspkfire.mdl", NULL, FALSE },
    /* PK Thunder's head (flags 0x03, a two-joint tree with
     * DL links, the ground jolt's shape) and its trail segments (flags
     * 0x02, Pikachu's Thunder's link array). Unlike Pikachu's, head and
     * trail are different models, so two packs. The trail's MObj is not
     * optional: wpnesspkthunder.c:400 and :632 write
     * DObjGetStruct(g)->mobj->texture_id_curr with no NULL check, a
     * random 0..2 into its three sprites. A reflect makes a new head and
     * new trails from the same two WPAttributes (239 @0x0C and @0x40), so
     * the Reflect rows name the same packs and wpModelLoad shares them. */
    { &dWPNessPKThunderHeadWeaponDesc, "wpnesspkthunder.mdl", NULL, FALSE },
    { &dWPNessPKReflectHeadWeaponDesc, "wpnesspkthunder.mdl", NULL, FALSE },
    { &dWPNessPKThunderTrailWeaponDesc, "wpnesspktrail.mdl", NULL, FALSE },
    { &dWPNessPKReflectTrailWeaponDesc, "wpnesspktrail.mdl", NULL, FALSE },
    /* Meowth's Coin, the first of the seven monster weapons.
     * Flags 0x01 -- WEAPON_FLAG_DOBJDESC, the boomerang's shape, so the
     * renderer walks the tree and reads each node's own `dl`. (This
     * comment said DOBJLINKS and `dobj->dl_link`; wp/wpdef.h:14-15
     * makes DOBJDESC 0x1 and DOBJLINKS 0x2, and the switch below reads
     * the flags at run time, so only the comment was ever wrong.) Its
     * model is a two-joint tree in
     * ITCommonObject at 0xd290, reached through the weapon's own
     * `WeaponAttributes NyarsCoin` table (0x8c8) rather than through an
     * item's. Baked by tools/export/ssb_itemmodelexport.py --weapons, the same
     * walk that bakes the items. */
    { &dITNyarsWeaponCoinWeaponDesc, "wpnyarscoin.mdl", NULL, FALSE },
    /* Koffing's Smog, flags 0x03 -- a tree with DL links, the
     * cutter's shape. Its pack is a two-joint tree in ITCommonObject at
     * 0x13100, and the weapon RESIZES ITS OWN HITBOX from the child
     * joint's scale every frame (itDogasWeaponSmogProcUpdate), which is
     * the one thing no other weapon here does. */
    { &dITDogasWeaponSmogWeaponDesc, "wpdogassmog.mdl", NULL, FALSE },
    /* Onix's Rock. Flags 0x01 (a tree with DL links) and the
     * one monster weapon whose three models are THREE FRAMES of one MObj
     * -- itIwarkWeaponRockMakeWeapon writes the same `random` that picked
     * its starting velocity into `dobj->child->mobj->texture_id_curr`,
     * which is a write that has a real MObj to land on.
     * Its pack is at 0xab98 in ITCommonObject. */
    { &dITIwarkWeaponRockWeaponDesc, "wpwarkrock.mdl", NULL, FALSE },
    /* Starmie's Swift. Flags 0x03 -- a tree with DL
     * links, the smog's shape -- and the only monster weapon whose
     * proc_setoff and proc_absorb are its own proc_hit rather than
     * NULL. Its pack is at 0x119d8 in ITCommonObject. */
    { &dITStarmieWeaponSwiftWeaponDesc, "wpstarmieswift.mdl", NULL, FALSE },    { &dITSpearWeaponSwarmWeaponDesc, "wpspearswarm.mdl", NULL, FALSE },
    { &dITPippiWeaponSwarmWeaponDesc, "wppippiswarm.mdl", NULL, FALSE },
    /* Blastoise's Hydro Pump. Flags 0x01, and the one
     * monster weapon whose proc_update writes its ATTACK OFFSET
     * rather than its size -- the child joint's X translation times
     * `lr` is where the stream's hitbox sits. Its pack is at 0x10748
     * in ITCommonObject. */
    { &dITKamexWeaponHydroWeaponDesc, "wpkamexhydro.mdl", NULL, FALSE },
    /* Saffron City's Venusaur razor. The first weapon here
     * whose WPDesc is an ITEM's in a STAGE file -- `p_weapon` is
     * &gITManagerCommonData and its attributes ride in the item pack's
     * WEAPON ATTRIBUTES section, which is what the lookup above consults
     * before the byte overlay. */
    { &dITFushigibanaWeaponRazorWeaponDesc, "wpfushigibanarazor.mdl", NULL, FALSE },
    /* Sector Z's Arwing laser, the stage's own weapons and
     * the last of the nine. ONE bolt serves both WPDescs -- the 2D wing
     * lasers and the aimed 3D bolt read the same display list
     * (relocData 153, 0x1C50) through two different WPAttributes, and
     * tools/export/ssb_effectexport.py --what arwinglaser asserts as much
     * before baking it once. Two rows because the lookup is by WPDesc, and
     * `wpModelLoad`'s `is_loaded` is per ROW -- the same shape Pikachu's
     * Thunder head/trail rows already take, so this is the
     * bolt's file read twice into two Fighters rather than shared, which
     * that precedent already accepts. */
    { &dGRSectorArwingWeaponLaser2DWeaponDesc, "wparwinglaser.mdl", NULL, FALSE },
    { &dGRSectorArwingWeaponLaser3DWeaponDesc, "wparwinglaser.mdl", NULL, FALSE },
    /* the Ray Gun's shot, one quad on the flags-0x00 path.
     * Its WPAttributes are in ITCommonData and its display list is in
     * ITCommonObject, tools/export/ssb_effectexport.py --what lgunammo. */
    { &dITLGunAmmoWeaponDesc, "wplgunammo.mdl", NULL, FALSE },
    /* the Star Rod's star. Its WPAttributes (tilt and smash
     * alike) name ITCommonObject's display list at 0x5458, the very list
     * Yoshi's stars draw, so it is Yoshi's pack under a second row, the
     * Arwing lasers' precedent. The item model exporter had read that
     * list as a tree and refused it. */
    { &dITStarRodWeaponStarWeaponDesc, "wpyoshistar.mdl", NULL, FALSE },
    /* Master Hand's finger rocket, the Normal and the Hard.
     * Flags 0x01 -- the boomerang's shape, a DObjDesc tree with each
     * node's own dl -- and two joints, 22 triangles, one 32x32 tile.
     * The first weapon tree in this port with NO AnimJoint: his bullet
     * only flies where wpbossbullet.c pushes it.
     *
     * Two rows and one pack: both WPAttributes name the same DObjDesc
     * array (dBossModel_DObjDescs_0x2CB8), the way the Arwing lasers
     * and the Thunder head/trail already do. His is also the only
     * weapon in the game whose attribute records live in a fighter's
     * MainMotion rather than a Special file. */
    { &dWPBossBulletNormalWeaponDesc, "wpbossbullet.mdl", NULL, FALSE },
    { &dWPBossBulletHardWeaponDesc, "wpbossbullet.mdl", NULL, FALSE },
};

static WPModel *wpModelPackFor(const WPDesc *wp_desc)
{
    s32 i;

    for (i = 0; i < (s32)ARRAY_COUNT(sWPManagerModels); i++)
    {
        if ((sWPManagerModels[i].desc != NULL) &&
            (sWPManagerModels[i].desc == wp_desc))
        {
            return &sWPManagerModels[i];
        }
    }
    return NULL;
}

/* efModelLoad's twin: mallocs the pack's Fighter once and keeps it for the
 * run (the malloc heap is not the scene heap), rather than a static per
 * weapon. See src/dc/efmanager.c for why load-time allocation and not
 * .bss. */
static Fighter *wpModelLoad(WPModel *m)
{
    int pal_bank = 0;

    if (!m->is_loaded)
    {
        Fighter *pack;
        u32 i;

        /* Two rows can name one file -- the Thunder's head and trail share
         * wppikachuthunder.mdl -- and the preload below loads one copy
         * for both rows in one tic. A row whose file
         * another row has is a pointer to that row's, as efModelLoad's. */
        for (i = 0; i < ARRAY_COUNT(sWPManagerModels); i++)
        {
            if (sWPManagerModels[i].is_loaded &&
                strcmp(sWPManagerModels[i].pack, m->pack) == 0)
            {
                m->loaded = sWPManagerModels[i].loaded;
                m->is_loaded = TRUE;
                return m->loaded;
            }
        }
        pack = malloc(sizeof(Fighter));

        if (pack == NULL)
        {
            syDebugPrintf("wpmanager: no room for %s's Fighter\n", m->pack);
            return NULL;
        }
        if (fighter_load(pack, m->pack, &pal_bank) != 0)
        {
            free(pack);
            return NULL;
        }
        m->loaded = pack;
        m->is_loaded = TRUE;
    }
    return m->loaded;
}

#ifndef FT_HOSTTEST
/* What attr->anim_joints would have been: the pack's animation 0 as one
 * AObjEvent32* per pack joint, rebuilt from its word indexes the way
 * src/dc/itemmodel.c itemModelAnimJoints does for an item's. NULL when
 * the pack carries no animation. gcAddAnimJointAll reads the table once
 * and keeps only the scripts, which are in the pack. */
static AObjEvent32 *sWPManagerAnimJoints[FIGHTER_MAX_JOINTS];

static AObjEvent32 **wpModelAnimJoints(const Fighter *f)
{
    const FPackAnim *anim;
    const s32 *entries;
    u32 i;

    if (f->hd->anim_count == 0)
    {
        return NULL;
    }
    anim = &f->anims[0];
    entries = (const s32 *)((const u8 *)f->blob + anim->off_entries);

    for (i = 0; i < ARRAY_COUNT(sWPManagerAnimJoints); i++)
    {
        sWPManagerAnimJoints[i] = NULL;

        if ((i < f->hd->joint_count) && (entries[i] >= 0) &&
            ((u32)entries[i] < anim->nwords))
        {
            sWPManagerAnimJoints[i] =
                (AObjEvent32 *)((u8 *)f->blob + anim->off_words) + entries[i];
        }
    }
    return sWPManagerAnimJoints;
}

/* The MatAnimJoint half of the same thing: what the decomp's
 * `AObjEvent32 ***p_matanim_joints` is, one row per pack joint pointing at
 * that joint's MObj scripts, from the pack's own MatAnimJoint (alt 0),
 * built the way src/dc/objmodel.c dc_model_add_mobjs_alt builds its own.
 * Static, because the one caller (the Thunder Jolt's second attach) keeps
 * it for as long as the pack is loaded. NULL when the pack has no MObjs. */
#define WPMANAGER_MAT_SCRIPTS_MAX 64
static AObjEvent32 *sWPManagerMatScripts[WPMANAGER_MAT_SCRIPTS_MAX];
static AObjEvent32 **sWPManagerMatRows[FIGHTER_MAX_JOINTS];

static AObjEvent32 ***wpModelMatAnimJoints(const Fighter *f)
{
    const FPackMObjs *mo = f->mobjs;
    const s32 *entries;
    u32 i;

    if ((mo == NULL) || (mo->mobj_count > WPMANAGER_MAT_SCRIPTS_MAX))
    {
        return NULL;
    }
    entries = (const s32 *)((const u8 *)f->blob + mo->off_entry);

    for (i = 0; i < mo->mobj_count; i++)
    {
        sWPManagerMatScripts[i] = (entries[i] < 0) ? NULL
            : (AObjEvent32 *)((u32 *)((u8 *)f->blob + mo->off_words) + entries[i]);
    }
    for (i = 0; i < ARRAY_COUNT(sWPManagerMatRows); i++)
    {
        sWPManagerMatRows[i] = ((i < f->hd->joint_count) && (f->mobj_joint[i * 2 + 1] != 0))
            ? &sWPManagerMatScripts[f->mobj_joint[i * 2]]
            : NULL;
    }
    return sWPManagerMatRows;
}
#endif

/* Every weapon's pack, now (src/dc/wpattrs.h).
 *
 * The preload, and why (DIVERGES). On the N64 none of this is a load at all:
 * the models live in relocData files the battle has loaded before the first
 * tic -- the common effect and item files, each fighter's Special files -- and
 * making one is pointer arithmetic. The port bakes a pack per model; reading
 * each off the disc the first time it was made would mean, in the middle of a
 * match, a pause on the game thread while the drive seeks, and the read path
 * behind the Poke Ball freeze (src/dc/assetroot.c asset_read).
 * scVSBattleStartBattle calls this beside the rest of the battle's loading, so
 * a match reads nothing; what is loaded is kept for the run, as it always was.
 * Every row, not the ones this roster and this stage can reach: the set is
 * small, and a census would be one more thing to fall out of date. */
void wpManagerPreloadModels(void)
{
    u32 i;

    for (i = 0; i < ARRAY_COUNT(sWPManagerModels); i++)
    {
        (void)wpModelLoad(&sWPManagerModels[i]);
    }
}

/* Give every loaded pack back; rows that share one (wpModelLoad) free it
 * once. Safe to call twice. */
void wpManagerReleaseModels(void)
{
    u32 i, j;

    for (i = 0; i < ARRAY_COUNT(sWPManagerModels); i++)
    {
        Fighter *pack = sWPManagerModels[i].loaded;

        if (!sWPManagerModels[i].is_loaded)
        {
            continue;
        }
        for (j = i; j < ARRAY_COUNT(sWPManagerModels); j++)
        {
            if (sWPManagerModels[j].is_loaded &&
                sWPManagerModels[j].loaded == pack)
            {
                sWPManagerModels[j].loaded = NULL;
                sWPManagerModels[j].is_loaded = FALSE;
            }
        }
        if (pack != NULL)
        {
            fighter_release(pack);
            free(pack);
        }
    }
}

/* wp/wpmanager.c:249-250's transform triple. gcSetupCustomDObjs /
 * lbCommonInitDObj3Transforms install one XObj per non-Null kind, in
 * order; dc_model_add_dobjs has already installed gcAddDObjRpyR's three
 * (Tra, RotRpyR, Sca), so what is left is to rewrite their kinds -- the
 * same rewrite efManagerSetTransformTypes makes for effects (which see
 * for the fused-kind case). Applied to every DObj, as the DObjDesc branch
 * (gcSetupCustomDObjs) does. */
static void wpManagerSetTransformTypes(DObj *dobj, const DObjTransformTypes *types)
{
    u8 kinds[3];
    s32 i;

    kinds[0] = types->tk1;
    kinds[1] = types->tk2;
    kinds[2] = types->tk3;

    if (kinds[0] == nGCMatrixKindTraRotRpyRSca &&
        kinds[1] == nGCMatrixKindNull && kinds[2] == nGCMatrixKindNull)
    {
        kinds[0] = nGCMatrixKindTra;
        kinds[1] = nGCMatrixKindRotRpyR;
        kinds[2] = nGCMatrixKindSca;
    }
    if (dobj->xobjs_num < 3)
    {
        return;
    }
    for (i = 0; i < 3; i++)
    {
        dobj->xobjs[i]->kind = kinds[i];
    }
}
#endif

/* The one divergence, folded into a helper so MakeWeapon reads verbatim.
 * Returns FALSE if the weapon cannot get a model -- MakeWeapon then
 * unwinds (SetPrevStructAlloc + gcEjectGObj) exactly as it does when
 * gcMakeGObjSPAfter fails. Must leave a DObj on weapon_gobj on success,
 * because everything below it reads DObjGetStruct(weapon_gobj)->translate.
 *
 * Replaces wp/wpmanager.c:227-260: the WEAPON_FLAG_DOBJDESC branch's
 * gcSetupCustomDObjs / the else branch's gcAddDObjForGObj +
 * lbCommonInitDObj3Transforms that build the tree, and the gcAddMObjAll /
 * gcAddAnimAll under them. The proc_display selection and gcAddGObjDisplay
 * stay in MakeWeapon: they pick one of the four wpDisplay renderers by the
 * WPDesc flags and are not model-specific. */
/* The one decision the target arm of wpManagerAddModel makes about what a
 * weapon may be, as a function rather than a condition, for one reason: it
 * is the thing a HOST test can check. The two arms of that #ifdef cannot
 * agree structurally -- the host has no renderer and so no model packs at
 * all -- and they must agree about ACCEPTANCE: a host that built a bare
 * DObj unconditionally while the target refused anything without a
 * pack would pass every host test for a weapon the console
 * would not make. Saffron City's Charmander's flame (whose `data` is NULL
 * on purpose -- an invisible hitbox drawn entirely by particles) is what
 * exposed it.
 *
 * A weapon with no display list is legal in the decomp's own terms: its
 * non-DOBJDESC arm is `gcAddDObjForGObj(gobj, attr->data)`, and with a
 * NULL data that is a bare DObj. */
sb32 wpManagerIsModelLess(WPAttributes *attr)
{
    return (attr->data == NULL);
}

/* The one divergence, folded into a helper so MakeWeapon reads verbatim.
 * Returns FALSE if the weapon cannot get a model -- MakeWeapon then
 * unwinds (SetPrevStructAlloc + gcEjectGObj) exactly as it does when
 * gcMakeGObjSPAfter fails. Must leave a DObj on weapon_gobj on success,
 * because everything below it reads DObjGetStruct(weapon_gobj)->translate.
 */
#ifdef FT_HOSTTEST
/* No packs on the host (wpManagerAddModel below). */
void wpManagerPreloadModels(void)
{
}

void wpManagerReleaseModels(void)
{
}
#endif

static sb32 wpManagerAddModel(GObj *weapon_gobj, WPDesc *wp_desc, WPAttributes *attr)
{
#ifdef FT_HOSTTEST
    /* The host cross-test links the scene but not the renderer, so there
     * is no pack to build a tree from; a bare DObj gives MakeWeapon the
     * translate it writes below and lets every field-fill be checked. As
     * efManagerAddModel's host arm. */
    (void)wp_desc;
    (void)attr;

    if (gcAddDObjRpyR(weapon_gobj, NULL) == NULL)
    {
        return FALSE;
    }
    /* A per-fighter MakeWeapon wrapper (wpMarioFireballMakeWeapon and its
     * kin) writes the model's animation frame into DObjGetStruct(g)->mobj->
     * palette_id after the weapon is made. The bare DObj above carries no
     * MObj, so give the host stub a real one from the pool -- not a static:
     * gcEjectDObj hands every dobj->mobj back with gcSetMObjPrevAlloc, and a
     * static would corrupt the allocator on the weapon's eject. gcAddMObj-
     * ForDObj takes a pool MObj and links it, so the eject frees it clean. */
    {
        static MObjSub stub_sub;    /* zeroed; gcAddMObjForDObj copies it */
        gcAddMObjForDObj(DObjGetStruct(weapon_gobj), &stub_sub);
    }
    return TRUE;
#else
    WPModel *m;
    Fighter *pack;
    DObj *root;

    /* THE DATA-LESS ARM, first, and it is the decomp's own: a weapon whose
     * attributes name no `data` has no display list and no model to look a
     * pack up for. Take it before wpModelPackFor, which would refuse. */
    if (wpManagerIsModelLess(attr) != FALSE)
    {
        if (gcAddDObjRpyR(weapon_gobj, NULL) == NULL)
        {
            return FALSE;
        }
        wpManagerSetTransformTypes(DObjGetStruct(weapon_gobj),
                                   &wp_desc->transform_types);
        return TRUE;
    }

    m = wpModelPackFor(wp_desc);

    if (m == NULL)
    {
        syDebugPrintf("wpmanager: no pack for the WPDesc at 0x%08X\n",
                      (unsigned)(uintptr_t)wp_desc);
        return FALSE;
    }
    pack = wpModelLoad(m);

    if (pack == NULL)
    {
        syDebugPrintf("wpmanager: %s did not load\n", m->pack);
        return FALSE;
    }
    if (dc_model_add_dobjs(weapon_gobj, NULL, pack, NULL) < 0)
    {
        syDebugPrintf("wpmanager: no DObj tree for %s\n", m->pack);
        return FALSE;
    }
    root = DObjGetStruct(weapon_gobj);

    if (root != NULL)
    {
        DObj *dobj;

        wpManagerSetTransformTypes(root, &wp_desc->transform_types);

        for (dobj = gcGetTreeDObjNext(root); dobj != NULL;
             dobj = gcGetTreeDObjNext(dobj))
        {
            wpManagerSetTransformTypes(dobj, &wp_desc->transform_types);
        }
    }
    /* wp/wpmanager.c:273-281's gcAddMObjAll / gcAddAnimAll, as the pack's
     * own sections -- dc_model_add_mobjs is gcAddMObjAll followed by
     * gcAddMatAnimJointAll. A pack with no MObjs does nothing, which is
     * fine. */
    dc_model_add_mobjs(weapon_gobj, pack, 0.0F);

    /* The AnimJoint half, attr->anim_joints, as the pack's animation 0.
     * Without it no weapon tree moves on its own: Link's
     * boomerang did not spin (its joint 1 turns ROTX 0 to 2pi every six
     * frames, LinkSpecial3 0x6CC), and neither did Kirby's cutter,
     * Link's Spin Attack, the ground Thunder Jolt or PK Thunder's head.
     * The decomp's condition, on the record: a weapon whose attributes
     * name no AnimJoint does not get one. */
    if (attr->anim_joints != NULL)
    {
        AObjEvent32 **anim_joints = wpModelAnimJoints(pack);

        if (anim_joints != NULL)
        {
            gcAddAnimJointAll(weapon_gobj, anim_joints, 0.0F);
        }
    }
    /* The ground Thunder Jolt plays that same animation again every time
     * it changes which line it rides (wpPikachuThunderJoltGroundAddAnim,
     * which hands gcAddAnimAll Special3's ThunderJoltB tables -- the very
     * ones its attributes name, so they are the pack's animation 0 and
     * its MatAnimJoint). Point the two symbols at the pack's. */
    if (wp_desc == &dWPPikachuThunderJoltGroundWeaponDesc)
    {
        wpAttrsBindJoltB((void **)wpModelAnimJoints(pack),
                         (void ***)wpModelMatAnimJoints(pack),
                         pack->hd->joint_count);
    }
    return TRUE;
#endif
}

/* wp/wpmanager.c:86-346 wpManagerMakeWeapon 0x801655C8. Verbatim but for
 * the model, which is wpManagerAddModel above (DIVERGES there). */
GObj* wpManagerMakeWeapon(GObj *parent_gobj, WPDesc *wp_desc, Vec3f *spawn_pos, u32 flags)
{
    GObj *weapon_gobj;
    void (*proc_display)(GObj*);
    WPAttributes *attr;
    WPStruct *wp;
    WPStruct *owner_wp;
    ITStruct *ip;
    FTStruct *fp;

    wp = wpManagerGetNextStructAlloc();

    if (wp == NULL)
    {
        return NULL;
    }
    weapon_gobj = gcMakeGObjSPAfter(nGCCommonKindWeapon, NULL, nGCCommonLinkIDWeapon, GOBJ_PRIORITY_DEFAULT);

    if (weapon_gobj == NULL)
    {
        wpManagerSetPrevStructAlloc(wp);
        return NULL;
    }
    /* DIVERGES: the decomp is one line, the byte overlay below. That
     * works for every FIGHTER's weapon -- four pointers are 16 bytes on
     * the SH4 as on the N64 -- but not for a STAGE's: `*wp_desc->p_weapon` is
     * `&gGRCommonStruct.<stage>.item_head`, and this port has no stage map
     * file for it to point into. Saffron City's Charmander and Venusaur
     * carry their tables in the item pack instead, keyed by the same
     * `o_attributes`, and so do ITCommonData's own twelve (the Ray Gun,
     * Fire Flower, Star Rod and Poke Ball monsters' weapons), whose
     * bytes in the pack are the ROM's big-endian bitfields and cannot be
     * overlaid either. itemPackWeaponAttr answers for those and returns
     * NULL for everything else, which falls through to the decomp's own
     * arithmetic. */
    attr = itemPackWeaponAttr(*wp_desc->p_weapon, wp_desc->o_attributes);

    if (attr == NULL)
    {
        attr = lbRelocGetFileData(WPAttributes*, *wp_desc->p_weapon, wp_desc->o_attributes);
    }
    weapon_gobj->user_data.p = wp;
    wp->weapon_gobj = weapon_gobj;
    wp->kind = wp_desc->kind;

    switch (flags & WEAPON_MASK_PARENT)
    {
    case WEAPON_FLAG_PARENT_FIGHTER: // Weapons spawned by fighters
        fp = ftGetStruct(parent_gobj);
        wp->owner_gobj = parent_gobj;
        wp->team = fp->team;
        wp->player = fp->player;
        wp->handicap = fp->handicap;
        wp->player_num = fp->player_num;
        wp->lr = fp->lr;

        wp->display_mode = fp->display_mode;

        wp->attack_coll.stale = ftParamGetStale(fp->player, fp->motion_attack_id, fp->motion_count);
        wp->attack_coll.motion_attack_id = fp->motion_attack_id;
        wp->attack_coll.motion_count = fp->motion_count;
        wp->attack_coll.stat_flags = fp->stat_flags;
        wp->attack_coll.stat_count = fp->stat_count;
        break;

    case WEAPON_FLAG_PARENT_WEAPON: // Weapons spawned by other weapons
        owner_wp = wpGetStruct(parent_gobj);
        wp->owner_gobj = owner_wp->owner_gobj;
        wp->team = owner_wp->team;
        wp->player = owner_wp->player;
        wp->handicap = owner_wp->handicap;
        wp->player_num = owner_wp->player_num;
        wp->lr = owner_wp->lr;

        wp->display_mode = owner_wp->display_mode;

        wp->attack_coll.stale = owner_wp->attack_coll.stale;
        wp->attack_coll.motion_attack_id = owner_wp->attack_coll.motion_attack_id;
        wp->attack_coll.motion_count = owner_wp->attack_coll.motion_count;
        wp->attack_coll.stat_flags = owner_wp->attack_coll.stat_flags;
        wp->attack_coll.stat_count = owner_wp->attack_coll.stat_count;
        break;

    case WEAPON_FLAG_PARENT_ITEM: // Weapons spawned by items
        ip = itGetStruct(parent_gobj);
        wp->owner_gobj = ip->owner_gobj;
        wp->team = ip->team;
        wp->player = ip->player;
        wp->handicap = ip->handicap;
        wp->player_num = ip->player_num;
        wp->lr = ip->lr;

        wp->display_mode = ip->display_mode;

        wp->attack_coll.stale = ip->attack_coll.stale;
        wp->attack_coll.motion_attack_id = ip->attack_coll.motion_attack_id;
        wp->attack_coll.motion_count = ip->attack_coll.motion_count;
        wp->attack_coll.stat_flags = ip->attack_coll.stat_flags;
        wp->attack_coll.stat_count = ip->attack_coll.stat_count;
        break;

    default: // Weapons spawned independently
    case WEAPON_FLAG_PARENT_GROUND:
        wp->owner_gobj = NULL;
        wp->team = WEAPON_TEAM_DEFAULT;
        wp->player = WEAPON_PORT_DEFAULT;
        wp->handicap = WEAPON_HANDICAP_DEFAULT;
        wp->player_num = 0;
        wp->lr = +1;

        wp->display_mode = sWPManagerDisplayMode;

        wp->attack_coll.motion_attack_id = nFTMotionAttackIDNone;
        wp->attack_coll.stale = WEAPON_STALE_DEFAULT;
        wp->attack_coll.motion_count = ftParamGetMotionCount();
        wp->attack_coll.stat_flags.attack_id = nFTStatusAttackIDNone;
        wp->attack_coll.stat_flags.is_smash_attack = wp->attack_coll.stat_flags.ga = wp->attack_coll.stat_flags.is_projectile = 0;
        wp->attack_coll.stat_count = ftParamGetStatUpdateCount();
        break;
    }
    wp->attack_coll.attack_state = nGMAttackStateNew;

    wp->physics.vel_air.x = wp->physics.vel_air.y = wp->physics.vel_air.z = 0.0F;
    wp->physics.vel_ground = 0.0F;

    wp->attack_coll.damage = attr->damage;
    wp->attack_coll.element = attr->element;

    wp->attack_coll.offsets[0].x = attr->attack_offsets[0].x;
    wp->attack_coll.offsets[0].y = attr->attack_offsets[0].y;
    wp->attack_coll.offsets[0].z = attr->attack_offsets[0].z;
    wp->attack_coll.offsets[1].x = attr->attack_offsets[1].x;
    wp->attack_coll.offsets[1].y = attr->attack_offsets[1].y;
    wp->attack_coll.offsets[1].z = attr->attack_offsets[1].z;

    wp->attack_coll.size = attr->size * 0.5F;

    wp->attack_coll.angle = attr->angle;

    wp->attack_coll.knockback_scale = attr->knockback_scale;
    wp->attack_coll.knockback_weight = attr->knockback_weight;
    wp->attack_coll.knockback_base = attr->knockback_base;

    wp->attack_coll.can_setoff = attr->can_setoff;

    wp->attack_coll.shield_damage = attr->shield_damage;

    wp->attack_coll.fgm_id = attr->sfx;

    wp->attack_coll.priority = attr->priority;

    wp->attack_coll.can_rehit_item = attr->can_rehit_item;
    wp->attack_coll.can_rehit_fighter = attr->can_rehit_fighter;
    wp->attack_coll.can_rehit_shield = FALSE;

    wp->attack_coll.can_hop = attr->can_hop;
    wp->attack_coll.can_reflect = attr->can_reflect;
    wp->attack_coll.can_absorb = attr->can_absorb;
    wp->attack_coll.can_not_heal = FALSE;
    wp->attack_coll.can_shield = attr->can_shield;

    wp->attack_coll.attack_count = attr->attack_count;

    wp->attack_coll.interact_mask = GMHITCOLLISION_FLAG_ALL;

    wpMainClearAttackRecord(wp);

    wp->hit_normal_damage = 0;
    wp->hit_refresh_damage = 0;
    wp->hit_attack_damage = 0;
    wp->hit_shield_damage = 0;
    wp->reflect_gobj = NULL;
    wp->absorb_gobj = NULL;

    wp->is_hitlag_victim = FALSE;
    wp->is_hitlag_weapon = FALSE;
    wp->is_camera_follow = FALSE;

    wp->group_id = 0;

    wp->is_static_damage = FALSE;

    wp->p_sfx = NULL;
    wp->sfx_id = 0;

    wp->shield_collide_angle = 0.0F;

    wp->shield_collide_dir.x = wp->shield_collide_dir.y = wp->shield_collide_dir.z = 0.0F;

    /* DIVERGES: wp/wpmanager.c:227-260, the model tree. wpManagerAddModel
     * builds a DObj on weapon_gobj (a pack tree on target, a stub under
     * test), and returns FALSE when a pack will not load -- which
     * unwinds exactly as gcMakeGObjSPAfter failing does. */
    if (wp_desc->flags & WEAPON_FLAG_DOBJDESC)
    {
        proc_display = (wp_desc->flags & WEAPON_FLAG_DOBJLINKS) ? wpDisplayDObjTreeDLLinks : func_ovl3_80167618;
    }
    else
    {
        proc_display = (wp_desc->flags & WEAPON_FLAG_DOBJLINKS) ? wpDisplayDObjDLLinks : wpDisplayDLHead1;
    }
    if (wpManagerAddModel(weapon_gobj, wp_desc, attr) == FALSE)
    {
        wpManagerSetPrevStructAlloc(wp);
        gcEjectGObj(weapon_gobj);
        return NULL;
    }
    gcAddGObjDisplay(weapon_gobj, proc_display, 14, GOBJ_PRIORITY_DEFAULT, ~0);

    wp->coll_data.p_translate = &DObjGetStruct(weapon_gobj)->translate.vec.f;
    wp->coll_data.p_lr = &wp->lr;

    wp->coll_data.map_coll.top = attr->map_coll_top;
    wp->coll_data.map_coll.center = attr->map_coll_center;
    wp->coll_data.map_coll.bottom = attr->map_coll_bottom;
    wp->coll_data.map_coll.width = attr->map_coll_width;
    wp->coll_data.p_map_coll = &wp->coll_data.map_coll;

    wp->coll_data.ignore_line_id = -1;
    wp->coll_data.floor_line_id = -1;
    wp->coll_data.ceil_line_id = -1;
    wp->coll_data.lwall_line_id = -1;
    wp->coll_data.rwall_line_id = -1;

    wp->coll_data.update_tic = gMPCollisionUpdateTic;
    wp->coll_data.mask_curr = 0;

    wp->coll_data.vel_push.x = 0.0F;
    wp->coll_data.vel_push.y = 0.0F;
    wp->coll_data.vel_push.z = 0.0F;

    gcAddGObjProcess(weapon_gobj, wpProcessProcWeaponMain, nGCProcessKindFunc, 3);
    gcAddGObjProcess(weapon_gobj, wpProcessProcSearchHitWeapon, nGCProcessKindFunc, 1);
    gcAddGObjProcess(weapon_gobj, wpProcessProcHitCollisions, nGCProcessKindFunc, 0);

    wp->proc_update    = wp_desc->proc_update;
    wp->proc_map       = wp_desc->proc_map;
    wp->proc_hit       = wp_desc->proc_hit;
    wp->proc_shield    = wp_desc->proc_shield;
    wp->proc_hop       = wp_desc->proc_hop;
    wp->proc_setoff    = wp_desc->proc_setoff;
    wp->proc_reflector = wp_desc->proc_reflector;
    wp->proc_absorb    = wp_desc->proc_absorb;
    wp->proc_dead      = NULL;

    wp->coll_data.pos_prev = DObjGetStruct(weapon_gobj)->translate.vec.f = *spawn_pos;

    if (flags & WEAPON_FLAG_COLLPROJECT)
    {
        switch (flags & WEAPON_MASK_PARENT)
        {
        default:
        case WEAPON_FLAG_PARENT_GROUND:
            break;

        case WEAPON_FLAG_PARENT_FIGHTER:
            mpCommonRunWeaponCollisionDefault(weapon_gobj, ftGetStruct(parent_gobj)->coll_data.p_translate, &ftGetStruct(parent_gobj)->coll_data);
            break;

        case WEAPON_FLAG_PARENT_WEAPON:
            mpCommonRunWeaponCollisionDefault(weapon_gobj, wpGetStruct(parent_gobj)->coll_data.p_translate, &wpGetStruct(parent_gobj)->coll_data);
            break;

        case WEAPON_FLAG_PARENT_ITEM:
            mpCommonRunWeaponCollisionDefault(weapon_gobj, itGetStruct(parent_gobj)->coll_data.p_translate, &itGetStruct(parent_gobj)->coll_data);
            break;
        }
    }
    wp->ga = nMPKineticsAir;

    wpProcessUpdateHitPositions(weapon_gobj);

    return weapon_gobj;
}
