#!/usr/bin/env python3
"""ssb64-dc: cut gSYSinTable out of the SSB64 US baserom.

The game's sine is a table, not a call. `syGetSinCosUShort` (lb/lbdef.h:85)
turns radians into an index with SINTABLE_RAD_TO_ID -- `(s32)(x * (2048 /
PI))` -- and reads gSYSinTable[id & 0x7FF], negating on bit 0x800. The
2,048 entries are sin scaled by 32768 over half a period, and everything in
the game that spins reads them: sys/matrix.c's syMatrixFastSin/Cos, and the
particle interpreter's vortex arm (lb/lbparticle.c:1372).

It is 0x1000 bytes of .data in the boot segment -- symbols/system.txt:608
puts it at 0x8003B950 -- so there is no yaml segment to cut, only an
address to convert: the `main` segment starts at ROM 0x1060 and vram
0x80000460, which makes the table ROM 0x3C550.

The port cannot compute it. The table is not the sine function rounded:
its second half mirrors about index 1023.5 rather than 1024, so
gSYSinTable[2047] is 0 where sin(2047*PI/2048)*32768 is 50, and the whole
second half is one entry out. A particle whose velocity is turned by that
arm would drift from the N64's by up to 51/32768 of its magnitude per
frame. tools/check/sintable_check.py is what states that as a bound and holds
the exported table to it.

Unlike the particle banks (tools/export/ssb_particleexport.py) this is not a
scene asset and does not go on the disc: 4 KB of constant math that every
scene reads, wanted before any file is open. It is emitted as C and
linked, byteswapped once here so the SH-4 reads it directly.

Usage:
  python3 tools/export/ssb_sinexport.py [--rom <rom.z64>] --emit-c <file>
  python3 tools/export/ssb_sinexport.py [--rom <rom.z64>] --out <file.bin>
"""
import argparse
import os
import struct
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ROM_DEFAULT = os.path.join(REPO_ROOT, "base_rom", "baserom.z64")

# symbols/system.txt:608 gSYSinTable = 0x8003B950; // size:0x1000, minus
# the `main` segment's vram (0x80000460) plus its ROM start (0x1060).
SINTABLE_VRAM = 0x8003B950
MAIN_VRAM = 0x80000460
MAIN_ROM = 0x1060
SINTABLE_ROM = SINTABLE_VRAM - MAIN_VRAM + MAIN_ROM     # 0x3C550
SINTABLE_LEN = 0x800                                    # entries, u16 each


def read_table(rom: bytes):
    """The 2,048 big-endian u16 of gSYSinTable, in the ROM's order."""
    return list(struct.unpack_from(">%dH" % SINTABLE_LEN, rom, SINTABLE_ROM))


def emit_c(table) -> str:
    out = ["/* Generated by tools/export/ssb_sinexport.py -- do not edit.",
           " *",
           " * gSYSinTable, the game's sine: 2,048 entries of sin scaled by",
           " * 32768 over half a period, read by syGetSinCosUShort",
           " * (lb/lbdef.h:85) and by sys/matrix.c's fast sin and cos. Cut",
           " * from the baserom at 0x%06X (symbols/system.txt:608 has it at" % SINTABLE_ROM,
           " * 0x%08X); tools/check/sintable_check.py says why it is cut and not" % SINTABLE_VRAM,
           " * computed. */",
           "#include <ssb_types.h>",
           "",
           "u16 gSYSinTable[0x%X] = {" % SINTABLE_LEN]
    for i in range(0, SINTABLE_LEN, 8):
        out.append("    " + " ".join("%6d," % v for v in table[i:i + 8]))
    out.append("};")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", default=ROM_DEFAULT)
    ap.add_argument("--emit-c", metavar="FILE", help="write the table as C")
    ap.add_argument("--out", metavar="FILE", help="write the table as raw u16")
    args = ap.parse_args()

    if not (args.emit_c or args.out):
        sys.exit("need --emit-c or --out")

    with open(args.rom, "rb") as f:
        rom = f.read()
    table = read_table(rom)

    for path, data in ((args.emit_c, emit_c(table).encode()),
                       (args.out, struct.pack("<%dH" % SINTABLE_LEN, *table))):
        if not path:
            continue
        os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
        with open(path, "wb") as f:
            f.write(data)
        print(f"{path}: {SINTABLE_LEN} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
