#!/usr/bin/env python3
"""ssb64-dc: libultra's __sinf and __cosf, made from the decomp at build time.

The game computes its sine and cosine with libultra's own functions,
ssb-decomp-re/src/libultra/gu/sinf.c and cosf.c, and the port needs the
same ones: the C library's differ in their last bits, and they do on 24 of the particle bank's 119 scripts, and the knockback
vector (ftCommonDamageInitDamageVars, src/dc/ftcommon.c) and
ftMainProcPhysicsMap go through both every frame. They are Cody and Waite:
reduce against a two-part PI, then a degree-9 odd polynomial evaluated in
*double* and rounded to float, so the SH-4 runs the doubles too.

The two files cannot be compiled as the decomp writes them, and this
repository does not carry copies of them (they are SGI's, and their notice
forbids it), so this script writes the port's versions from the decomp
tree in the image. It makes exactly two changes, and
tools/check/trig_check.py holds the output to the decomp line by line and
to the ROM's .rodata word by word:

  aliases    the `#pragma weak fsin = __sinf` / `sinf = __sinf` lines (and
             cosf's two) are dropped. A weak definition of `sinf` in an
             object file keeps the linker from pulling newlib's, so every
             `sinf` in the port -- src/dc/mtx.h's joint matrices, the
             renderer -- would silently become libultra's. The game's own
             code calls __sinf and __cosf (sys/utils.h), never the aliases.

  constants  each `{hi, lo}` word pair is swapped. PR/guint.h overlays a
             double with `struct { u32 hi; u32 lo; }`, which puts the high
             word at the low address: right on the N64, and on the SH-4 the
             low half -- P[1] would come out as -3.36e-17 instead of
             -0.1666666, and sin(x) would quietly become x, which for small
             angles looks entirely plausible. After the swap the member
             names read backwards; nothing reads `.word`, every use is `.d`.

sinf.c's output also defines __libm_qnan_f, the one word of
libultra/gu/libm_vals.s the two functions read: the NaN they return for a
NaN argument, 0x7F810000 at ROM 0x03FF70. Its quiet bit is clear -- MIPS's
convention for a quiet NaN and the opposite of the SH-4's -- so it is
spelled as the ROM's bit pattern rather than any NAN macro.

Usage:
  python3 tools/export/ssb_trigexport.py --decomp <ssb-decomp-re> \\
      --out-dir <dir>          (writes gusinf.c and gucosf.c)
"""
import argparse
import os
import re
import sys

# port file -> decomp file under src/libultra/gu
FILES = {"gusinf.c": "sinf.c", "gucosf.c": "cosf.c"}

PAIR = re.compile(r"\{\s*0x([0-9a-fA-F]{8}),\s*0x([0-9a-fA-F]{8})\s*\}")

QNAN = """
/* libultra/gu/libm_vals.s's __libm_qnan_f, 0x7F810000 at ROM 0x03FF70
 * (tools/export/ssb_trigexport.py says why it is spelled this way). */
float __libm_qnan_f = __builtin_nansf("0x10000");
"""


def generate(decomp, port):
    """The port's text of `port` (gusinf.c or gucosf.c), from the decomp
    checkout at `decomp`."""
    src = os.path.join(decomp, "src", "libultra", "gu", FILES[port])
    out = ["/* Generated by tools/export/ssb_trigexport.py from the decomp's\n"
           " * src/libultra/gu/%s -- its #pragma weak aliases dropped and its\n"
           " * constant word pairs swapped for a little-endian machine. Do not\n"
           " * edit; it is rewritten every build. */\n" % FILES[port]]
    with open(src) as f:
        for line in f:
            if line.startswith("#pragma weak"):
                continue
            out.append(PAIR.sub(lambda m: "{ 0x%s,\t0x%s }"
                                % (m.group(2), m.group(1)), line))
    if port == "gusinf.c":
        out.append(QNAN)
    return "".join(out)


def write_all(decomp, out_dir):
    paths = []
    for port in FILES:
        path = os.path.join(out_dir, port)
        text = generate(decomp, port)
        # Leave an unchanged file alone, so make does not rebuild it.
        try:
            with open(path) as f:
                if f.read() == text:
                    paths.append(path)
                    continue
        except FileNotFoundError:
            pass
        with open(path, "w") as f:
            f.write(text)
        paths.append(path)
    return paths


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--decomp", default=os.environ.get("SSB_DECOMP_DIR",
                                                       "/opt/ssb-decomp-re"))
    ap.add_argument("--out-dir", required=True)
    args = ap.parse_args()
    for path in write_all(args.decomp, args.out_dir):
        print("ssb_trigexport: wrote", path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
