#!/bin/bash
# ssb64-dc: build glank's gfxdis as a host tool for cross-checking our F3DEX2
# display-list decode.
#
# `gfxdis` is the original C reference display-list disassembler (the code that
# pygfxd / libgfxd is ported from). We build just the gfxdis.f3dex2 host binary
# with the host compiler (it is not an N64 tool; it runs on the build machine),
# supplying a tiny generated config.h so it builds without running autotools.
#
# The image builds this once from glankk/n64 at the revision in
# docker/pins.env; N64_DIR says where that checkout is.
#
# tools/check/verify_dl.py uses the output to independently confirm the macros
# and indices we decode, comparing it against pygfxd's.
#
# Usage: N64_DIR=<glankk/n64 checkout> tools/build_gfxdis.sh
#        [OUT_DIR=<dir>] [CONF_DIR=<dir>]
set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
N64_DIR="${N64_DIR:?set N64_DIR to a glankk/n64 checkout}"
OUT_DIR="${OUT_DIR:-$REPO_ROOT/tools/bin}"
CONF_DIR="${CONF_DIR:-$REPO_ROOT/build-dc/gfxdis-inc}"

CC="${CC:-gcc}"
VARIANT="f3dex2"
FLAGS="-DF3DEX_GBI_2"

if [ ! -d "$N64_DIR/src/gfxdis" ]; then
    echo "no gfxdis sources at $N64_DIR" >&2
    exit 1
fi

mkdir -p "$OUT_DIR" "$CONF_DIR"
cat > "$CONF_DIR/config.h" <<'EOF'
/* Auto-generated by tools/build_gfxdis.sh: enough of config.h to build the
 * gfxdis host tool without autotools. Host is little-endian; the guest DLs are
 * big-endian, which swap.h handles. */
#define PACKAGE "n64"
#define PACKAGE_NAME "gfxdis"
#define PACKAGE_VERSION "0.7"
#define VERSION "0.7"
EOF

echo "building gfxdis.$VARIANT (host $CC)..."
"$CC" -std=c11 -Wall "${FLAGS}" \
    -I "$CONF_DIR" \
    -I "$N64_DIR/src" \
    -I "$N64_DIR/include" \
    -I "$N64_DIR/src/gfxdis" \
    -o "$OUT_DIR/gfxdis.$VARIANT" \
    "$N64_DIR/src/gfxdis/main.c" \
    "$N64_DIR/src/gfxdis/gfxdis.c"

echo "built $OUT_DIR/gfxdis.$VARIANT"
